- cmd/server.go
- cmd/server_test.go
Fixes https://github.com/hootsuite/atlantis/issues/245
> Convert relative --data-dir paths to absolute.

- server/events/apply_executor.go
- server/events/mocks/mock_project_finder.go
- server/events/plan_executor.go
- server/events/project_finder.go
- server/events/project_finder_test.go
Fixes #12. Previously we would assume that if there was a change
in any modules/ directory, we should run plan in the parent. Now
we first check whether the parent has a main.tf file. If it doesn't
then we assume it's not actually the root of a project.
> Fix bug with top-level modules/ directory.

- server/events/apply_executor.go
- Fixes #22. We were running apply in the parent directory.
- Also changes error message if no plans are found to apply.
> Fix bug where apply -d was using parent dir.

- Dockerfile
See https://github.com/nodejs/docker-node/issues/380
> Use ipv4 keyservers to fix failing builds.

- cmd/server.go
- cmd/server_test.go
- server/server.go
- server/server_test.go
- server/web_templates.go
> Show atlantis version in index page

- server/events/vcs/github_client.go
- server/events/vcs/github_client_internal_test.go
- server/server.go
Fixes #55. GitHub will throw an error if the comment is over
65535 characters. Now we will split up a comment into multiple
comments if it's over that size.
> Split GitHub comments into multiple if over max.

- README.md
Within the README.md updated the following:
* Changed extra_arguments item to a valid argument.
* Rename `myvars.tfvars` to `terraform.tfvars`
* Updated the terraform version example value when referencing the env var `ATLANTIS_TERRAFORM_VERSION` to reflect the value of the var if the schema was run.
> Update extra_arguments schema example

- Dockerfile
Following advice from https://github.com/tianon/gosu/issues/35
> Fix Dockerfile build failures.

- README.md
- cmd/server.go
- cmd/server_test.go
- main.go
Fixes #38.
Builds off the great work by @psalaberria002 in #77.
> Allow specifying config values as environment variables

- server/events/comment_parser.go
- server/events/comment_parser_test.go
Saw in the TF code how they were validating workspace names
and decided to do the same. '..' is actually a valid TF workspace but we
don't support that.
> Validate workspace the same way as Terraform.

- server/events/terraform/terraform_client.go
- server/server.go
Fixes #34
- run terraform with TF_PLUGIN_CACHE_DIR set so that terraform init will
be faster.
- check which workspace we're in and don't switch unless we need to.
- run terraform with TF_IN_AUTOMATION set so the plan output doesn't
have instructions that don't make sense. Ex.
```
This plan was saved to: /tmp/atlantis/data/repos/lkysow/atlantis-example/3/default/default.tfplan
To perform exactly these actions, run the following command to apply:
terraform apply "/tmp/atlantis/data/repos/lkysow/atlantis-example/3/default/default.tfplan"
```
> Add plugin cache. Don't run workspace if unneeded.

- Gopkg.lock
- cmd/server.go
- This will make the help output easier to read. To accomplish this, we
needed to not set defaults via cobra because then the default would be
printed on another line which looks bad. So now we set the defaults
ourselves.
- Also had to update spf13/pflag to the version that supports newlines
in flag descriptions.
Fixes #54
> Add newlines between flags in help output.

- bootstrap/bootstrap.go
- bootstrap/utils.go
We use a config file so we can set ngrok's API port (web_addr). We use
the API to get the public URL and if there's already ngrok running, it
will just choose a random API port and we won't be able to get the right
url.
Fixes #92
> Use custom ngrok config so we can specify api url.

- Dockerfile
0.11.5 came out on March 21st. This upgrades the Terraform version in the Docker image.
> Upgrade latest TF to 0.11.5 in Dockerfile

- server/events/repo_whitelist.go
- server/events/repo_whitelist_test.go
This is okay to do because it's a better user experience and because
GitLab and GitHub project names are case insensitive as well.
Fixes #95
> Make repo whitelist case insensitive.

- CHANGELOG.md
- Dockerfile
- main.go
- Upgrade to Terraform 0.11.7
- Add SHA256 checksum verification for Terraform binaries
- Bump version to 0.3.8 and add release notes
> Add checksum verification for Terraform binaries, upgrade Terraform to 0.11.7

- README.md
Kubernetes sets ATLANTIS_PORT to a tcp://... address which Atlantis then
tries to parse so we need to set it ourselves.
Also add "v" to the version to make it obvious that the Docker images
all start with v.
> Set ATLANTIS_PORT.

- bootstrap/bootstrap.go
- bootstrap/utils.go
Hi,
Thanks for the work on this awesome project!
I've encountered a bug running `atlantis bootstrap` on Amazon Linux - the process failed to copy the Terraform binary to `/usr/local/bin` but the error got silently ignored. This error caused another error when running the Atlantis server, which got ignored, too.
Therefore, I've refactored the overall error handling inside the bootstrap process. It doesn't fix the permissions problem on Amazon Linux (`sudo` needs to be used, which is outside the scope of this PR), but it does show an error to the user instead of reporting that everything is OK.
Any comments are welcome :-)
> Improve error handling

- README.md
- cmd/bootstrap.go
- main.go
- scripts/coverage.sh
- testdrive/github.go
- testdrive/testdrive.go
- testdrive/utils.go
Bootstrap is meant for a system that sets itself up. This command is
more like a testing mode so I want to rename it to avoid confusion.
Fixes #129 and came out of #117.
> Rename bootstrap to testdrive.

- CONTRIBUTING.md
- README.md
👋 🐧:penguin: Going through `CONTRIBUTING.md` and updated 
- example `Run Atlantis` to include `--repo-whitelist` because of `v0.3.2`
- `Add Github Webhook` check boxes section with plural nouns to be consistent with Github
<details>
</details>
And should the bullet below be updated to recommend using a secret?
> - leave **Secret** blank or set this to a random key (https://www.random.org/strings/). If you set it, you'll need to use the `--gh-webhook-secret` option when you start Atlantis
Running without it warns
```
[WARN] No GitHub webhook secret set. This could allow attackers to spoof requests from GitHub. See https://git.io/vAF3t
```
> Update CONTRIBUTING.md atlantis command example, pluralize Webhook boxes

- .codecov.yml
Many pull requests that I've wanted to merge have failed CodeCov
statuses. This indicates that they're not useful for this project at
this time so I'm disabling them. The comment from CodeCov is the most
useful part.
> Disable code coverage GitHub statuses.

- README.md
> Add note about pull request approval and access control

- .gometalinter.json
- Makefile
- cmd/server.go
- server/events/comment_parser.go
- server/events/runtime/init_step_runner.go
- server/events/vcs/github_client.go
- server/events/yaml/raw/step.go
After update of errcheck, needed to explicitly disable checking fmt
functions.
> Add .gometalint.json config

- testdrive/testdrive.go
This will prevent old locks from a previous run from sticking around.
> Use temp dir for testdrive.

- Dockerfile
Was getting:
Connecting to github.com (192.30.253.112:443)
ssl_client: github.com: TLS connect failed
wget: error getting response: Connection reset by peer
> Add update-ca-certificates to fix Docker build.

- CHANGELOG.md
- main.go
- server/events/command_runner.go
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events_controller_e2e_test.go
- server/testfixtures/test-repos/modules/exp-output-autoplan-only-modules.txt
> Don't comment back on autoplan no projects.

- .gometalinter.json
- Dockerfile
- Dockerfile-base
- cmd/server.go
- docker-base/Dockerfile
- e2e/e2e.go
- server/events/project_config.go
- server/events/yaml/parser_validator.go
- server/recovery/recovery.go
- testdrive/utils.go
If users are using /etc/hosts then because CGO is disabled golang
doesn't look at that file. This fix makes it so /etc/hosts is respected.
Fixes #196
References:
* https://github.com/docker-library/golang/blob/master/1.9/alpine3.7/Dockerfile#L9
* https://github.com/golang/go/issues/22846
> Add file so /etc/hosts works in Docker.

- runatlantis.io/docs/apply-requirements.md
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketcloud/client_test.go
- server/events/vcs/bitbucketcloud/models.go
- server/events/vcs/bitbucketcloud/testdata/pull-approved-by-author.json
- server/events/vcs/bitbucketcloud/testdata/pull-approved-multiple.json
- server/events/vcs/bitbucketcloud/testdata/pull-approved.json
- server/events/vcs/bitbucketcloud/testdata/pull-unapproved.json
In Bitbucket cloud, the pull request author can approve their own pull
request. Ignore this approval.
Fixes #201
> Require approval from someone other than PR author

- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events/event_parser.go
Accept comments like
```
atlantis plan
```
So that when a comment is copy-pasted in GitHub and GitHub adds two
newlines, Atlantis still parses that comment.
> Ignore extra newlines in comments.

- runatlantis.io/.vuepress/components/HomeCustom.vue
New page looks slick!
- In the home page `applied` is used first so this changes `apply'd` to `applied` for consistency.
- Added periods at end of bullets for consistency.
Other feedback: currently `Know who apply'd the change and who approved it.` barely takes up 2 lines and may look awkward.
> Website: change apply'd to applied, add periods at end of bullets

- server/server.go
Server startup should be something expected therefore an info rather than a warning.
```
2018/08/28 18:37:50 [WARN] server: Atlantis started - listening on port 4141
```
Signed-off-by: Ben Abrams <me@benabrams.it>
> change server startup log message from warn to info level

- docker-base/Dockerfile
See https://justi.cz/security/2018/09/13/alpine-apk-rce.html
Fixes #271 
NOTE: I rebuilt `runatlantis/atlantis-base` locally on alpine 3.8 and pushed it. When I release the next version of Atlantis it will build from that new base image.
> Update to alpine 3.8 to fix security vuln.

- runatlantis.io/docs/server-configuration.md
- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
Add new variables to execute TF with:
```
-var atlantis_repo=owner/repo
-var atlantis_pull_num=10
```
These can be used within TF to set the session_name of the AWS session
that Terraform creates. This allows all API calls to be traced back to a
specific pull request and user.
Fixes #256, refactored work from @jolexa in #285
> Execute tf with vars that give source of run.

- server/events/models/models.go
- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
Fixes #290. In Bitbucket Server, the repo owner name can have spaces.
This causes errors when running terraform plan -out path with spaces so
we need to quote it: terraform plan -out "path with spaces".
> Quote the -out variable in terraform plan.

- runatlantis.io/docs/server-configuration.md
After trying out the new tf run variables implemented in #287 I found an error that I couldn't assume the role. I had a suspicion that the session_name was invalid so I consulted the [documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html).
The valid pattern for session_name is: `Pattern: [\w+=,.@-]*`
> The regex used to validate this parameter is a string of characters consisting of upper- and lower-case alphanumeric characters with no spaces. You can also include underscores or any of the following characters: =,.@-
> Update example for new tf run variables

- .gometalinter.json
- testdrive/utils.go
Atlantis currently errors when building on Windows with:
`testdrive\utils.go:44:40: cannot use syscall.Stdin (type syscall.Handle) as type int in argument to terminal.ReadPassword`
This pull request fixes this by type casting `syscall.Stdin` to `int`, as shown in Google's go-github example code: [main.go](https://github.com/google/go-github/blob/master/example/basicauth/main.go)
This should then successfully build on Windows and Linux.
> Testdrive readPassword fix to allow Windows build

- runatlantis.io/docs/server-configuration.md
- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
Previously we added -var atlantis_repo=runatlantis/atlantis but the '/'
character is not a valid character for the AWS assume role session name.
To fix this, this commit adds -var atlantis_repo_owner=runatlantis and
-var atlantis_repo_name=atlantis (where runatlantis and atlantis would
be the values for the repo the pull request is from ).
> Add new -var args for tf plan.

- cmd/server.go
- server/events_controller.go
- server/events_controller_test.go
- server/server.go
Fixes #312 
Some users would like to add the Atlantis webhook at the org level and then use the whitelist to configure which repos Atlantis actually runs on. In this configuration, it's annoying that Atlantis continually comments on pull requests "Repo is not whitelisted".
This PR adds a flag `--silence-whitelist-errors` which will prevent commenting back on the pull request.
> Add --silence-whitelist-errors server flag

- .gitignore
- server/events/project_locker.go
- server/events/project_locker_test.go
Just updating the message atlantis spits out when the project is locked. Once the locking plan is released, atlantis doesn't auto-run `plan` on subsequent PR's. This message makes it clear to users that they should manually run plan.
> Updating message when project is locked.

- .circleci/config.yml
- Dockerfile
- testing/Dockerfile
> Upgrade to terraform 0.11.8

- server/events/runtime/runtime.go
- server/events/runtime/runtime_test.go
- server/events/yaml/raw/project.go
- server/events/yaml/raw/project_test.go
Allow the project name in `atlantis.yaml` file to contain slashes:
```yaml
projects:
- dir: terraform/myservice
name: terraform/myservice
```
Also in this PR:
* Validate project names to ensure they don't contain invalid characters
* Ensure the planfile names (which are generated from the project names) don't contain invalid filename chars
Notes
* With commit from @johnlinvc in #319. I've added the validation of the config file and also changed the allowed filename chars regex
* Made change recommended by @kipkoan to only remove invalid filename chars
* Fixes #253
> Allow slashes in project names

- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events_controller_e2e_test.go
- server/testfixtures/test-repos/modules-yaml/exp-output-autoplan.txt
- server/testfixtures/test-repos/modules/exp-output-autoplan-only-staging.txt
- server/testfixtures/test-repos/modules/exp-output-plan-production.txt
- server/testfixtures/test-repos/modules/exp-output-plan-staging.txt
- server/testfixtures/test-repos/simple-yaml/exp-output-autoplan.txt
- server/testfixtures/test-repos/simple/exp-output-apply-var-all.txt
- server/testfixtures/test-repos/simple/exp-output-apply-var-default-workspace.txt
- server/testfixtures/test-repos/simple/exp-output-apply-var-new-workspace.txt
- server/testfixtures/test-repos/simple/exp-output-apply-var.txt
- server/testfixtures/test-repos/simple/exp-output-apply.txt
- server/testfixtures/test-repos/simple/exp-output-atlantis-plan-new-workspace.txt
- server/testfixtures/test-repos/simple/exp-output-atlantis-plan-var-overridden.txt
- server/testfixtures/test-repos/simple/exp-output-atlantis-plan.txt
- server/testfixtures/test-repos/simple/exp-output-autoplan.txt
- server/testfixtures/test-repos/simple/main.tf
- server/testfixtures/test-repos/tfvars-yaml-no-autoplan/exp-output-plan-default.txt
- server/testfixtures/test-repos/tfvars-yaml-no-autoplan/exp-output-plan-staging.txt
- server/testfixtures/test-repos/tfvars-yaml/exp-output-autoplan.txt
When running terraform plan, Terraform writes a line for each resource
it updates. For example:
null_resource.b: Refreshing state... (ID: 700288721293508840)
null_resource.a: Refreshing state... (ID: 2853194762920164292)
null_resource.f: Refreshing state... (ID: 6634469389761751950)
This change removes those lines by splitting the output string after a
separator.
This change is being made because the Refreshing output isn't important
and it will make the comments shorter.
From:
To:
Notes:
* This is thanks to suggestions from @jonboulle, @BlackTurtle123 and @majormoses 
* This will help with #280 and #111
> Remove "Refreshing..." output from top of plan.

- .dockerignore
This docker really speeds up the docker build as we do not have to send the entire repository to the docker daemon. We only send the files it actually needs
> Add a dockerignore to speedup docker build

- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/bitbucketserver/client_test.go
- server/events/vcs/bitbucketserver/models.go
Based on https://docs.atlassian.com/bitbucket-server/rest/5.15.0/bitbucket-rest.html the `nextPageStart` field should be an int.
> Use int instead of string for bitbucket response.

- cmd/server.go
- server/locks_controller.go
- server/router.go
- server/router_test.go
- server/server.go
- server/server_test.go
- server/url.go
- server/url_test.go
- server/web_templates.go
Resolves #213
Allows users to run Atlantis behind a shared reverse proxy, which is a fairly common use case.
`make test` passes for me, but `make test-all` does not, both on this branch and an unchanged master.
> Prefix URLs in templates with AtlantisURL

- server/server.go
The GitLab client doesn't do a good job logging errors if the hostname
isn't resolvable so we log an error early to help users.
Fixes #128
> Log warning if unable to resolve GitLab hostname.

- runatlantis.io/docs/deployment.md
After merging https://github.com/runatlantis/atlantis/pull/346, we now
support OpenShift however users need an additional flag to atlantis
server for it to work.
> Deployment docs for OpenShift.

- Dockerfile
- helm/atlantis/templates/statefulset.yaml
- Upon merging https://github.com/runatlantis/atlantis/pull/346 I
manually built and pushed a new version of runatlantis/atlantis-base and
tagged it as runatlantis/atlantis-base:v2.0. This change uses that new
tag. Before it was using :latest which isn't good if other people see
that and use atlantis-base:latest because we could break it for them.
- I've also put back the fsContext to 1000 because the atlantis user is
still in that group so we need that for kubernetes.
> Use latest atlantis-base.

- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
- server/server.go
On startup, make a call to the /version endpoint of Gitlab to get which
version we're running. Then use that version to determine whether we
should use the markdown folding syntax where the code is expandable.
Versions of Gitlab < 11.1 don't support the "Common Mark" markdown
format.
Fixes #315
> Disable markdown folding on gitlab < 11.1

- server/events/vcs/bitbucketcloud/client.go
Bitbucket released the 2.0 version for the commenting on pull requests
API:
https://community.atlassian.com/t5/Bitbucket-questions/Re-Bitbucket-Cloud-REST-API-v2-0-Commenting-on-Pull-Re/qaq-p/849427/comment-id/30070#M30070.
Previously, this was only available in version 1.0. Since 1.0 will be
deprecated, it's best to move to the latest version.
> Use Bitbucket 2.0 API for comments.

- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
If terraform plan returns an error, we still want to print the output to
the pull request.
> Return plan output on error.

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
Fixes https://github.com/runatlantis/atlantis/issues/377
I also added a unit test to check for this particular case.
> Fix URL parsing not working when passing only a domain to GitlabHostname

- scripts/e2e.sh
- server/events_controller.go
- server/events_controller_test.go
- server/gitlab_request_parser_validator.go
- server/gitlab_request_parser_validator_test.go
Detect if the GitLab event is a comment on a commit instead of a merge
request and log a debug message that we don't support this.
Previously, Atlantis would panic if it received this event.
Related to #150 and #390.
> Don't parse gitlab comment events when on commit

- server/events/command_runner.go
- server/events/command_runner_test.go
Previously, we were just logging when an error happened early in our
comment processing code. However it's possible for us to write comments
on error even at this early stage which will make for a better user
experience.
Fixes #398
> Write error comment on early failures.

- .circleci/config.yml
- Dockerfile
- testing/Dockerfile
Hi!
This upgrades the used version of Terraform to 0.11.11.
It would be awesome to get a release very soon! 😄
Thanks!
> Bump Terraform version to 0.11.11

- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/bitbucketserver/models.go
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- server/events/vcs/gitlab_client.go
If a file is moved during a pull request, we want to run plan in both the new and old directories (since they've both changed).
Notes:
* Fixes #413 
* Takes commit from @kent-b in #414 (thanks!)
> Include src of moved files in list of modified files

- runatlantis.io/guide/atlantis-yaml-use-cases.md
If users are overriding the default plan command then they need to
select the workspace themselves.
Fixes #405
> Document need to manually select workspace

- cmd/server.go
- cmd/server_test.go
`slack-token` was previously only supported via the yaml config file. Now it's supported via the `slack-token` flag and the `ATLANTIS_SLACK_TOKEN` environment variable.
Takes commit from @jacobfoard via #428.
Closes #428.
> Add slack-token to flags.

- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
Fixes #465 which is caused by XSRF detection on Bitbucket server and
cloud.
> Add header to disable bitbucket xsrf

- server/events/command_runner.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/bitbucketserver/client_test.go
- server/events/vcs/bitbucketserver/models.go
- server/events/vcs/bitbucketserver/testdata/pull-request.json
BB Server requires we send a 'version' parameter along with our call to
/merge.
Fixes #479
> Fix automerge bug in Bitbucket Server

- runatlantis.io/docs/atlantis-yaml-reference.md
- server/events/runtime/run_step_runner.go
- server/events/runtime/run_step_runner_test.go
Add `user_name` environment variable (username of VCS user running command) for custom workflow commands to use.
> Add user_name environment variable

- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/bitbucketserver/client_test.go
Previously we were stripping the basepath from the passed in URL. i.e.
if I passed in --bitbucket-base-url=https://me.com/basepath then we
would just strip off /basepath.
This change fixes that bug (#508).
> Support basepath for bitbucket server

- server/events/event_parser.go
- server/events/testdata/bitbucket-cloud-comment-event.json
- server/events/testdata/bitbucket-cloud-pull-event-fulfilled.json
- server/events/vcs/bitbucketcloud/models.go
Bitbucket is deprecating the username field.
See: https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr
> Use new 'nickname' field for bitbucket cloud

- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events/terraform/terraform_client.go
Allow running atlantis plan -d "dir with spaces" to target a directory
that contains spaces.
Fixes #423
>  Support dirs with spaces

- e2e/e2e.go
- server/events/command_runner.go
- server/events/command_runner_internal_test.go
- server/events/command_runner_test.go
- server/events/commit_status_updater.go
- server/events/commit_status_updater_test.go
- server/events/db/boltdb.go
- server/events/db/boltdb_test.go
- server/events/mocks/mock_commit_status_updater.go
- server/events/models/models.go
- server/events/models/models_test.go
- server/events/project_command_runner.go
- server/events_controller_e2e_test.go
Split single top-level status check into one plan and one apply check.
These checks will also now track the whole pull request status rather
than just the last action.
Fixes #446
> Split status checks

- server/events/working_dir.go
We recover gracefully from this so it's not an error.
> Log rev-parse error at warn level.

- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events_controller_e2e_test.go
- server/server.go
Fixes #533, a regression where Atlantis will respond with errors to
comments that aren't intended to invoke Atlantis.
> Stop Atlantis replying to non-atlantis comments.

- docker-base/Dockerfile
Mitigation for CVE-2018-19486 (https://nvd.nist.gov/vuln/detail/CVE-2018-19486)
Alpine 3.8 ships git version 2.18.1 which is vulnerable per above. This is one possible mitigation technique, though I do not know the impact of changing the FROM image in this project
> Use alpine:3.9 in base docker image

- e2e/e2e.go
- server/events/commit_status_updater.go
- server/events/commit_status_updater_test.go
- server/events/vcs/client.go
> Renamed status checks from <action>/atlantis to atlantis/<action>

- runatlantis.io/docs/apply-requirements.md
Describe that the Atlantis user may need write/push permissions to the base branch before it considers a PR mergeable.
When I was attempting to figure out why Atlantis wasn't considering a PR mergeable even when all status checks passed and approvals were given, I realized that it's possible that the Atlantis GH user itself may need write/push permissions to the base branch if the "Restrict who can push to this branch" option is checked under the base branch protection.
This PR just adds a heads up for other users that may have the same branch protection setup.
> Add mergeable GitHub requirement to docs

- README.md
- cmd/root.go
- runatlantis.io/.vuepress/config.js
- runatlantis.io/README.md
- server/events/comment_parser.go
Atlantis has been focused on TF pull request automation for the last
year so I want to rename its tagline to be more focused.
> Change Atlantis tagline.

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/server-side-repo-config.md
- server/events/yaml/parser_validator.go
- server/events/yaml/parser_validator_test.go
- server/events/yaml/raw/global_cfg.go
- server/events/yaml/raw/stage.go
- server/events/yaml/raw/step.go
- server/events/yaml/raw/workflow.go
- server/server.go
- server/user_config.go
This flag will allow users to specify repo config as json instead of
writing a file to disk. This is useful in deployments where disk access
is more difficult, ex. Docker.
> Add new --repo-config-json flag

- server/events/pending_plan_finder.go
- server/events/pending_plan_finder_test.go
- server/events/project_command_builder.go
- server/events/runtime/runtime.go
- server/events/runtime/runtime_test.go
- server/events/yaml/valid/repo_cfg.go
Previously, if you were using project names and you had two projects
with the same directory and workspace but different workflows, running
"atlantis apply" would fail. This was because we weren't figuring out
what the project name was for each pending plan.
This change fixes this by extracting the project name from the planfile.
We also handle /'s in the project name by substituting them with '::'.
This allows us to convert them back to /'s when we're figuring out the
project names from the filenames. It's safe to do this because : isn't
an allowed character for project names.
We also remove a final substitution of invalid filename characters
because we rely on the validation of the project names instead which
happens when validating the atlantis.yaml file.
Fixes #365
> Fix apply all with project name bug

- server/events/pending_plan_finder.go
- server/events/runtime/run_step_runner.go
- server/events/runtime/run_step_runner_test.go
- server/events/runtime/runtime.go
- Fixes #539
- Small refactor of @nikovirtala's work from #577
> Add PROJECT_NAME env var to custom run step

- server/events/runtime/run_step_runner.go
- server/events/runtime/run_step_runner_test.go
As requested in #539, this is an attempt to expose the project name as an environment variable.
> Expose project name as an environment variable

- server/logging/simple_logger.go
Includes the change in server/logging/simple_logger.go that will allow tests to pass but since its being vendored instead of being a relative path within the project, it won't take effect until after merging. Please let me know if there is a preferable way to doing this.
> Comment on why EROR and DBUG are not typos

- runatlantis.io/docs/locking.md
As per #269 , closing the PR without merging will unlock the project automatically. Including this as part of the documentation.
> Document project unlock due to PR close scenario

- cmd/server.go
I don't think any tokens accept newlines, so warn if the tokens have
one. Usually this is the result of a mistake when deploying Atlantis
which is hard to debug.
> Warn if tokens have newline

- server/events/working_dir.go
- server/events/working_dir_test.go
When using --checkout-strategy merge, we were performing the merge
without the --no-ff flag. This meant that if the branch could be merged
via a fast-forward merge (without a merge commit), then later when we
ran git rev-parse HEAD^2 to determine if the repo was at the right
commit, it would fail.
Now we merge with --no-ff which ensures the commit tree will always look
the same and git rev-parse HEAD^2 will always succeed.
Fixes #584
> Never use fast-forward merges

- runatlantis.io/docs/deployment.md
Short description of pointer to my separate GH repo with instructions/script for installing Atlantis on Azure Container Instances with self-signed cert, durable Azure backing store for Terraform, etc.
> added pointer for Azure ACI deploy

- server/events/event_parser_test.go
- server/events/models/models.go
- server/events/models/models_test.go
- server/events/working_dir.go
- server/events_controller_test.go
If there was an error during cloning, we would sometimes print the clone
credentials to the pull request and in the Atlantis logs. This change
ensures we print the redacted clone url.
We also change the redacted clone url to contain "username:<redacted>"
so that if users see the redacted url in logs, they'll know we were
using a credentialed form and so if they try to replicate with curl
they'll know to substitute the correct credentials.
Fixes #615
> Redact clone url during clone errors.

- server/events/runtime/run_step_runner.go
Since we're including the command output inside the error, we don't need
to also return the output. This was resulting in the error output being
printed twice.
Fixes #519
> Don't include errored cmd output twice.

- testdrive/testdrive.go
Previously we were using a library to colorize our strings during the
testdrive command. We used [white] which caused the output to not appear
on terminals that use white as the background. This change uses the
default terminal output color instead and only uses colorized strings
for warnings, errors and info via yellow, red and green respectively.
Hopefully those colours still show up on most terminals!
Fixes #575
> Fix testdrive output on solarized theme terminals.

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/command_runner.go
- server/events/command_runner_test.go
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/server.go
- server/user_config.go
Add a flag to disable the use of the command `atlantis apply` so you
can enforce that each plan must be applied separately.
Notes
* Took @wsoula's commits from #626, squashed, added finishing touches
>  Add --disable-apply-all flag

- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketcloud/models.go
- server/events/vcs/bitbucketcloud/testdata/pull-approved-by-author.json
- server/events/vcs/bitbucketcloud/testdata/pull-approved-multiple.json
- server/events/vcs/bitbucketcloud/testdata/pull-approved.json
- server/events/vcs/bitbucketcloud/testdata/pull-unapproved.json
Bitbucket Cloud changed their APIs to deprecate the username fields.
This broke how we were checking for approvals. Rather than propagate the
UUID field through the PullRequest model, I use the pull request API
response directly while checking approvers.
Fixes #652
> Fix require-approval for Bitbucket Cloud.

- server/events/project_command_runner.go
- server/events/webhooks/slack_client.go
- server/events/webhooks/slack_client_test.go
- server/events/webhooks/webhooks.go
Fixes: https://github.com/runatlantis/atlantis/issues/660
> Include directory in slack webhook message

- server/events/event_parser.go
- server/events/event_parser_test.go
- server/events/testdata/bitbucket-cloud-pull-event-created.json
- server/events/testdata/bitbucket-cloud-pull-event-fulfilled.json
- server/events/testdata/bitbucket-cloud-pull-event-rejected.json
Was using the word DECLINE but the actual keyword is DECLINED.
Fixes #676
> Fix bug parsing BB Cloud pull rejected events

- .circleci/config.yml
- Dockerfile
- testing/Dockerfile
we have some Engineers that are super aggressive in updating their things;
```Initializing the backend...
Error refreshing state: state snapshot was created by Terraform v0.12.2, which is newer than current v0.12.1; upgrade to Terraform v0.12.2 or greater to work with this state```
Thanks
> go to the latest version

- runatlantis.io/docs/custom-workflows.md
- server/events/runtime/run_step_runner.go
- server/events/runtime/run_step_runner_test.go
This should allow the extra args passed in the comment to be used by run steps
This should resolve #670 
@lkysow this seemed like an easy first issue to work on as you gave the info on how to implement in the issue 😄 - let me know if anything needs changing.
> Add CommentArgs to run step runner

- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
The error message we use to detect remote ops changed between 0.11.14
and 0.12.0. Recognize this new error message.
Fixes #704
> Detect remote ops for TF >= 0.12.0

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/terraform-cloud.md
- server/events/terraform/terraform_client.go
- server/events/terraform/terraform_client_internal_test.go
- server/events/terraform/terraform_client_test.go
- server/events_controller_e2e_test.go
- server/server.go
- server/user_config.go
--tfe-hostname will allow for creating a .terraformrc file with a
different hostname than app.terraform.io
Fixes #702
> Add flag for setting Terraform Enterprise hostname

- runatlantis.io/docs/repo-level-atlantis-yaml.md
Hey, thanks for the great project!
I noticed version 2 was still used in this part of the docs.
I assume this was overlooked when upgrading as the examples reflect the use of version 3.
> Update the yaml version so that it reflects latest

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/git_cred_writer.go
- server/events/git_cred_writer_test.go
- server/server.go
- server/user_config.go
Currently when Atlantis is running in a docker container it cannot access private repositories without people either pushing ssh private keys into the container with commands at launch or in some cases forking off their own copy where they embed the ssh key/secrets in the image. I'm sure there are a myriad of other ways people are doing it also. None of these are particularly nice options at least personally as then you're providing two sets of secrets instead of one.
GitHub, GitLab and Bitbucket all support push/pull via HTTPS you just need to provide the respective token. git will and does prompt you for the username and password required to authenticate over HTTPS however it is not cached to disk.
Terraform itself doesn't support any sort of environment variables either which would …
> Create .git-credentials to allow secure auth when cloning private repos

- docker-base/Dockerfile
Upgrade dumb-init and gosu versions the latest
> Upgrade dumb-init and gosu versions

- README.md
Pull the docker image information from microbadger.
> Add Docker image metadata

- runatlantis.io/.vuepress/config.js
- runatlantis.io/docs/README.md
- runatlantis.io/docs/troubleshooting-https.md
After our discussion on #750 , here is the troubleshooting section.
For info, in order to contribute to the doc, 
I just forked this repo, then `npm install && npm website:dev` and start editing files in `runatlantis.io/` .
It was quite a seamless experience. 👍 
Let me know your thoughts
> Add troubleshooting section for https

- runatlantis.io/docs/custom-workflows.md
- server/events/project_finder.go
- server/events/project_finder_test.go
Quick fix for https://github.com/runatlantis/atlantis/issues/728 until [this](https://github.com/runatlantis/atlantis/issues/728#issuecomment-521312535) is implemented.
Allows for using Atlantis with Terragrunt 0.19 style `terragrunt.hcl` config.
All tests passing.
> add .hcl to supported file filter

- runatlantis.io/docs/autoplanning.md
- runatlantis.io/docs/repo-level-atlantis-yaml.md
- runatlantis.io/docs/requirements.md
This clarifies that the `when_modified` block will be used by both
manual and automatic planning even though it's configured within the
auto planning block. This will help clarify issues like #774.
> Update repo level planning configuration docs

- server/events/working_dir_test.go
When cloning atlantis on a mac with git version 2.23.0 and running `make test-all`, I get the follwing test failure:
```
--- FAIL: TestClone_CheckoutMergeConflict (0.25s)
working_dir_test.go:227: exp err: "running git merge -q --no-ff -m atlantis-merge FETCH_HEAD: Auto-merging file\nCONFLICT (add/add): Merge conflict in file\nAutomatic merge failed; fix conflicts and then commit the result.\n: exit status 1" but got: "running git merge -q --no-ff -m atlantis-merge FETCH_HEAD: CONFLICT (add/add): Merge conflict in file\nAuto-merging file\nAutomatic merge failed; fix conflicts and then commit the result.\n: exit status 1"
```
Presented more cleanly, you can see that the 2 clauses between `FETCH_HEAD:` and `Automatic merge failed` are flipped
```
Expected:
running git merge -q --no-ff -m …
```
> Fix test that depends on exact output of git command

- server/events/repo_whitelist_checker.go
- server/events/repo_whitelist_checker_test.go
> Fix to allow whitelist globbing for strings after wildcard

- cmd/server.go
- runatlantis.io/docs/server-configuration.md
- server/events/git_cred_writer.go
- server/events/git_cred_writer_test.go
Pretty straightforward. Means that when `write-git-creds` is used it'll work for ssh and https sources without any changes needed. This was discussed in #711
> Configure git to use https instead of ssh.

- cmd/server.go
- cmd/server_test.go
- go.mod
- go.sum
- runatlantis.io/.vuepress/components/HomeCustom.vue
- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/apply-requirements.md
- runatlantis.io/docs/configuring-webhooks.md
- runatlantis.io/docs/deployment.md
- runatlantis.io/docs/installation-guide.md
- runatlantis.io/docs/requirements.md
- runatlantis.io/docs/security.md
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/webhook-secrets.md
- runatlantis.io/guide/testing-locally.md
- server/azuredevops_request_validator.go
- server/events/command_runner.go
- server/events/event_parser.go
- server/events/event_parser_test.go
- server/events/models/models.go
- server/events/models/models_test.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/azuredevops_client_test.go
- server/events_controller.go
- server/locks_controller.go
- server/server.go
- server/user_config.go
- server/web_templates.go
* flags
* `azuredevops-basic-password` => `azuredevops-webhook-password` (to keep consistent with other webhook flags)
* `azuredevops-basic-user` => `azuredevops-webhook-user`
* Capitalize `O` in `DevOps`
* remove regex validation of azuredevops repos since it was broken and also I didn't think it provided any value since if the repo wasn't in the right format it would fail later
* removed the `project` field from the lock view data since it wasn't being used
cc @mcdafydd
> Small refactoring to azure devops support

- CONTRIBUTING.md
- kustomize/bundle.yaml
- kustomize/kustomization.yaml
- runatlantis.io/docs/deployment.md
Towards #424.
Here I provide a base `bundle.yaml` that I took from the example in the documentation. Ideally, I'd prefer to generate this with a script upon release to update the container image. 
I've provided some base structural documentation of what envvars need to be patched from the kustomize manifest. 
I'd love to hear some feedback and how we can continue on this. Thanks!
> Initial Kustomize work

- runatlantis.io/docs/custom-workflows.md
This updates docs for COMMENT_ARGS to account for escaping from https://github.com/runatlantis/atlantis/pull/699. This will address https://github.com/runatlantis/atlantis/issues/832.
> Update COMMENT_ARGS Docs for Character Escaping

- runatlantis.io/docs/deployment.md
This should address https://github.com/runatlantis/atlantis/issues/824 by reverting back to the original docs for OpenShift but setting `HOME=/home/atlantis` instead of `ATLANTIS_DATA_DIR=/home/atlantis`.
May need further discussion to determine if this is all that is needed.
> revert openshift docs, change ATLANTIS_DATA_DIR to HOME

- .circleci/config.yml
- Dockerfile
- testing/Dockerfile
The GitLab autobump action is taking a bit too long.
> Bump terraform version to 0.12.16

- go.mod
- go.sum
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/azuredevops-accessors.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/azuredevops.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/events.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/git.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/pull_requests.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/teams.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/tests.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/users.go
- vendor/github.com/mcdafydd/go-azuredevops/azuredevops/work_items.go
- vendor/modules.txt
Updates go-azuredevops module version to handle time parsing error.
> Azure Devops: Fix timestamp parsing error in webhooks

- server/events/yaml/parser_validator_test.go
- server/events/yaml/raw/global_cfg.go
Previously, given the config:
```
workflows:
default:
...
```
We wouldn't actually use the redefined default workfow in our always
existing first repo config. This would mean that the redefined default
was never used unless users explicitly set workflow: default in the
repos array.
Fixes #860
> Fix bug when redefining default workflow

- server/events/project_finder.go
- server/events/project_finder_test.go
> I noticed that setting when_modified to something like ["*.tf", "!exclude-me.tf] with a modified list of exclude-me.tf still resulted in a plan automatically running. This PR allows files to be excluded using .dockerignore's exclusion syntax, i.e. prepending a ! to the path.
(from https://github.com/runatlantis/atlantis/pull/847)
Closes #847 (rebased those commits).
> Allow when_modified files to be excluded

- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events/mock_workingdir_test.go
- server/events/mocks/mock_working_dir.go
- server/events/models/models.go
- server/events/project_command_builder.go
- server/events/project_command_runner.go
- server/events/project_command_runner_test.go
- server/events/working_dir.go
- server/events/working_dir_test.go
Warn when using checkout-strategy=merge and the branch we're merging into has been updated after we've cloned it.
Takes commits from #815 and slightly refactors
Fixes #804
> Diverge warning

- server/server.go
The default BitbucketBaseURL value if not set by the user is
"https://api.bitbucket.org" which does not actually work with git.
Fixes #873
> Fix WriteGitCreds for BitBucket

- server/events/vcs/azuredevops_client.go
- server/events/vcs/azuredevops_client_test.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/gitlab_client.go
- server/events/yaml/raw/project.go
- server/events/yaml/raw/project_test.go
Previously, we wouldn't modify the config
```
project: /a/b/c
```
and would use the absolute directory.
Now we prepend `./` and then run `Clean()` to ensure that every project dir
is relative.
This PR also fixes AZDO to return relative paths from its GetModifiedFiles() function to match the rest of the VCS's.
Fixes #849
> Allow absolute project dirs and fix AZDO

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/terraform/terraform_client.go
- server/events/terraform/terraform_client_test.go
- server/events_controller_e2e_test.go
- server/server.go
- server/user_config.go
Add new `--tf-download-url` flag that configures where Terraform is downloaded from. Defaults to `https://releases.hashicorp.com`. This can be used in environments where calls to https://releases.hashicorp.com are firewalled.
Notes:
* Fixes https://github.com/runatlantis/atlantis/issues/614
* Carries @cullenmcdermott's work from https://github.com/runatlantis/atlantis/pull/787
* Closes https://github.com/runatlantis/atlantis/pull/787
> Add `--tf-download-url` flag

- cmd/server.go
- cmd/server_test.go
- go.sum
- runatlantis.io/docs/server-configuration.md
- server/events/command_runner_test.go
- server/events/commit_status_updater.go
- server/events/commit_status_updater_test.go
- server/events/matchers/models_pullrequest.go
- server/events/matchers/models_repo.go
- server/events/matchers/ptr_to_logging_simplelogger.go
- server/events/project_command_runner_test.go
- server/events/runtime/env_step_runner.go
- server/server.go
- server/user_config.go
Add a new flag `--vcs-status-name` for setting a custom status name that Atlantis will use for its PR statuses. Useful if you're running multiple Atlantis servers.
Notes
* Carries @js-timbirkett work from https://github.com/runatlantis/atlantis/pull/841
* Closes https://github.com/runatlantis/atlantis/pull/841
> Set custom PR status name

- server/events/webhooks/slack_client.go
- server/events/webhooks/slack_client_test.go
Set as_user to true for slack post message function so messages to a Slack channel use the bot's name and icon.
> Set Slack parameter AsUser to true

- runatlantis.io/docs/custom-workflows.md
default-tf-version
See https://github.com/runatlantis/atlantis/issues/910
> Expand on config for terragrunt custom workflow to accomodate downloaded

- docker-base/Dockerfile
- server/events/working_dir.go
Closes https://github.com/runatlantis/atlantis/issues/869
> Add Git LFS support

- cmd/server_test.go
- server/user_config.go
- Remove config/env/flag override tests since we know that the overrides
work
- We'll no longer need to edit the tests now when we add new flags
> Refactor cmd tests

- cmd/server.go
- cmd/server_test.go
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/server.go
- server/user_config.go
Refactors https://github.com/runatlantis/atlantis/pull/820
> Add flag for disabling markdown formatting

- cmd/server.go
- server/events/markdown_renderer.go
- server/server.go
- server/user_config.go
Heavy user of Atlantis and ran into a situation where users over-looked the changes of a plan because it had been wrapped. Thought adding a toggle for this behavior would be helpful for those who wanted to opt-out
> Adding flag to toggle wrapped default

- cmd/server.go
- cmd/server_test.go
Just a small quality of life change when parsing log levels. During our rollout of Atlantis, I had set the log level to `DEBUG` and saw it wasn't a valid option.
> Ignore casing on log levels

- cmd/server_test.go
- server/events/models/models_test.go
- server/server_test.go
Resolves #985. This assumes the test failures are harmless and can safely be updated to match the new error output. The tests now pass locally.
> Fix parse URL tests

- .gitignore
- Makefile
This is an alternative to #990 .
It seems like there are some OOM issues in `v1.24.0` of golanglint-ci. This still updates our golanglint-ci version, but only up a more stable version.
ref issue: https://github.com/golangci/golangci-lint/issues/994
> Update lint version

- runatlantis.io/docs/apply-requirements.md
- server/events/project_command_runner.go
- server/events/project_command_runner_test.go
Cherrypicks commit from https://github.com/runatlantis/atlantis/pull/988 and closes https://github.com/runatlantis/atlantis/pull/988.
Azure DevOps also allows users to approve their own requests, but there isn't much value in checking if this occurred before running an apply (similar to BitBucket).
The current Atlantis documentation seems to hint that the `approved` requirement means that someone _else_ has to approve the pull request, but the error message and documentation doesn't quite highlight this.
The apply requirement itself does call this out: https://www.runatlantis.io/docs/apply-requirements.html#supported-requirements.
This change updates the error message that is returned from Atlantis so that it's clear that more than just a single approval is needed. Also updates the …
> Update approved requirement documentation to be consistent

- runatlantis.io/.vuepress/config.js
👋 team,
I am working on DocSearch. [We have an integration for Vuepress](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search). We thought it is a shame you can not also used this search that you can [find on vuejs for example](https://vuejs.org/).
This PR will add DocSearch to the documentation website. It will allow a user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.
> feat: add DocSearch as recommended by vuepress

- server/events/event_parser.go
- server/events/event_parser_test.go
Related to #491. This change would classify any pull request event coming from draft PRs as an 'OtherPullEvent'. As a result Atlantis will ignore the PR until it is ready for review, at which point new events would be classified as before.
> Ignore Github draft PRs

- Dockerfile
At this point, I expect Hashicorp to have valid TLS certs at all times.
> disable insecure curl flags

- runatlantis.io/docs/terraform-cloud.md
Add instructions for Terraform Cloud token permissions. Without **Manage Workspaces** permission, users get this error:
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/my_org/terraform/79/dev/my_project": exit status 1
Initializing the backend...
Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.
Error: No existing workspaces.
Use the "terraform workspace" command to create and select a new workspace.
If the backend already contains existing workspaces, you may need to update
the backend configuration.
```
> Add instructions for Terraform Cloud token permissions

- server/events/event_parser.go
- server/events/event_parser_test.go
If plan is run manually in a draft PR, the PR may hold locks. If the draft PR is then closed, without first marking it Ready For Review, the locks are left in place. To resolve this, we can process closing draft PRs in the same way as non-draft PRs.
Also collapses draft event parsing test into normal event parsing. Previous test did not actually test different event types.
> Release locks when closing draft PRs

- cmd/server.go
- cmd/server_test.go
- server/events/event_parser.go
- server/events/event_parser_test.go
- server/server.go
- server/user_config.go
Refactors #1008 closes #1007 via `-enable-draft-prs` flag.
> Plan drafts

- go.mod
- go.sum
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- vendor/modules.txt
Using an empty auto-merge commit will cause GitHub to autogenerate its
own commit message like would happen when using the UI.
Closes #845, Deprecates #939
> Update go-github, empty automerge commit

- server/middleware.go
Fix for #1055.
Took the liberty of removing the exception for `/static/*` files as well, as the log level of DEBUG means only users actively configuring the log level will see those (and they might want to, if they're debugging).
> Changed default log level for web requests from INFO to DEBUG

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
fixes #948
Thanks to the ground work from #983, we can now configure GitLab's Merge Request links in the Lock Message correctly, using `!` instead of `#` which refers to issues, not MRs.
> GitLab's Merge Requests are using ! not #

- CHANGELOG.md
The CHANGLEOG says the new option in 0.13.0 fro draft PR autoplanning is  `--enable-draft-prs` but it is actually `--allow-draft-prs`
> Modify the CHANGELOG for correct draft PR autoplanning flag

- server/events/vcs/github_client.go
- server/events/vcs/github_client_internal_test.go
- server/events/vcs/github_client_test.go
- server/server.go
This PR adds debug level logging to indicate when Atlantis is making github API calls. This will be helpful when we approach GH rate limits and want some visibility into when + why calls are made.
> vcs/github_client: add logging around github API calls

- runatlantis.io/docs/custom-workflows.md
- server/events/runtime/run_step_runner.go
- server/events/runtime/run_step_runner_test.go
fixes https://github.com/runatlantis/atlantis/issues/806
> Export ctx.RepoRelDir to run step environment.

- server/events/vcs/github_client.go
- server/events/vcs/github_client_internal_test.go
- server/events/vcs/github_client_test.go
Partially addresses #1009, but doesn't fix it entirely. The 406 response
is still a puzzler.
> Fix GraphQL URL for Github Enterprise

- server/events/command_runner.go
- server/events/command_runner_test.go
- server/events/pull_closed_executor.go
- server/events/pull_closed_executor_test.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/mocks/mock_client.go
- server/events/vcs/not_configured_vcs_client.go
- server/events/vcs/proxy.go
- server/events_controller.go
- server/events_controller_e2e_test.go
- server/events_controller_test.go
- server/locks_controller.go
- server/locks_controller_test.go
Related to #1021
It looks like if the word "Plan" is added in the first line of comments made by atlantis hiding will work. Edited all vcs comments for consistency.
> Add "plan" to continued output statement

- runatlantis.io/docs/custom-workflows.md
- runatlantis.io/docs/repo-level-atlantis-yaml.md
This is a pretty shameless plug of my own library, so no worries at all if you don't feel comfortable adding this reference here.
`terragrunt-atlantis-config` is a tool that I have been using in production for a number of months now with a lot of success, and know of at least a few other companies who have benefited from using it as well.
> Add reference to terragrunt-atlantis-config in the Terragrunt docs

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
Bring back change from https://github.com/runatlantis/atlantis/commit/2f074727e295b2d82a8712bdc0c5a5750f3d939c#diff-e348084f0b7562996b0bd5d429158e53
that was clobbered.
> Bring back clobbered hide-prev-commentds fix

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
I made a mistake with my if statement logic for comment splitting.
> Reversed if statement for comment splitting

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
These calls have been 404'ing lately, likely due to eventual consistency
issues on GitHub's side where they send the PR created webhook but it's
not yet available on their API.
To work around this, we will retry up to 3 times with a 1s delay.
Fixes https://github.com/runatlantis/atlantis/issues/1019
> Retry get pull request calls to github

- server/events/runtime/apply_step_runner.go
Logging the start of an apply at the info level will be helpful in measuring the time it takes to apply.
Some of our applies are taking a long time when deleting AWS resources. We would like to be able to measure the time it takes to apply a PR with our logging platform so that our SRE team can know when to suggest a project be broken up into smaller projects.
> Log apply start at info level

- server/events/models/models.go
- server/events/models/models_test.go
Changes NewRepo() to encode any spaces in clone URLs.
> NewRepo() encodes spaces in clone URLs.

- runatlantis.io/docs/access-credentials.md
Mostly a revert of #1095, which while working, is too convoluted and can be sidestepped by using the documented --gh-org flag included in the original PR.
> Fix github app docs

- server/events/working_dir_locker.go
- server/events/working_dir_locker_test.go
Improves working dir lock error formatting by adding some punctuation and line breaks to the messages that are sent back to git.
> Improve working dir lock error formatting

- server/events/event_parser.go
- server/events/event_parser_test.go
Previously any update to a draft PR other than "closed" would default to
being an "open" event due to a bug in the parsing logic.
FIxes https://github.com/runatlantis/atlantis/issues/1194
> Fix bug responding to draft pr updates

- server/events/vcs/azuredevops_client.go
- server/events/vcs/azuredevops_client_test.go
- server/events/vcs/fixtures/azuredevops-policyevaluations.json
Fixes #1172
I was on the fence about removing the `Atlantis Bot` from the genre entirely to make the behavior in AzDO closer to the other VCS platforms but ultimately decided against it. Please let me know if you have any thoughts.
> Fix AzureDevops PR status updates

- runatlantis.io/docs/server-configuration.md
This PR fixes a typo made in the `server-configuration` page of the Atlantis docs.
The `Gitlab` section contained the `Github` flag, which is now replaced with the Gitlab `--gitlab-webhook-secret` flag.
> Hotfix: server-configuration Gitlab webhook secret command 

- runatlantis.io/docs/configuring-webhooks.md
When setting up Atlantis I noticed the GitLab Webhook instructions are slightly out of date, webhooks now have their own menu item under the projects settings rather than being under "Integrations" 
This PR updates the docs to reflect this
> GitLab have moved Webhooks into their own menu Item

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/command_runner.go
- server/events/command_runner_test.go
- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events/mocks/mock_comment_parsing.go
- server/events_controller.go
- server/events_controller_test.go
- server/server.go
- server/user_config.go
Implement a new server flag that will disable the ability to run `atlantis apply`, as suggested in #1219
> Add Option to globally disable apply

- server/server.go
Hi
I realised this weekend while working with the disable apply changes that the `atlantis help` output was not working I have tracked it down to me not passing the property to the CommentParser this PR fixes it
> Set ApplyDisabled on CommentParser to fix atlantis help output with --apply-disabled set

- server/events/git_cred_writer.go
- server/events/git_cred_writer_test.go
- server/events/working_dir.go
- server/events/working_dir_test.go
Fixes:  https://github.com/runatlantis/atlantis/issues/1236
Basically just ensures we are always using the latest credential URL in the case that we already have our repo cloned at the right commit and we want to check if master has diverged.  
Additionally, also ensures we can still write creds even when our creds are nuked.
> Ensure that refreshed creds are used to update remote.

- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
Resolves #1276 
As outlined in https://github.com/hashicorp/go-version/issues/59 go-version Constraints explicitly disallow matches with prerelease versions specified. Most of our other usage of Constraint tend to be for detection of older versions of terraform so there is probably no sense in a global update of these comparisons. In the future it is a good idea for us to opt for the explicit version comparison functions provided by the library.
> Fix >= 0.12.0 version detection for versions with prereleases

- scripts/binary-release.sh
Hashicorp has recently added arm64 builds with their recent 0.14
release:  https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability
> Terraform 0.14 also adds official support for Linux ARM64 builds.
> We’ve gone further and added Linux ARM64 support in the latest 0.13.x releases.
Similarly, recent versions of popular providers are also published with
arm64 builds.
This change updates the build script in order to produce an arm64
binary.
This would be useful, for example, for running in the cloud with one of
Amazon graviton2 instance types, or at a smaller scale on a Raspberry Pi
3 (or newer).
> Add arm64 (Linux) binary releases.

- runatlantis.io/docs/server-configuration.md
This PR update server configuration docs for `skip-clone-no-changes` flag
> docs: add 'skip-clone-no-changes' server configuration flag

- server/events/project_finder.go
- server/events/project_finder_test.go
I ran into an issue where I have a directory of templates I use that I name `foo.tf.template`. I found that Atlantis was running against this directory and failing, which was unexpected behaviour.
This is because we're just checking if `.tf` is contained within a filename, rather than checking if it's the suffix of the filename.
Instead, we can use regex to ensure that we're only filtering on actual Terraform files, inclusive of `.tf` and `.tfvars` suffixes.
There are obviously some alternative ways I could get around this: rename my templates to `foo.template` without the `.tf`.
I also really liked the idea of a `.atlantisignore` file previously cited[1], but it was rejected in favour of explicitly defining exactly
which directories to run it in. We have a large number of directories so …
> Use regex to filter filenames

- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/server-side-repo-config.md
- runatlantis.io/guide/testing-locally.md
- server/events/yaml/parser_validator_test.go
- server/events/yaml/raw/global_cfg.go
- server/events/yaml/valid/global_cfg.go
- server/events/yaml/valid/global_cfg_test.go
This implements a new option that can be defined server-config side.
The idea is to have a new key: `allowed_workflows.`
Currently, when `workflow` is an allowed override, the workflows that the repo side can choose any of the ser-side defined workflows..
This allows to specify server-side what workflows each repo is allowed to use.
This is particularly useful when certain workflows are associated with certain accounts or credentials set and limiting access to these is desired.
> Added support for restricting workflows usage repo-side

- server/events/db/boltdb.go
Small behavioral bug that has been around for a while. In the error message we are casting the index to a rune resulting in text characters rather than the numeric string.
> chore: correct cast from int to string in error message formatting

- server/events/project_finder.go
- server/events/project_finder_test.go
Fix for https://github.com/runatlantis/atlantis/issues/1330
https://www.terraform.io/docs/configuration/variables.html#variable-definitions-tfvars-files
```
Terraform also automatically loads a number of variable definitions files if they are present:
Files named exactly terraform.tfvars or terraform.tfvars.json.
Any files with names ending in .auto.tfvars or .auto.tfvars.json.
```
> add a valid variable definition file extension to list of exceptions

- runatlantis.io/docs/pre-workflow-hooks.md
The initial docs on pre workflow hooks - as well as their name - led me to the understanding that hooks run right before each workflow execution.
After implementing a pre workflow hook it is obvious that this is not the case. 
Digging in the source code reveals a slightly different logic on when pwh are being executed.
This PR adds an info box to the pre workflow hooks documentation page.
> Note added on when exactly pre workflow hooks run.

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/comment_parser.go
- server/events/locking/locking.go
- server/events/locking/locking_test.go
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events/mock_workingdir_test.go
- server/server.go
- server/user_config.go
This change introduces a no-op Locker implementation that when enabled effectively disables the locking of projects and workspace
This is another possible solution to #1212, my initial change just automatically unlock after a plan had run (#1258)
> Add the ability to disable Atlantis locking a repo

- server/events/command_runner.go
When a pull request has no Terraform changes at all, Atlantis passes the atlantis/plan check, but it doesn't pass the atlantis/apply check. This means that while it's possible to enable the atlantis/plan check as required in the branch protection settings, it's not possible to do the same for atlantis/apply (otherwise for PRs with no Terraform changes you have to run a no-op `atlantis apply`). The fix is simple: pass both checks in the case of no Terraform changes.
> Pass atlantis/apply when there are no plans

- .github/workflows/stale.yml
Right now this is only configured for PRs but can be used for issues as well.  This only cleans up PRs for which the customer is not responding to as of now.
> Add stale github action

- server/events/yaml/valid/global_cfg.go
- server/events/yaml/valid/global_cfg_test.go
This fixes a bug where it was required to set `allow_custom_workflows` in order to validate that the workflows were whitelisted.
If the repo is allowed custom workflows and selects one that is not whitelisted server-side we verify that the repo has defined it. 
Fixes [Issue 1358](https://github.com/runatlantis/atlantis/issues/1358)
> Fixed bug in allowed_workflows logic

- docker-base/Dockerfile
Fixes curl vulnerability [CVE-2020-8177](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8177).
> deps: bump alpine to v3.13

- runatlantis.io/docs/server-side-repo-config.md
- server/events/pre_workflow_hooks_command_runner.go
- server/events/yaml/parser_validator_test.go
- server/events/yaml/raw/global_cfg.go
- server/events/yaml/valid/global_cfg.go
- server/events/yaml/valid/global_cfg_test.go
* Add a branch regex to the repo.yaml config to allow Atlantis to accept only pull requests with a given base branch (the branch
a PR would merge _into_).
* `branch` is optional. By default its unset and Atlantis will match webhooks for pull requests for any branch (no change)
Match any PR,
```
repos:
- id: /.*/
branch: /.*/
```
Match only PRs with master or main base branch.
```
repos:
- id: /.*/
branch: /(main|master)/
```
Some repos have unique pull request branching practices. For example, plan/apply from feature branches merging into master, but separate flows for merging master into a release branch (where Atlantis isn't used). Adding a regex allows for flexible workflow options. For example, you could have Atlantis ignore "release" branches.
> Add a branch matcher to the server side repo config

- server/events/runtime/apply_step_runner.go
- server/events/runtime/plan_step_runner.go
- server/events/runtime/plan_step_runner_test.go
Fixes #1306
Since Terraform 0.14.0 there are no separator between refreshing plan and the plan. This strategy is to find the last line with "Refreshing state..." and remove it with all of the above.
I remove the sentence "Refreshing Terraform state in-memory prior to plan..." from tests because Terraform don't show that anymore.
> fix(output): Remove Refreshing state... from output

- CONTRIBUTING.md
After my last PR, I found my error for UTs, I run only `make test` and not `make test-all`. That could prevent some errors.
> Suggest to run integration tests in Docker

- runatlantis.io/docs/server-configuration.md
This was added in #1053 but is not documented.
> Add Missing allow-draft-pr Server Flag Docs

- runatlantis.io/docs/pre-workflow-hooks.md
After #1418 was merged pre-workflow-hooks are executed before every command. Removed the note and added some more explanation to the docs
> Updating the pre workflow hooks docs

- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events/models/models.go
- server/events/models/models_test.go
- server/testfixtures/test-repos/automerge/exp-output-autoplan.txt
- server/testfixtures/test-repos/modules-yaml/exp-output-autoplan.txt
- server/testfixtures/test-repos/modules/exp-output-autoplan-only-staging.txt
- server/testfixtures/test-repos/modules/exp-output-plan-production.txt
- server/testfixtures/test-repos/modules/exp-output-plan-staging.txt
- server/testfixtures/test-repos/policy-checks-apply-reqs/exp-output-autoplan.txt
- server/testfixtures/test-repos/policy-checks-diff-owner/exp-output-autoplan.txt
- server/testfixtures/test-repos/policy-checks-multi-projects/exp-output-autoplan.txt
- server/testfixtures/test-repos/policy-checks/exp-output-autoplan.txt
- server/testfixtures/test-repos/server-side-cfg/exp-output-autoplan.txt
- server/testfixtures/test-repos/simple-yaml/exp-output-autoplan.txt
- server/testfixtures/test-repos/simple/exp-output-atlantis-plan-new-workspace.txt
- server/testfixtures/test-repos/simple/exp-output-atlantis-plan-var-overridden.txt
- server/testfixtures/test-repos/simple/exp-output-atlantis-plan.txt
- server/testfixtures/test-repos/simple/exp-output-autoplan.txt
- server/testfixtures/test-repos/tfvars-yaml-no-autoplan/exp-output-plan-default.txt
- server/testfixtures/test-repos/tfvars-yaml-no-autoplan/exp-output-plan-staging.txt
- server/testfixtures/test-repos/tfvars-yaml/exp-output-autoplan.txt
If there are multiple projects planned and markdown folding is enabled user must click on each "Show details" button separately and scroll through the plan to check if there are any changes to the infrastructure. This may be pretty time consuming when multiple projects are planned. Some of them may not have any changes in them, due to the dependency resolution. 
This PR adds the extra summary line, so user can quickly eyeball what is the impact of his change for each project without unfolding the output.
> Add plan summary to unfolded part of comment

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/project_command_builder.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/project_finder.go
- server/events/project_finder_test.go
- server/events_controller_e2e_test.go
- server/server.go
- server/user_config.go
This adds a new server flag that allows modifying the list of files that trigger default project planning.
We use terraform/atlantis to build AWS AMI's using packer and ansible. We wanted changes to the packer (`*.pkr.hcl`) and ansible (`*.yml`) files to trigger an autoplan when modified in a commit. It looked like we could do this with an `atlantis.yml` file (Workflow), but we have a large repo with 100's of small projects and rely on the default atlantis workflow. Defining `atlantis.yml` would require us to define every existing project, and all new projects in that workflow.
Instead, I added a server flag/ENV that would allow modifying/overriding the list of file patterns that trigger an autoplan.
`--autoplan-file-list` uses the same dockeringore syntax as Custom workflows autoplan …
> feat: Add `--autoplan-file-list` server flag.

- .circleci/config.yml
CircleCI contexts (https://circleci.com/docs/2.0/contexts/) can be used
to scope environment variables to specific jobs rather than all jobs in
a repo.
This change adds contexts for docker publish and e2e tests which are the
only jobs that need secrets.
> Use circle ci contexts to scope secret access

- .circleci/config.yml
- These require the CircleCI context which fork PRs don't have access to.
- Also skip tests on PRs with branchname "docs/blah"
> Don't run e2e tests for fork PRs

- server/events/markdown_renderer.go
- server/events/models/models.go
- server/events/pull_updater.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/mocks/mock_client.go
- server/events/vcs/not_configured_vcs_client.go
- server/events/vcs/proxy.go
This should fix the problem being seen here:
https://github.com/runatlantis/atlantis/issues/1506
> [ORCA-559] Fix hide previous command logic (#37)

- server/events/vcs/azuredevops_client.go
- server/events/vcs/azuredevops_client_test.go
1. Get all commits of PR
2. Get changed files all PR commits
Fixes #1397
> Get modified Azure DevOps PR files from commit and changes API endpoint

- server/events/project_command_builder.go
This PR is fixing the issue https://github.com/runatlantis/atlantis/issues/1555
The DeleteSourceBranchOnMerge attribute was set before calling MergeProjectCfg.
> DeleteSourceBranchOnMerge issue fixed

- server/events/vcs/azuredevops_client.go
- server/events/vcs/azuredevops_client_test.go
My first attempt of fixing #1397 lead to issues, where later commits in an Azure DevOps PR revert changes to some modules introduced in earlier commits.
This PR reverts #1521 and gets modified files from the diff of the PRs source branch to the target branch instead of just the latest commit.
> fix: Azure DevOps get modified files from PR via source -> target diff

- runatlantis.io/docs/apply-requirements.md
- server/events/mock_workingdir_test.go
- server/events/mocks/mock_working_dir.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/project_command_runner.go
- server/events/project_command_runner_test.go
- server/events/working_dir.go
- server/events/working_dir_test.go
- server/events/yaml/parser_validator_test.go
- server/events/yaml/raw/project.go
- server/events/yaml/raw/project_test.go
- server/events/yaml/valid/global_cfg.go
- server/events/yaml/valid/global_cfg_test.go
- server/server.go
- server/user_config.go
This PR adds an `undiverged` Apply requirement which prevents applies if there are any changes on the base branch since the most recent plan. The apply requirement only effects repos/projects with the 'merge' checkout strategy and prevents the situation where an 'apply' is run on Atlantis but not all changes from remote/master had been pulled locally to Atlantis. This is the same situation where we already warn users on the 'plan' but additionally prevents the apply.
Example workflow:
> Add undiverged apply requirement

- server/logging/simple_logger.go
Atlantis version - atlantis 0.17.0
Issue - 
With the current format of logs, the timestamp is printed in the format -
**{"level":"info","ts":1623266081.273087,"caller":"server/server.go:715","msg":"All in-progress operations complete, shutting down","json":{}}**
This particular format makes it really difficult or impossible to ingest atlantis logs into logging system like ELK. Also to the bare eye it is difficult to understand the format.
Solution offered -
Zap logs can be formatted to be printed in ISO8601 standards. This has been configured in the logger initialisation. With this configs logs are printed in the below format -
**{"level":"info","ts":"2021-06-10T00:44:51.559+0530","caller":"server/server.go:148","msg":"Policy Checks are enabled","json":{}}**
This format is more readable …
> Standardised logging timestamp to ISO8601

- runatlantis.io/docs/custom-workflows.md
- server/events/runtime/run_step_runner.go
- server/events/runtime/run_step_runner_test.go
Policy checks require the PLANFILE in json format. The default show workflow step defaults to `terraform show`. This breaks custom workflows, e.g. a terragrunt workflow.
This PR adds a SHOWFILE environment variable which is set to the expected absolute path of the json formatted PLANFILE. This allows for the following custom show command:
```yaml
- run: terragrunt show -no-color -json $PLANFILE > $SHOWFILE
```
fixes #1562
> Add run step environment variable SHOWFILE

- server/events/apply_command_runner.go
- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events/event_parser.go
- server/events/event_parser_test.go
- server/events/mocks/mock_comment_building.go
- server/events/project_command_context_builder.go
- server/events/project_command_context_builder_test.go
- server/events/yaml/valid/global_cfg.go
```
atlantis apply --auto-merge-disabled
```
Issue: #1245
> Add an extra flag to disable automerge with comment apply

- server/events/vcs/azuredevops_client.go
Azure DevOps comment character limit is 150.000
This limit is undocumented. However, posting a large comment via the rest api leads to a bad request with following message:
"message": "A discussion comment cannot be longer than 150000 characters.\r\nParameter name: comment.Content"
> Set Azure DevOps max comment characters to api limit

- .github/dependabot.yml
Along with migrating the pipeline into github actions, it is also good to introduce github-action dependabot management as well.
> dependabot: track github-action deps

- server/events/runtime/init_step_runner.go
- server/events/runtime/init_step_runner_test.go
Seems I messed up with git and the previous PR got closed #1644 and I dont have the option to re-open So this PR replaces it
It will only omit the `-upgrade`  flag if TF version > 0,14 and the `.terraform.lock.hcl` exists 
I also attempt to de-duplicate the args (but there must be a more efficient way of doing this than what I have)
> Dont add -upgrade of the lock file exists & dedupe extra args

- server/events/runtime/common/common.go
- server/events/runtime/common/common_test.go
- server/events/runtime/init_step_runner.go
This PR moves the argument de-duplication logic out into to a utility package so  it can be re-used as requested 
I have also tried to cater for matching  "--argname" vs "-argname" in both argument lists
> Move argument deduplication logic to a utility package

- server/events/project_command_builder.go
Fixes https://github.com/runatlantis/atlantis/issues/1612
When `pre_workflow_hooks` is being used to generate `atlantis.yaml` and projects are set with specific workspaces different than `default`, a different directory is created for each project-workspace pair, but all those that are not on the `default` workspace will not have an `atlantis.yaml` file at their root.
As described in some details in https://github.com/runatlantis/atlantis/issues/1612#issuecomment-856121614 this can lead to situations where atlantis tries to build commands without finding the `atlantis.yaml` even though it has correctly being generated in the `default` workspace.
The most obvious error is
```
building command for dir "<path to project>": cannot specify a project name unless an atlantis.yaml file exists to …
```
> Always use the default workspace directory when building commands context

- server/core/runtime/plan_step_runner.go
Atlantis fails during the plan step when using TFE remote ops and Terraform version 1.0.0. (Same issue with 1.0.1). This is due to a slight change in the error message that gets printed when trying to run plan with the -out param on a TFE workspace set up for remote operations. This change fixes that by adding the Terraform 1.0.{0,1} specific error message to the remote ops detection logic.
> fix: TFE remote ops detection for >= tf 1.0.0

- server/controllers/events/events_controller_e2e_test.go
- server/core/runtime/version_step_runner.go
- server/core/runtime/version_step_runner_test.go
- server/events/command_runner_test.go
- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events/markdown_renderer.go
- server/events/mocks/mock_comment_building.go
- server/events/mocks/mock_project_command_builder.go
- server/events/mocks/mock_project_command_runner.go
- server/events/models/models.go
- server/events/project_command_builder.go
- server/events/project_command_builder_test.go
- server/events/project_command_context_builder.go
- server/events/project_command_runner.go
- server/events/version_command_runner.go
- server/server.go
Adds version command for #1552. It doesn't currently include the version of atlantis, and I wasn't sure the best way of passing down the version from `main.go`
I'm happy to make any changes, thanks!
> feat: add version command

- runatlantis.io/docs/configuring-webhooks.md
Some links were broken because they had `.html` instead of `.md`
> fix: urls on webhooks documentation

- server/events/project_command_pool_executor.go
It seems to me that `--parallel-pool-size` flag (https://github.com/runatlantis/atlantis/blob/master/runatlantis.io/docs/server-configuration.md#--parallel-pool-size) is ignored because default value (which is 15) is hardcoded.
> fix ignore of --parallel-pool-size flag

- server/events/vcs/gitlab_client.go
Why:
This PR solves the following issue:
MR can be applied when MR is in a draft status (Work In Progress)
> fix: fixing apply permission when MR is in a draft status

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/server-configuration.md
- server/events/github_app_working_dir_test.go
- server/events/vcs/github_credentials.go
- server/events/vcs/github_credentials_test.go
- server/server.go
- server/user_config.go
> allow user to pass gh-app-key directly instead of filename

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
- server/events/models/models.go
- server/events/project_command_builder.go
- server/server.go
- server/user_config.go
Heavily inspired from #1325 and looking at https://github.com/runatlantis/atlantis/issues/1395. Thanks @raxod502-plaid for the base for the regex.
I added the ability to optionally enable Atlantis to do some Github markdown diff formatting, to enable color coded comments. Also added some tests using the original PR as reference for correctness. This has been pretty useful for me, and hopefully will be useful for the users asking for a bit more Github friendliness :) 
This flag will turn comments into something like this:
<details><summary> New Atlantis Comment </summary>
Ran Plan for dir: `path/to/terraform` workspace: `default`
<details><summary>Show Output</summary>
```diff
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform …
```
> Add a flag to optionally enable Github Markdown Formatting for diffs

- server/events/vcs/gitlab_client.go
close https://github.com/runatlantis/atlantis/issues/798
If a comment is too long, a gitlab server returns a following error.
```
2019/10/03 03:07:12+0000 [EROR] command_runner.go:390 REPO_PATH_OBSCURED#247: Unable to comment: POST URL_OBSCURED: 400 {message: 400 (Bad request) "Note {:note=>["is too long (maximum is 1000000 characters)"]}" not given}
```
Migrate implementation from other vcs server to split comment.
https://github.com/runatlantis/atlantis/blob/da981cbb46033dde037e285d8bac2a1deff95cc0/server/events/vcs/azuredevops_client.go#L99-L109
> Split Gitlab Server comments if over max length

- runatlantis.io/guide/testing-locally.md
The instructions incorrectly asked to visit "Settings->Integrations" , whereas the correct instruction is to visit "Settings->Webhooks".
This PR fixes the error.
> Fixed instructions for adding Webhook under Gitlab

- server/controllers/events/events_controller_e2e_test.go
- server/events/command_runner.go
- server/events/command_runner_test.go
- server/events/pre_workflow_hooks_command_runner.go
- server/events/yaml/valid/global_cfg.go
- server/events/yaml/valid/global_cfg_test.go
- server/server.go
Fixes #1539
The branch matcher feature has been introduced in #1383, but the current implementation was broken and doesn't work at all (#1539). If my understanding is correct, there are two problems:
(1) The `GlobalCfg` has a default `Repo` instance which always matches any repositries and branches. Therefore the branch matcher never be functional.
(2) Validating base branches in `DefaultPreWorkflowHooksCommandRunner.RunPreHooks()` implicitly assumed that users customize `pre_workflow_hooks`, but the assumption isn't always true because it defaults to empty.
For (1), I added a new method `MatchingRepo()` to `GlobalCfg` to check `BranchMatches()` for a single `Repo` instance.
For (2), I moved validating branch to `DefaultCommandRunner.validateCtxAndComment()`. Since the method has already …
> Validate base branches in DefaultCommandRunner

- docker-base/Dockerfile
Fixes apk-tools vulnerability CVE-2021-36159 and fix curl vulnerabilities CVE-2021-22924, CVE-2021-22923 and CVE-2021-22925
> deps: bump alpine to v3.14

- runatlantis.io/docs/server-configuration.md
`The Silence VCS Status` feature has been implemented in #954. However there is no reference to it in the server side repo config.
Add missing `The Silence VCS Status` `--silence-vcs-status-no-plans` in the reference for server side repo config.
> docs: Add missing --silence-vcs-status-no-plans flag

- .github/workflows/lint.yml
- .golangci.yml
- server/core/locking/locking_test.go
- server/core/runtime/policy/conftest_client.go
- server/events/pre_workflow_hooks_command_runner_test.go
- server/events/yaml/valid/global_cfg.go
- testdrive/utils.go
The golint was officially deprecated.
https://github.com/golang/go/issues/38968
We have been using golint via golangci-lint and golangci-lint now recommends using revive instead of golint.
https://golangci-lint.run/usage/linters/
> golint: The repository of the linter has been archived by the owner.
> Replaced by revive.
The revive is a drop-in replacement of golint. I think switching to revive is a reasonable choice to check the same rules for free.
https://github.com/mgechev/revive
> build(lint): use revive instead of golint

- runatlantis.io/docs/apply-requirements.md
- runatlantis.io/docs/server-side-repo-config.md
Fixes #1695
The branch matcher feature has been implemented in #1383 and #1768. There is only an example for it, but not in the reference.
https://github.com/runatlantis/atlantis/pull/1383/files#diff-5dd8dd3b7c37191b78109efaaa1bb73184ff7a1690632d687fed7cd748847f5eR31-R34
Add missing the `branch` key in the reference for server side repo config.
I also add a warning for `mergeable` requirement to check the `branch` setting because I think a typical branch protection rule only restricts a default branch. We should let users know that someone can potentially bypass it without the `branch` restriction in atlantis.
> docs: add missing the `branch` key in the reference for server side repo config

- README.md
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/bitbucketserver/client_test.go
This PR adds the support for the delete_source_branch_on_merge attribute of a atlantis.yaml file for the BitBucket Server.
> Add support for deleting a branch on merge in BitBucket Server

- runatlantis.io/docs/automerging.md
- runatlantis.io/docs/using-atlantis.md
This flag was added in #1533 but was not documented.
> Document --auto-merge-disabled option

- server/events/vcs/github_client.go
Retry with fixed 1 second backoff up to 3 retries was added by #1131 to address #1019, but the issue continued to show up (#1453).
Increase max attempts to 5 and use exponential backoff for a maximum total retry time of (2^n - n - 1) seconds, which is roughly 30 seconds for current max attempts n = 5.
Also move the sleep to the top of the loop so that we never sleep without sending the request again on the last iteration.
I decided not to change the test case added in #1131 to avoid sleeping the full time in the test suite - I can bump the retries there to 5 to keep it in sync if that would be better.
I can also add jitter so the backoff isn't deterministic / less vulnerable to thundering herds but didn't for now since there's already existing retry logic in this exact place that is …
> Improve github pull request call retries

- runatlantis.io/docs/terraform-versions.md
When latest Docker image still had terraform 1.0.0, for example, any method of specifying a higher version failed to build.  This note clarifies the dependency.
> docs: clarify maximum version limit

- runatlantis.io/docs/terraform-versions.md
relates to #1894
---
```
$ curl -I https://github.com/runatlantis/atlantis/pkgs/container/atlantis/9854680?tag=latest
HTTP/2 404
server: GitHub.com
date: Fri, 12 Nov 2021 20:03:39 GMT
```
Which caused the master build failure
> docs: revert to use docker hub page as 404 on github pkg registry

- server/middleware.go
Basic Auth support was added in https://github.com/runatlantis/atlantis/pull/1777, however this disabled the ability to use AWS ELB health checks against the `/healthz` endpoint. This purpose of this change is to allow the `/healthz` endpoint to work for systems that check automatically and do not support authentication or it is desired to configure without authentication, including AWS ELB health checks and Kubernetes probes.
This PR changes the behavior of the middleware when it checks if Basic Auth is enabled to allow unauthenticated requests to `/healthz` in the same way that requests to `/events` were excepted from the check.
> fix: allow requests to /healthz without authentication

- runatlantis.io/docs/terraform-versions.md
Reverts runatlantis/atlantis#1897
---
Github has fixed the access issue, revert the code change to use the github package registry url.
```
$ curl -I https://github.com/runatlantis/atlantis/pkgs/container/atlantis/9854680?tag=latest
HTTP/2 200
server: GitHub.com
date: Wed, 17 Nov 2021 14:27:16 GMT
```
> Revert "docs: revert to use docker hub page as 404 on github pkg registry"

- server/controllers/events/testfixtures/test-repos/policy-checks-apply-reqs/exp-output-auto-policy-check.txt
- server/controllers/events/testfixtures/test-repos/policy-checks-diff-owner/exp-output-auto-policy-check.txt
- server/controllers/events/testfixtures/test-repos/policy-checks-extra-args/exp-output-auto-policy-check.txt
- server/controllers/events/testfixtures/test-repos/policy-checks-multi-projects/exp-output-auto-policy-check.txt
- server/controllers/events/testfixtures/test-repos/policy-checks/exp-output-auto-policy-check.txt
- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/events/markdown_renderer.go
- server/events/markdown_renderer_test.go
The `approve_policies` command was added with policy checking but was
never included in the command parser help.
Add an explicit mention of the `approve_policies` command in the error
message on policy checking failure.
Also update the comments in the file to reflect all of the commands.
> docs: document approve_policies command in comment_parser

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- server/events/yaml/raw/repo_cfg.go
- server/events/yaml/raw/repo_cfg_test.go
- server/events/yaml/valid/repo_cfg.go
- server/events/yaml/valid/repo_cfg_test.go
Implements what is suggested in https://github.com/runatlantis/atlantis/issues/1718. 
As explained there, this is useful to be able to execute for example `atlantis apply -p dev/.*` and `atlantis apply -p staging/.*` but not any other regex matches, for safety and security reasons.
> feat: adds `allowed_regexp_prefixes` parameter to use with the `--enable-regexp-cmd` flag

- runatlantis.io/docs/deployment.md
- runatlantis.io/docs/policy-checking.md
> docs: add clarity and further policy_check examples

- CHANGELOG.md
- kustomize/bundle.yaml
- main.go
plan to do the release this week (after the multiplatform image build setup)
> release: 0.17.6

- cmd/server.go
- runatlantis.io/docs/server-configuration.md
- server/controllers/events/events_controller.go
- server/events/command_runner.go
- server/events/team_allowlist_checker.go
- server/events/team_allowlist_checker_test.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/mocks/mock_client.go
- server/events/vcs/not_configured_vcs_client.go
- server/events/vcs/proxy.go
- server/server.go
- server/user_config.go
Configure permissions by GitHub team, with a list of teams and commands they are permitted to use.
```sh
atlantis server --gh-team-allowlist "myteam:plan, secteam:apply"
```
This change is intended to replace #1206.
The code is the same, so all credit/blame goes to @jamengual & co-authors—I have only squashed those 75 revisions down to one, rebased on master, and resolved a few minor conflicts & incompatibilities.
> feat: add GitHub team allowlist configuration option

- server/core/runtime/apply_step_runner.go
- server/server.go
The plan step has a mechanism to use the default tf version from the Terraform client if the context does not define one, however the apply step does not have this. This results in remote executions of apply failing with a nil pointer dereference when it checks tfVersion in StripRefreshingFromPlanOutput. This fix involves copying what the PlanStepRunner does and falls back to the default version if the context's version is nil.
Fixes #1804 and #1852
> fix: fallback to default TF version in apply step

- runatlantis.io/guide/testing-locally.md
The DevOps section doesn't show up in the Table of Content. This PR sets the number of `#`s to be the same as the previous section.
> docs: typo in heading level

- runatlantis.io/docs/configuring-webhooks.md
- runatlantis.io/docs/server-configuration.md
Fix github docs link check failures in #1961
> 2021/12/27 12:14:05 Connected to tcp://localhost:8080
> http://localhost:8080/docs/deployment.html
> 	timeout	https://github.com/runatlantis/helm-charts/tree/main/charts/atlantis
> http://localhost:8080/docs/configuring-webhooks.html
> 	timeout (following redirect https://docs.github.com/articles/differences-between-user-and-organization-accounts)	https://help.github.com/articles/differences-between-user-and-organization-accounts/
> http://localhost:8080/docs/server-configuration.html
> 	timeout	https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/securing-your-webhooks
> 	timeout (following redirect https://docs.github.com/v3/apps/installations)	https://developer.github.com/v3/apps/installations/
job ref, …
> docs: update github docs links

- cmd/server.go
There shouldn't be any GitHub team allowlist rules by default, since the feature and team API integration doesn't make sense for everybody.  [With no rules to enforce, no API call is made](https://github.com/runatlantis/atlantis/blob/bc368465a00353e79aa3947eed11965a95e1fba8/server/events/command_runner.go#L177-L181), so this should resolve https://github.com/runatlantis/atlantis/issues/1967
More generally, the way of defaulting flags when the value is "" seems dubious, and should instead depend on the presence of the flag itself.  However, that behavior isn't specific to this flag and is made moot with this change.
> Include no GitHub allowlist rules by default

- cmd/server.go
- runatlantis.io/docs/troubleshooting-https.md
- server/events/command_runner.go
- server/events/command_runner_test.go
- server/events/team_allowlist_checker.go
- server/events/team_allowlist_checker_test.go
Removes dead code and adds some testing.
> fix: default permissions for gh-team-allowlist.

- runatlantis.io/.vuepress/config.js
- runatlantis.io/docs/using-slack-hooks.md
The Atlantis docs only mentioned how to configure the Slack token, but not how to actually use it.
This is what I have cobbled together based on what I was able to find in the issues of this repository.
> docs: documentation for slack integration

- .github/workflows/atlantis-image.yml
https://github.com/runatlantis/atlantis/pull/1943 changed the way Docker images
were built in GitHub Actions so multi-architecture Docker images now are built,
but it unfortunately included a bug which means it hasn't worked yet on any
released version of Atlantis.
The problem is the change expected environment variables to be replaced in the
regular YAML code instead of just the commands which are run.
This attempts to fix that by instead using the template language available to
access the same environment variable.
This is based on the example provided in the documentation here:
https://docs.github.com/en/actions/learn-github-actions/environment-variables.
> workflows(atlantis-image): fix building and publishing of Docker images

- server/events/yaml/valid/repo_cfg.go
- server/events/yaml/valid/repo_cfg_test.go
As you can see on the test case I added on this pull request, if the user comments for example `atlantis apply -p prod/myproject` it would fail if he didn't add `prod` on the `allowed_regexp_prefixes` config (added on https://github.com/runatlantis/atlantis/pull/1884/files). 😞 
This PR fixes that to only check the `allowed_regexp_prefixes` only if there's more than one match for the regex inserted on the PR comment. If it's an exact match, it should ignore the `allowed_regexp_prefixes`.
> fix: allowed regexp prefixes for exact matches

- cmd/server.go
- runatlantis.io/docs/server-configuration.md
- server/controllers/events/events_controller_e2e_test.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/project_finder_test.go
This pull request should fix #1970 by adding `.terraform.lock.hcl` to  DefaultAutoplanFileList
I have modified  existing unit and e2e tests to cover this case
> Fix autoplan when .terraform.lock.hcl is modifed

- runatlantis.io/docs/policy-checking.md
Invalid YAML, add missing colon.
> docs: add colon to policy checking yaml

- runatlantis.io/docs/post-workflow-hooks.md
Added link to infracost Docs. I am using Atlantis with infracost latest version . It might be good to link to the Docs.
so its clear.
> docs: include infracost ref in post-workflow-hooks

- server/events/yaml/valid/policies.go
Making policy owner check be case insensitive, since Github, Bitbucket, Gitlab and Azure Devops have case insensitive usernames:
- https://gitlab.com/edbighead -> https://gitlab.com/EdBighead
- https://bitbucket.org/edbighead/ -> https://bitbucket.org/EDbighead/
- https://github.com/edbighead -> https://github.com/edBIGHEAD
- https://dev.azure.com/edbighead/test -> https://dev.azure.com/edBIGheAD/test
> fix: make IsOwner policy check case-insensitive

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- runatlantis.io/docs/server-configuration.md
I've faced two problems during my Atlantis setup, and I'd like to suggest some changes to make the documentation more user-friendly.
> docs: fix incorrect wildcard and more precise instruction to --gh-team-allowlist option.

- server/middleware.go
- server/server.go
When log-streaming #1937 was upstreamed, the improved auth-support #1777 was removed. This change brings back the basic auth support.
> fix: add back basic auth support

- server/server.go
- server/server_test.go
:wave: team. First and foremost: thank you for open sourcing and maintaining this project, it's been really useful. Today while working on an unrelated issue I started to investigate the `/healthz` endpoint in Atlantis and found that it could be improved in both speed and memory allocations.
The first thing I did was adding a benchmark to have a baseline for comparing my changes:
```
goos: darwin
goarch: amd64
pkg: github.com/runatlantis/atlantis/server
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkHealthz-12       100000               531.0 ns/op           112 B/op          4 allocs/op
PASS
ok      github.com/runatlantis/atlantis/server  0.370s
```
Then I implemented my improvements. I noticed that the response body is always the following:
```json
{
"status": "ok"
}
``` …
> chore: improve `/healthz` endpoint performance

- server/router.go
- server/router_test.go
https://github.com/runatlantis/atlantis/issues/1979
> Fix 1979: Update GenerateProjectJobURL to account for nested repo names

- server/events/models/models.go
- server/router_test.go
We'll eventually be moving to a UUID based log-streaming job identifier, removing any dependencies on the project name or the directory. So, replacing the "." character with a "_" as a temporary fix!
#1993
> fix: broken Log Streaming URL when working directory is set to "./" 

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
Similar to #1131, we see this for /files/ too, resulting in a plan
error.
Closes #1905
> fix: retry /files/ requests to github

- runatlantis.io/docs/policy-checking.md
* Specify the workflow for the repo under the `repos` key.
* Fix indentation
* Fix typo `seperate` -> `separate`
> docs: fix policy example with custom workflow

- server/events/vcs/github_client.go
The previous code loops through the teams in the organization and makes an API call in each loop to check the user membership. This change uses GitHub GraphQL API to retrieve the team list the user belongs to with one API call so it's less likely to exceed the rate limit.
> fix: get user teams with GitHub GraphQL API

- server/middleware.go
This is to avoid plaintext printing of web credentials
> Removing web credentials from debug log

- server/controllers/templates/web_templates.go
- server/static/bindata_assetfs.go
When setting '--atlantis-url' this static content 404s.
For example, we can see this when comparig:
- /lock --> works seamless with a custom `--atlantis-url`
- /jobs --> doesn't work when using a custom `--atlantis-url`
Note that for the different templates, we are configuring `CleanedBasePath: s.AtlantisURL.Path`:
https://github.com/runatlantis/atlantis/blob/58e9b42bbc21bd6d2706b8c8b9c6cd6ad699c3c8/server/server.go#L879-L884
https://github.com/runatlantis/atlantis/blob/d914eafd2a3343fb22211018661bed1881b813e6/server/controllers/locks_controller.go#L82-L94
https://github.com/runatlantis/atlantis/blob/58e9b42bbc21bd6d2706b8c8b9c6cd6ad699c3c8/server/controllers/jobs_controller.go#L45-L54
Credit goes to @iainlane 👍
> fix(web-templates): use CleanedBasePath for static content

- server/controllers/templates/web_templates.go
A follow-up to https://github.com/runatlantis/atlantis/pull/2079
After upgrading to https://github.com/runatlantis/atlantis/releases/tag/v0.18.3 in our own infra, I noticed a minor issue with the links in the titles, they are still pointing to `/` even when '--atlantis-url' is provided.
> fix(web-templates): use CleanedBasePath for titles

- docker-base/Dockerfile
The current PR includes the following updates:
- Bumps `gosu` version to 1.14. Not much to say here - just version bump.
- Changes the way `git-lfs` is installed. Apk pulls a version compiled against go 1.17.2, which is an old version with a number of known CVEs. The new source is GitHub, which pull the same version of `git-lfs` build against go 1.17.6.
> docker: bump git-lfs and gosu dependencies

- docker-base/Dockerfile
This uses a similar pattern than what is used for `GOSU_ARCH` to map the
`TARGETPLATFORM` argument into the name of the architecture git-lfs use for
their release binaries, as "linux/arm/v7" otherwise would be mapped into "v7"
which is wrong.
> fix(docker): fix installation of git-lfs in armv7 image

- Dockerfile
This firstly drops Terraform versions prior to 0.11.15 because they don't have all the architectures available that Docker images are built for. I don't assume many people use those versions anymore. Should this be communicated in some special way as it technically is a breaking change?
Terraform is now downloaded for the architecture the Docker image is being built for and the same goes for conftest, although this makes it apparent there's no binary available for conftest for armv7.
I have kept it downloading the x86_64 binary for now in order to keep this change simpler, but I guess the alternatives are:
* to compile an armv7 version of conftest when building the Docker image
* keep it like it is now and say conftest is unsupported on armv7 (at least for now)
* drop support of the armv7 …
> fix(docker): download Terraform and conftest versions maching image architecture

- .circleci/config.yml
We dont have docker multiplatform setup for circleci and we have defaulted to ghcr for quite some time, thus removing the circleci support docker image updates.
> ci: drop circleci docker hub update

- Dockerfile
- docker-base/Dockerfile
- docker-entrypoint.sh
This reintroduces the changes that were reverted in #2106 and adds one extra change in 697ea1723ebca89be49d4049a94861fcc056f77c which fixes the problem reported in #2104.
The gist is the path to `dumb-init` changes from `/bin/dumb-init` to `/usr/bin/dumb-init` when we install it via `apk` rather than downloading the binary directly. Since it's the first binary Docker tries to execute and it can't find it, it gives the somewhat cryptic error message:
> standard_init_linux.go:228: exec user process caused: no such file or directory
I believe the steps for getting this merged and built correctly are:
1. Merge this PR
1. Wait for the `atlantis-base` image to be built
1. Change the tag for the `atlantis-base` image in `Dockerfile` to point at the newly built base image
1. Wait for the …
> fix(docker): Multi-arch Docker images, attempt two

- server/events/vcs/bitbucketcloud/client.go
I observed this error:
```json
{
"level": "error",
"ts": "2022-02-01T20:21:06.571Z",
"caller": "events/project_command_runner.go:156",
"msg": "updating project PR status%!(EXTRA *errors.errorString=making request \"POST https://api.bitbucket.org/2.0/repositories/myworkspace/myrepo/commit/abc1605a840c/statuses/build\" unexpected status code: 400, body: {\"type\": \"error\", \"error\": {\"fields\": {\"key\": [\"Ensure this value has at most 40 characters (it has 53).\"]}, \"message\": \"key: Ensure this value has at most 40 characters (it has 53).\"}})",
"json": {
"repo": "myworkspace/myrepo",
"pull": "19"
},
"stacktrace": "github.com/runatlantis/atlantis/server/events.(*ProjectOutputWrapper).updateProjectPRStatus\n\tgithub.com/runatlantis/atlantis/server/events/project_command_runner.go:156 …
```
> fix(bitbucketcloud): Ensure status key has at most 40 characters

- server/events/event_parser.go
- server/events/event_parser_test.go
- server/events/testdata/bitbucket-cloud-comment-event.json
- server/events/testdata/bitbucket-cloud-pull-event-updated.json
- server/events/vcs/bitbucketcloud/models.go
- server/events/vcs/bitbucketcloud/testdata/pull-approved-by-author.json
- server/events/vcs/bitbucketcloud/testdata/pull-approved-multiple.json
- server/events/vcs/bitbucketcloud/testdata/pull-approved.json
- server/events/vcs/bitbucketcloud/testdata/pull-unapproved.json
I want to be able to identify the user running the workflow and do checks like https://github.com/runatlantis/atlantis/issues/308#issuecomment-479930295, and `nickname` is not appropriate:
> Note that while we are introducing a nickname field, it will not be effective for identifying user accounts, because nicknames are not guaranteed to be globally unique. If you do store user data, we strongly encourage you to use Atlassian account IDs as the identifier for your data.
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/
I also clean up `username` from the test data, since it has been removed on 29 April 2019.
I suppose `PullRequest.Author` is only informative, so it should be fine to keep `Nickname` there.
For reference, the change from `Username` to `Nickname` …
> fix(bitbucketcloud)!: Use AccountID as username instead of Nickname

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
This should fix issue #2090 by using the right client from shurcooL's library. 
Notes: By using GraphQL new scopes `['read:org', 'read:discussion']` are required by the OAuth token. C.f. https://docs.github.com/en/graphql/guides/forming-calls-with-graphql
> fix: fix unmarshall error in graphql call

- CONTRIBUTING.md
- runatlantis.io/docs/deployment.md
> docs: update docker registry link to ghcr

- docker-base/Dockerfile
Bump [hub.docker.com/_/alpine/](https://hub.docker.com/_/alpine/) from 3.15 to 3.15.2 that addresses `libretls` vulnerability.
More details here: https://alpinelinux.org/posts/Alpine-3.15.2-released.html
> build(deps): bump alpine base image from 3.15 to 3.15.2

- runatlantis.io/docs/apply-requirements.md
typo: `apply` is not a valid requirement, `approved` is.
> docs: fix apply requirements list

- server/events/working_dir.go
- server/server.go
closes #1696
i baked an image with my changes. running atlantis against private forks now works in my installation
> fix(github): allow Github App to clone forks of a private repository

- docker-base/Dockerfile
Updating the base image upgrades packages to address vulnerabilities
If I run `apk update && apk upgrade` on the original alpine base image `3.15.2`, the following upgrades are made:
```
➜ docker run --rm -ti localhost/atlantis-base:3.15.2 bash                  
bash-5.1# apk update -vvv
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
v3.15.4-28-gf3bb9d0183 [https://dl-cdn.alpinelinux.org/alpine/v3.15/main]
v3.15.4-38-gf7d0da3611 [https://dl-cdn.alpinelinux.org/alpine/v3.15/community]
OK: 15858 distinct packages available
bash-5.1# apk upgrade -vvvv
The following packages will be upgraded:
busybox ssl_client zlib
After this operation, 0 B of additional disk space will be used. …
```
> Update alpine base from 3.15.2 to latest patch version 3.15.4

- runatlantis.io/docs/locking.md
Currently, the only way to unlock according to the docs is to click through to the UI, which may not be available due to security issues etc. Update the docs to include `atlantis unlock` as a method to remove the lock from a PR.
> docs: Add unlock command

- docker-base/Dockerfile
"Fixes" https://github.com/runatlantis/atlantis/issues/2174 and might also be related to https://github.com/runatlantis/atlantis/issues/1047. This is not a hard issue but more of a convenience addon that might save some folks a lot of headaches.
> Add gcompat library to Docker base image for convenience

- server/controllers/github_app_controller.go
- server/controllers/templates/web_templates.go
Fixes: https://github.com/runatlantis/atlantis/issues/2141
Template for `GithubAppSetupTemplate` refers to the property `CleanedBasePath` of `GithubSetupData` struct that was undefined.
- Property `CleanedBasePath` was added into `GithubSetupData` struct
- Property `CleanedBasePath` is assigned in `server/controllers/github_app_controller.go` with `g.AtlantisURL.path`
Where `g` is `GithubAppController` struct
- Tested locally with modified for local dev `docker-compose run atlantis server`. 
Was able to see `http://localhost:4141/github-app/setup` page
> fix: Add CleanedBasePath to GithubSetupData (#2141)

- docker-entrypoint.sh
Addresses https://github.com/runatlantis/helm-charts/issues/14
See also: https://github.com/runatlantis/helm-charts/pull/21
> Implement runWithUser/fsGroup within entrypoint

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
Fix for the issue https://github.com/runatlantis/atlantis/issues/2135.
Behavior started in version 0.18.0, apply jobs are not being ignored during the apply requirements validation.
> [fix] ignore commit status for apply jobs (#2135)

- server/events/vcs/gitlab_client_test.go
Currently this is failing on PRs. Looks like this was added in the last day in #2137
```
server/events/vcs/gitlab_client_test.go:301:14: Error return value of `w.Write` is not checked (errcheck)
w.Write([]byte(response))
```
> fix: branch CI pipeline due to unchecked err in test

- server/events/working_dir_test.go
This fixes the tests to not rely in the implicit value of the
"defaultBranch" git configuration value, since they later assume that
it's "master".
For example, if you run:
```sh
git config --global init.defaultBranch main
```
And then run these tests, you get:
```sh
--- FAIL: TestClone_CheckoutMergeNoneExisting (0.69s)
working_dir_test.go:71: err running "git checkout master": error: pathspec 'master' did not match any file(s) known to git
--- FAIL: TestClone_CheckoutMergeNoReclone (0.71s)
working_dir_test.go:127: err running "git checkout master": error: pathspec 'master' did not match any file(s) known to git
--- FAIL: TestClone_CheckoutMergeNoRecloneFastForward (0.71s)
logger.go:130: 2022-05-17T10:15:03.244-0700 INFO    creating dir "/tmp/3840955393/repos/0/default" …
```
> fix: working dir tests initial branch assumes "master"

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
This allows forks of atlantis to push images to their own ghcr.
> build: generalize the image tag in image workflow

- .circleci/config.yml
- Makefile
I noticed builds failing, for two separate issues.
The install script location for golangci-lint has been changed, you can see the new one in their docs - https://golangci-lint.run/usage/install/#other-ci
`docs.github.com` seems to have some bot protection in front of it. It can be worked around by requesting compressed content - https://github.com/github/docs/issues/17358#issuecomment-1111864031
> Fix for failing builds

- server/core/runtime/common/common_test.go
- server/core/runtime/init_step_runner_test.go
- server/events/pending_plan_finder_test.go
- server/events/working_dir.go
- server/events/working_dir_test.go
* Ignore gpg signing for tests
* `make test` fails for me because I gpg sign all my commits by default
* It seems like this has been seen before because `TestPendingPlanFinder_FindPlanCheckedIn` contains `--no-gpg-sign` and others don't.
> Ignore gpg signing for tests

- server/controllers/status_controller.go
- server/controllers/status_controller_test.go
- server/server.go
* Add version to /status endpoint
* Much easier to identify what version is actively running
* Finally closes https://github.com/runatlantis/atlantis/issues/1119
* Previous PR https://github.com/runatlantis/atlantis/pull/1120
* and helpful comments from @lkysow !
```
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -v -o atlantis .
./atlantis server --gh-user=nitrocode --repo-allowlist=atlantis
```
```
✗ curl localhost:4141/status
{
"shutting_down": false,
"in_progress_operations": 0,
"version": "0.19.3"
}
```
> Add version to /status endpoint

- server/events/event_parser.go
- server/events/event_parser_test.go
- server/events/mocks/mock_event_parsing.go
- server/events/testdata/gitlab-merge-request-event-update-assignee.json
- server/events/testdata/gitlab-merge-request-event-update-description.json
- server/events/testdata/gitlab-merge-request-event-update-labels.json
- server/events/testdata/gitlab-merge-request-event-update-mixed.json
- server/events/testdata/gitlab-merge-request-event-update-new-commit.json
- server/events/testdata/gitlab-merge-request-event-update-target-branch.json
- server/events/testdata/gitlab-merge-request-event-update-title.json
This MR further parses Gitlab MergeRequest Update event to see if Atlantis should handle the update or just ignoring it. With current implementation of gitlab sdk used in Atlantis. We could ignore events such as assignee/description/title/labels changing
> Further parse Gitlab MergeRequest Update events

- runatlantis.io/docs/using-atlantis.md
- server/controllers/events/events_controller_e2e_test.go
- server/events/command_runner_test.go
- server/events/plan_command_runner.go
- server/server.go
This PR is an alternative to https://github.com/runatlantis/atlantis/pull/1633 and aims to fix https://github.com/runatlantis/atlantis/issues/1624
It solves the same problem but instead of deleting plans and locks directly it uses the `DeleteLocksByPull` method.
As a consequence every time an autoplan or generic `atlantis plan` command is issued it completely removes the working dir (which might be more than one for a single PR if non-default workspaces are used).
The change in this PR might be better because it reuses an existing method for cleaning up lock and plan but it might in some cases delete working directories that atlantis could have otherwise reused. 
Especially when using non-default workspaces atlantis creates a copy of the repository for every project in a PR. With this PR …
> fix: Delete locks and workdirs with potentially stale previous plans which fixes 1624

- runatlantis.io/docs/streaming-logs.md
Hello, I was reading through these docs and this section seemed incorrect. I assume the 2 commands it supports are atlantis plan/apply and not the underlying 3 terraform commands. Let me know if I'm misinterpreting this. Thanks!
> docs: update streaming-logs

- server/controllers/events/events_controller_e2e_test.go
- server/events/apply_command_runner.go
- server/events/command_runner_test.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/azuredevops_client_test.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketcloud/client_test.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
- server/events/vcs/instrumented_client.go
- server/events/vcs/mocks/mock_client.go
- server/events/vcs/not_configured_vcs_client.go
- server/events/vcs/proxy.go
- server/events/vcs/pull_status_fetcher.go
- server/server.go
Fix for the #2304 issue, where a custom VCS Status Name is ignored in the PullIsMergeable function.
> fix: vcs-status-name hardcoded in PullIsMergeable function

- server/controllers/events/testfixtures/null_provider_lockfile_old_version
```
server/controllers/events/testfixtures/test-repos/simple-with-lockfile/exp-output-autoplan.txt.act
server/controllers/events/testfixtures/test-repos/simple-with-lockfile/exp-output-plan.txt.act
```
error message with `terraform init`:
```
- Finding hashicorp/null versions matching "3.0.0"...
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/null v3.0.0 does not have a package
│ available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers
│ are available for all platforms. Other versions of this provider may have
│ different platforms supported.
```
> test: update null provider to support test run on m1 machine

- docker-entrypoint.sh
Fixes #2322 
See another PR (in helm-charts repo) that enables use of fsGroupChangePolicy instead.
https://github.com/runatlantis/helm-charts/pull/158
> Remove workaround for atlantis-data in entrypoint

- server/events/comment_parser.go
- server/events/comment_parser_test.go
I ran into a minor UX issue when copy-pasting a command for Atlantis. It looks like Github added an extra line before and after my comment, causing my comment to be silently ignored, after which I thought the apply was just hanging.
Based on the code comments around this, it looks like the intent was to at least allow trailing whitespace for this reason, so I reasoned it might be ok to allow leading whitespace as well. This change just trims whitespace from the left and right of the comment before parsing it, in an attempt to make things a little more flexible. I've added test cases for both leading whitespace and whitespace on both sides, in addition to the trailing whitespace test cases from before.
It's possible that blindling trimming whitespace could be problematic, so I'm …
> trim whitespace from comments before parsing

- runatlantis.io/docs/custom-workflows.md
With #2261, we now open a stdin pipe like the built-in terraform client
does. Doing so apparently caused some user's `plan`s to hang when they
had variables requiring inputs, since `terraform` saw that stdin was
open and prompted for a value.
https://github.com/runatlantis/atlantis/pull/2261#issuecomment-1170513957
https://github.com/runatlantis/atlantis/pull/2261#issuecomment-1170513957
https://github.com/runatlantis/atlantis/pull/2261#issuecomment-1170552929
> Update terragrunt workflow documentation

- .dockerignore
- docker-compose.yml
This PR solves two issues.
1) Currently you need to pass a `NGROK_AUTH` to ngrok, otherwise you'll get following error when trying to use the connection:
2) `atlantis` executable must not be ignored by `.dockerignore` otherwise `docker-compose up` and `docker build -f Dockerfile.dev .` fails with:
```
[+] Building 1.0s (6/7)
=> [internal] load build definition from Dockerfile.dev 0.0s
=> => transferring dockerfile: 36B 0.0s
=> [internal] load .dockerignore 0.0s
=> => transferring context: 116B 0.0s
=> [internal] load metadata for ghcr.io/runatlantis/atlantis:latest 0.8s
=> [internal] load build context 0.0s
=> => transferring context: 2B 0.0s
=> [1/3] FROM ghcr.io/runatlantis/atlantis:latest@sha256:3765101d3ee2b9db27f140a4766222b400f63d3cb4659d64394bcc6a2eedcec7 0.0s
=> ERROR [2/3] COPY …
```
> fix(docker-compose): update docker-compose

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- .github/workflows/testing-env-image.yml
Change the build job for the docker image to use the matrix jobs feature, speeding up the image creation.
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
> workflows: build image in parallel

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/command_runner.go
- server/events/var_file_allowlist_checker.go
- server/events/var_file_allowlist_checker_test.go
- server/server.go
- server/user_config.go
Add a new argument `--var-file-allowlist` in server configuration to limit the access of variable definitions files on Atlantis server. Previously, we don't have such check so users can access arbitrary files that the Atlantis process has access to, with PR comments like `atlantis plan -- -var-file=/path/to/file`.
The default value of this argument is currently set to `--data-dir`. This could be a breaking change since users who used to access files on Atlantis server outside of that directory need to pass in additional paths when running Atlantis. For users who only accessed files in repo directories, the behavior remains unchanged since files in the repo directory are still accessible as before.
> Add --var-file-allowlist in server configuration

- runatlantis.io/docs/security.md
Add section in security doc as a follow-up of https://github.com/runatlantis/atlantis/pull/2362.
> Add section for --var-file-allowlist in security doc

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- .github/workflows/testing-env-image.yml
Reverts runatlantis/atlantis#2361
fixes #2371
> Revert "workflows: build image in parallel"

- server/controllers/github_app_controller.go
As described over the issue #2310 it seems like the permission required to check `required_status_checks` endpoint is allowed under the scope of `administration` > `branches`, check [github docs: permissions-required-for-github-apps#permission-on-administration](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-administration).
```
[GET /repos/:owner/:repo/branches/:branch/protection/required_status_checks](https://docs.github.com/en/rest/reference/branches#get-status-checks-protection) (:read)
```
This pull-request adds the required extra permission to `read` under `administration` to check the desired endpoint.
> Add permission to allow GET `required_status_checks`, linked to #2310

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/terraform-cloud.md
- server/server.go
- server/user_config.go
When using TFE just for storing states and not for remote execution mode, seeing the streaming plan logs in Atlantis is currently broken.
It's is due to when setting `--tfe-token` (or `ATLANTIS_TFE_TOKEN` env) then the `NoopProjectOutputHandler` is used instead of `NewAsyncProjectCommandOutputHandler`.
This PR implements a new option `--tfe-local-execution-mode` so Atlantis will keep using the `NewAsyncProjectCommandOutputHandler`.
This PR might be the fix for #2111 and #2129
> fix: Log streaming broken with TFE local execution mode

- server/events/markdown_renderer_test.go
- server/events/models/models.go
The lazy regex for converting Terraform diffs to GitHub diffs would also mark YAML and other plain text that happen to start with `-`, `+`, or `~`. This is a bit more selective, scanning for obvious Terraform changes that contain `->`, `<<` for heredocs, `{` for modules/resources/blocks, `known after apply`, and `[` for lists. It will also do a second pass to attempt to capture changes to lists too.
Closes #2241
> fix: Only highlight Terraform changes on GitHub

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
This PR reverts a change that accidentally introduced regression described by https://github.com/runatlantis/atlantis/issues/2112, where an unmergeable GitHub PR can be applied when `apply_requirements: [mergeable]` is set.
Disclaimer: This PR doesn't implement additional features that cover more use cases, but only tries to resolve the regression.
This reverts commit a3db71292007497d97d4c417589cfe701b560ba8.
Revert "[fix] Ignore commit checks for atlantis apply on Github (#2311)"
> Revert "[fix] Ignore commit checks for atlantis apply on Github (#2311)"

- runatlantis.io/docs/streaming-logs.md
We noticed https://github.com/runatlantis/atlantis/pull/2261 and https://github.com/runatlantis/atlantis/pull/2350 landed and thought it should be mentioned in this doc as well.
> CHANGED - update streaming-logs doc to mention terragrunt support

- .circleci/config.yml
Follow up fix for https://github.com/runatlantis/atlantis/pull/2393 since [website_link_check](https://app.circleci.com/pipelines/github/runatlantis/atlantis/2460/workflows/797590b6-1c20-44fb-9111-2f0a59b5690d/jobs/10616) is failing.
> Fix helm chart url in website_link_check

- go.mod
- go.sum
- server/events/working_dir.go
This is my proposal to fix #2341.
> fix: repository cloning race condition (#2341)

- server/core/runtime/multienv_step_runner.go
- server/core/runtime/multienv_step_runner_test.go
Fixes #2351.
* Update multienv_step_runner.go to split only on the first = character
* Add affirmative and failing test cases
> fix: Update multienv_step_runner Env Var Parsing Logic (#2351)

- runatlantis.io/docs/deployment.md
the helm chart parameter for `orgWhitelist` have been deprecated since version 4.0.2 and have been replaced by `orgAllowlist` since this commit: https://github.com/runatlantis/helm-charts/commit/89da1af324c27bbe608052a577d60957a030e9b4. But the deployment instruction is still referencing the old parameter
* updated `orgWhitelist` to `orgAllowlist` in deployment.md
* updated the link in deployment.md pointing to `--repo-allowlist` in server-configuration.md (changed extension from `.html` to `.md` to make the link work when reading on GitHub, netlify will automatically convert to `.html`)
* added a note to indicate `orgWhitelist` should still be used for helm chart versions prior to 4.0.2
> Update documentation to reflect orgAllowlist changes in helm chart

- server/events/webhooks/mocks/mock_slack_client.go
- server/events/webhooks/slack.go
- server/events/webhooks/slack_client.go
- server/events/webhooks/slack_client_test.go
- server/events/webhooks/webhooks_test.go
This PR removes the check about the existence of a slack channel.
This is done to:
- avoid the necessity of `channels:read` scope to the corresponding bot (this is a broad scope and many orgs may be reluctant providing it)
- the specific check hits the `conversations.list` [endpoint](https://api.slack.com/methods/conversations.list) that has a lower rate [limit](https://api.slack.com/docs/rate-limits#tier_t2) that **may** be also related to this [issue](https://github.com/runatlantis/atlantis/issues/1420)
> Removing the check about whether a slack channel exists

- runatlantis.io/docs/using-slack-hooks.md
Clarify instructions on how to implement the webhook config changes when using a Helm chart deployment of Atlantis.
Add tidbit about adding the Slack app to the Slack channel used for notifications.
> fix: Clarify Slack hook setup for Helm chart deployments. Add tidbit about Slack channel setup.

- Dockerfile
- docker-base/Dockerfile
Bump alpine version to 3.16.1 in order to resolve several vulnerabilities around curl/pcre2/git.
> deps: bump alpine to v3.16.1

- runatlantis.io/docs/deployment.md
The deployment documentation manifest examples should use ghrc.io as image repository for runatlantis/atlantis, as dockerhub is deprecated as image repository.
Fix for issue #2422
> Use ghcr.io as image repostiory in docs manifests

- runatlantis.io/docs/custom-workflows.md
- Add docs on cdktf ([preview](https://github.com/nitrocode/atlantis/blob/cdktf-docs/runatlantis.io/docs/custom-workflows.md))
- cdktf is pretty cool
- it's nice to see how flexible atlantis is to make this possible without any code changea
- https://github.com/runatlantis/atlantis/issues/1441
> cdktf docs

- runatlantis.io/.vuepress/config.js
- runatlantis.io/docs/server-configuration.md
Small UI changes regarding anchor links.
Currently, when clicking header links in server configuration doc, such as `--allow-fork-prs`, the expected anchor link https://www.runatlantis.io/docs/server-configuration.html#allow-fork-prs won't persist, but will be changed to https://www.runatlantis.io/docs/server-configuration.html#flags.
The reason is that we are enabling [Active Header Links](https://vuepress.vuejs.org/theme/default-theme-config.html#active-header-links) with a [`sidebarDepth`](https://vuepress.vuejs.org/theme/default-theme-config.html#nested-header-links) to be `1` by default. So once we jump to the `#allow-fork-prs` tag, we are immediately redirected to the parent tag within `sidebarDepth`, in this case, `#flags`.
One way to fix this is to increase the `sidebarDepth`, …
> Disable activeHeaderLinks for VuePress. Remove bullet points in server config doc.

- runatlantis.io/docs/server-side-repo-config.md
- runatlantis.io/docs/stats.md
There is clearly the intent to provide cross-links in these docs, but they needed proper Markdown formatting (and lowercase anchor tags).
> Fix some not-quite-links in docs

- server/core/config/raw/metrics.go
- server/core/config/raw/metrics_test.go
> enable hostname (not only IP Address) on Metrics statsd host key

- server/events/post_workflow_hooks_command_runner_test.go
Go has type inference, and it's considered non-idiomatic to specify types when declaring a var with an initial value.
```go
var name = "Joe"
var name string = "Joe" // string here is redundant
```
> Omit type declaration of vars

- server/events/vcs/github_client.go
This is an alternative take on GitHub v4 client token refresh issue.
See another approach https://github.com/runatlantis/atlantis/pull/2475
Hopefully fixes https://github.com/runatlantis/atlantis/issues/2285
> Use proper http client for github v4 api

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- .github/workflows/ci-link-checker-image.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- .github/workflows/testing-env-image.yml
Recently, [ubuntu-22.04 went GA](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/), thus, updating the runners.
For the OS installed software differences, see [this issue](https://github.com/actions/runner-images/issues/5490)
> workflows: update runner to use ubuntu-22.04

- server/middleware.go
If WebAuthentication is enabled, API Endpoints can't be hit without Basic Auth on top of API Secret.
Not sure if this is by design, but I'd assume API Tokens should be decoupled from the WebAuthentication?
```sh
curl -vH "X-Atlantis-Token: ${ATLANTIS_API_SECRET}" \
-H "Accept: application/json" \
-H "Content-Type: application/json"  \
http://localhost:4141/api/plan \
-d '{ "repository": "...","ref":"...","type":"...","projects":["..."]}'
> OK
```
```sh
curl -vH "X-Atlantis-Token: ${ATLANTIS_API_SECRET}" \
-H "Accept: application/json" \
-H "Content-Type: application/json"  \
http://localhost:4141/api/plan \
-d '{ "repository": "...","ref":"...","type":"...","projects":["..."]}'
> Unauthorized
```
Work Around:
```sh
curl -vH "X-Atlantis-Token: ${ATLANTIS_API_SECRET}" \
-H "Authorization: …
```
> fix: allow requests to /api/* without authentication

- server/events/markdown_renderer_test.go
- server/events/models/models.go
In https://github.com/runatlantis/atlantis/pull/2337, I modified the GitHub Markdown regex to correctly handle YAML in the Terraform output. Unfortunately, that broke highlighting for resources that were being created or deleted. The updated regex will now also accept an `=` sign with spaces either side. It might incorrectly highlight some plain text in plans, but it should fix the error.
Closes #2425
> bug: Fix GitHub Markdown for added and deleted resources

- server/controllers/api_controller.go
- server/core/runtime/apply_step_runner_test.go
- server/events/event_parser_test.go
- server/events/pull_closed_executor_test.go
- server/static/bindata_assetfs.go
As of go1.16, io/util package has been deprecated
- See issue, https://github.com/golang/go/issues/42026
- follow up of #1843
> lint: remove deprecated io/util package

- cmd/server.go
- runatlantis.io/docs/server-configuration.md
- server/core/redis/redis.go
- server/core/redis/redis_test.go
- server/server.go
- server/user_config.go
The current implementation works great so far for using Redis as a locking DB. A slight oversight on the initial work, though, was being able to enable TLS for the connection to Redis. This change adds the option to turn on TLS for Redis for those that so desire.
Additionally, this adds a PING test on the client creation to ensure the connection is good to go.
> Adding Redis TLS Option

- Dockerfile
- [DL4006](https://github.com/hadolint/hadolint/wiki/DL4006) - Set the SHELL option -o pipefail before RUN with a pipe in
- [SC2086](https://github.com/hadolint/hadolint/wiki/SC2086) - Double quote to prevent globbing and word splitting.
- Reduce risk by addressing hadolint suggestions
- https://github.com/hadolint/hadolint
Before
```sh
$ hadolint Dockerfile
Dockerfile:19 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
Dockerfile:19 SC2086 info: Double quote to prevent globbing and word splitting.
Dockerfile:40 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you …
```
> chore: Use hadolint to fix DL4006, SC2086

- cmd/server.go
- runatlantis.io/docs/server-configuration.md
- server/core/redis/redis.go
- server/core/redis/redis_test.go
- server/server.go
- server/user_config.go
This exposes the remaining Redis connection option, `DB`,  which was hard-coded to `0` in the initial Redis Locking DB work.
This allows selecting something other than the default database of `0`. Atlantis may now use a different numerical database if needed, while still defaulting to `0`. Common use case is multiple applications using the same redis server and using database as a mechanism for name spacing different applications. This could also allow multiple atlantis instances to share a single redis instance and separate locks by database. cc @SudoSpartanDan
> Adding Redis DB option

- server/controllers/events/events_controller.go
- server/events/instrumented_pull_closed_executor.go
Prometheus metrics names have some restrictions that must match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`
The metric names have some restrictions which are documented here: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
This resolves https://github.com/runatlantis/atlantis/issues/2379
Also, see https://github.com/runatlantis/atlantis/pull/2204#issuecomment-1205005094
> Fix: Error when enabling prometheus metrics

- runatlantis.io/docs/using-atlantis.md
- server/controllers/events/events_controller_e2e_test.go
- server/events/command_runner_test.go
- server/events/plan_command_runner.go
- server/server.go
This PR aims to fix https://github.com/runatlantis/atlantis/issues/1624 (and https://github.com/runatlantis/atlantis/issues/1122)
When using non-default workspaces, plans are stored in pr-and-workspace-specific directories.
This is often the case when people want to use the parallel plan/apply feature of Atlantis to speedup how long it takes to plan PRs that change a lot of projects at the same time
If a PR is updated after being created it might happen that some of the original plans are no longer relevant with regards
to the latest changes.
The change in this PR ensures that previous plans are always deleted when a generic plan is triggered either by autoplan
or by a "atlantis plan" command.
NB Even after this change plans are not going to be cleaned up when specific projects are …
> Delete previous plans on autoplan or atlantis plan

- server/events/comment_parser.go
- server/events/project_command_builder.go
- server/events/project_finder.go
- server/events/project_finder_test.go
- server/events/testdata/test-repos/cloud-block-without-workspace-name/main.tf
- server/events/testdata/test-repos/no-cloud-block/main.tf
- server/events/testdata/test-repos/workspace-configured/main.tf
- server/events/working_dir.go
> Getting working workspace from Terraform Cloud configuration

- .github/workflows/test.yml
- CHANGELOG.md
- kustomize/bundle.yaml
- main.go
> Release v0.19.9

- .github/workflows/atlantis-image.yml
- Set the concurrency to replace `head_ref` with `ref` 
- Set the concurrency to replace `run_id` with `run_number` 
- Fix concurrency in atlantis-image workflow
- Use `ref` because `head_ref` is only for `pull_request` events and this workflow does not run on PRs
- Use `run_number` because the id is always unique whereas the number starts at 1 and continues for each workflow
- Original commit https://github.com/runatlantis/atlantis/commit/317b922c8e4d18301169cb90d5ab282f52edac99
- https://docs.github.com/en/actions/learn-github-actions/contexts
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
- Run 2552
- https://github.com/runatlantis/atlantis/actions/runs/3193021368/jobs/5211149751
- …
> Fix concurrency in `atlantis-image` workflow

- docker-base/Dockerfile
Includes fixes for:
CVE-2022-40674
CVE-2022-37434
Dockerfile also needs updating to build on new base image, after merging this.
> Bump alpine to 3.16.2

- README.md
At the top of the README is a "badge" to join the slack channel and uses a [join.slack.com](https://join.slack.com/t/atlantis-community/shared_invite/enQtNzc4NDM3OTA3ODI0LTA5NDQ4YTA3NTAxM2I3ZmIxMGNiYWJhNmY4YjBjZjM3OWMzNGI0NTcxNzY2NjRhODIyODA4YmNjOTBiOThhNTI) address. Further down is another reference to join Slack but links to a custom Heroku app to send an invite to someone. I think the custom Heroku app is legacy link and could be replaced by the join.slack.com url?
Thanks
> (README) Use join.slack.com instead of custom heroku app

- runatlantis.io/docs/server-configuration.md
A newline was missing which broke the markdown rendering.
> Fix server-configuration docs, missing newline

- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/apply-requirements.md
- runatlantis.io/docs/configuring-webhooks.md
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/webhook-secrets.md
Add documents.
* Fill all command line flags not in the document from `server/server.go`, related: #1161 .
* Add document about #2436 .
* and misc.
> docs: fill all command line flags not in the document, and more.

- runatlantis.io/docs/access-credentials.md
* #2380 is a great work, I also had trouble with the error message `Pull request must be mergeable before running apply`, which was solved by this PR.
* My PR is to add to the docs about #2380. We need to add a new permission to the GitHub app manually. I was able to find #2380, but anyone reading only the docs should also be able to find this solution.
> docs: added GitHub app permission in #2380

- CHANGELOG.md
- kustomize/bundle.yaml
- main.go
Releasing `0.20.1` due to `0.20.0` failed due to github actions issues
> Release 0.20.1

- server/events/event_parser.go
Fix #2537 by removing redundant conditional branch
> fix #2537: `if` with identical `then` and `else` branches

- server/controllers/events/events_controller.go
Solve #2493 
With this PR, the flag [--silence-allowlist-errors](https://www.runatlantis.io/docs/server-configuration.html#silence-allowlist-errors) is working as expected. The log messages are aware of the flag when an HTTP error is returned.
> fix: Silence allow list errors works again

- .github/workflows/atlantis-base.yml
- docker-base/Dockerfile
- pinned the dependencies to the latest base image
- This will allow the atlantis images more immutability. We'll also be able to control when we update base packages when necessary instead of always retrieving the latest.
- Fixed another hadolint issue
- https://github.com/hadolint/hadolint
- https://github.com/hadolint/hadolint/wiki/DL3018
- https://github.com/runatlantis/atlantis/pkgs/container/atlantis-base/44682219?tag=2022.10.06
```
$ hadolint docker-base/Dockerfile
docker-base/Dockerfile:28 DL3003 warning: Use WORKDIR to switch to a directory
docker-base/Dockerfile:28 DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
```
<details><summary>Get package versions of atlantis-base:2022.10.06</summary>
```sh
$ docker run \
-it --rm …
```
> hadolint: base: pin all dependencies

- .github/workflows/atlantis-image.yml
- Dockerfile
- Bump atlantis-base:2022.10.14
- Use image with pinned dependencies
- Previous PR https://github.com/runatlantis/atlantis/pull/2587
- https://github.com/runatlantis/atlantis/pkgs/container/atlantis-base/45823137?tag=2022.10.14
- https://docs.github.com/en/actions/learn-github-actions/expressions#example-matching-an-array-of-strings
> Bump atlantis-base:2022.10.14

- .circleci/config.yml
- Dockerfile
- runatlantis.io/docs/access-credentials.md
- runatlantis.io/guide/testing-locally.md
- testdrive/testdrive.go
- testdrive/utils.go
- testing/Dockerfile
- bump terrform to 1.3.3
- correct github doc link for pat token
- Latest terraform
- https://github.com/hashicorp/terraform/releases/tag/v1.3.3
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-fine-grained-personal-access-token
- Previous PR https://github.com/runatlantis/atlantis/pull/2569
- Previous PR https://github.com/runatlantis/atlantis/pull/2430
> deps: bump terrform to 1.3.3 and docs update

- server/events/plan_command_runner.go
Signed-off-by: Forest Oden <forest.oden@beatport.com>
This is a small PR to fix a typo in `plan_command_runner.go` that logs `Running applies in parallel` rather than an expected `Running plans in parallel`.
> fix: typo in log message when running parallel plans

- testdrive/testdrive.go
Also prefix ngrok config temporary filename so that it is easy to distinguish when listing the tmp directory.
Close https://github.com/runatlantis/atlantis/issues/2609.
> Specify ngrok config version

- runatlantis.io/docs/custom-workflows.md
These variables are available in the main `workflow` only.
> docs: update notes to clarify where the environment variables are available

- .github/workflows/stale.yml
- chore: set stale 6mo, close 1mo
- Adjust stale bot so it doesn't close issues or PRs to soon
- https://github.com/runatlantis/atlantis/issues/1575#issuecomment-1253899330
- https://github.com/actions/stale#stale-issue-message
> chore: set stale 6mo, close 1mo

- server/events/markdown_renderer_test.go
- server/events/models/models.go
**Details**: Updated `diffKeywordRegex` to properly handle the following use cases related to YAML content in Terraform output:
- nested inline array, see SomeAuth element
- changes in simple key-value fields, see operationId element
**Testing**: Updated existing `TestRenderProjectResultsWithEnableDiffMarkdownFormat` test case with the following Terraform resource
````
~ resource "aws_api_gateway_rest_api" "rest_api" {
~ body                         = <<-EOT
openapi: 3.0.0
security:
- SomeAuth: []
paths:
/someEndpoint:
get:
-       operationId: someOperation
+       operationId: someOperation2
responses:
204:
description: Empty response.
components:
schemas:
SomeEnum:
type: string
enum:
- value1
- value2
securitySchemes:
SomeAuth:
type: apiKey
in: header
name: Authorization
EOT
id …
```
> Updating diffKeywordRegex to properly handle new test case

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
Prevent Atlantis from updating the commit status on an incorrect Merge Request by passing the Ref (HeadBranch) in the CommitStatusOptions.
- GitLab API reference: https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit
Tested on gitlab.com (v15.x) and Self-hosted (v14.x)
Closes https://github.com/runatlantis/atlantis/issues/2484
> fix: prevent commit status update in incorrect MR

- .circleci/config.yml
- Dockerfile
- testdrive/utils.go
- testing/Dockerfile
- bump terraform to 1.3.4
- Latest terraform
- https://github.com/hashicorp/terraform/releases/tag/v1.3.4
- Previous PR https://github.com/runatlantis/atlantis/pull/2614
> deps: bump terraform to 1.3.4

- runatlantis.io/docs/post-workflow-hooks.md
- runatlantis.io/docs/pre-workflow-hooks.md
- server/core/runtime/post_workflow_hook_runner.go
- server/core/runtime/pre_workflow_hook_runner.go
- server/events/command_runner.go
- server/events/command_runner_test.go
- server/events/mocks/mock_post_workflows_hooks_command_runner.go
- server/events/mocks/mock_pre_workflows_hooks_command_runner.go
- server/events/models/models.go
- server/events/post_workflow_hooks_command_runner.go
- server/events/post_workflow_hooks_command_runner_test.go
- server/events/pre_workflow_hooks_command_runner.go
- server/events/pre_workflow_hooks_command_runner_test.go
This adds the `COMMENT_ARGS` environment variable to pre/post workflow hook execution environments, using the same escaping as for regular workflow steps.
At my workplace, we normally unlock projects after developers run `atlantis plan` since only operators can run applies in most environments (for compliance reasons) and this helps alleviate lock-contention issues. We do this using a post-workflow hook.
However, there are some scenarios where we want to allow developers to conditionally keep their plans. My idea was to use `atlantis plan -- --keep-locks` and handle the logic in the post-workflow hook; however, that doesn't work because post-workflow hooks don't get `COMMENT_ARGS`. I also tried moving the unlocking step to a workflow step, but that fails to delete the plan files:
``` …
```
> Add COMMENT_ARGS to Pre/Post-Workflow Hook Execution Environment

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- server/core/config/parser_validator.go
- server/core/config/parser_validator_test.go
- server/core/config/raw/global_cfg.go
- server/core/config/raw/project.go
- server/core/config/raw/project_test.go
- server/core/config/valid/repo_cfg.go
- server/events/project_command_builder.go
- server/events/repo_branch_test.go
This PR adds the possibility to match branches in repo-level `atlantis.yaml` config file.
With this it becomes possible to use atlantis to deploy different projects for different base branches of the PR (for example: the PR towards `develop` branch would deploy dev environment, while the PR towards `main` would go into production).
> feat: Implement branch matching in repo-level config

- runatlantis.io/docs/server-configuration.md
To better describe the flag about using the team name and not the slug, with practical examples.
> docs:  updates docs on gh-team-allowlist

- .golangci.yml
- Remove archived and deprecated interfacer linter
- interfacer repo has been archived and is no longer maintained
```
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
```
- PR https://github.com/runatlantis/atlantis/pull/2656 shows an interfacer error
- https://github.com/mvdan/interfacer
> Remove archived and deprecated interfacer linter

- .circleci/config.yml
- .github/workflows/testing-env-image.yml
- Makefile
- testing/Dockerfile
- Remove `go get` downloading of `golang.org/x/tools/cmd/goimports` from testing/Dockerfile
- Add trigger for `testing-env-image` workflow if the `testing/**` dir is modified in PR
- Revert `cimg/go` back to `circleci/golang` image
- hadolint fixes
- Using `go get` caused the testing image build failure.
- I saw the error with testing-env-image after merging the PR instead of before. THe new trigger will show the error prior to the merge.
- For some reason the new `cimg/go` image cannot download the terraform version and results in an [e2e error `initializing terraform: terraform not found in $PATH`](https://app.circleci.com/pipelines/github/runatlantis/atlantis/2842/workflows/fd9898b3-bc28-4d6e-81af-7ece0561e9f2/jobs/11532)
- Fixed a couple (not all) linting errors shown by hadolint for …
> e2e image and testing fixes

- .circleci/config.yml
- Dockerfile
- Makefile
- scripts/e2e-deps.sh
- Bump to atlantis-base:2022.11.13
- Use cimg/go:1.19 image and corrected terraform path
- Latest atlantis-base
- The circleci/golang image does not have a 1.19 tag
- Previous PR https://github.com/runatlantis/atlantis/pull/2670
- https://github.com/runatlantis/atlantis/pkgs/container/atlantis-base/50131170?tag=2022.11.13
Note that `/go/bin` is in `circlci/golang` (debian 11.1 bullseye) missing from the `cimg/go` (debian 12-pre-release bookworm/sid) image.
```sh
✗ docker run -it circleci/golang:1.17 sh -c "echo \$PATH | tr ':' '\n'"
/home/circleci/.local/bin
/home/circleci/bin
/go/bin
/usr/local/go/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
✗ docker run -it cimg/go:1.19 sh -c "echo \$PATH | tr ':' '\n'"
/home/circleci/go/bin
/usr/local/go/bin
/home/circleci/bin …
```
> Bump to atlantis-base:2022.11.13 and use cimg/go:1.19

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- Add auto generation of atlantis.yaml projects
- If a repo relies on autodiscovery and default autoplanning without a repo atlantis.yaml file and one project has to be modified to use a unique `when_modified` then every project has to be defined.
- This documentation tip will generate the atlantis.yaml projects key for you.
N/A
> docs: Add auto generation of atlantis.yaml projects

- runatlantis.io/.vuepress/config.js
- runatlantis.io/docs/server-configuration.md
- Fix website link checker branch rename
- Fix all the failures
- Previous PR https://github.com/runatlantis/atlantis/pull/2662
- https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links
> Fix website link checker due to branch rename

- Dockerfile
- Remove 5 old tf versions
- Reduce image size. Each binary is 80MB.
- This removes all terraform versions prior to 1.x.
- This will reduce the image size by 400MB.
- @jamengual and I worked on this and discussed this. Hoping this PR can be a discussion point with a wider audience.
- Example terraform version to download to check file size https://releases.hashicorp.com/terraform/0.12.31/
- Closes https://github.com/runatlantis/atlantis/issues/2622
> Reduce image size by rm'ing old tf versions

- CONTRIBUTING.md
- SECURITY.md
Update vulnerability reporting docs in favor of [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).
> docs: Update docs for vulnerability reporting

- testing/Dockerfile
- testing-env: create default atlantis user
- Running tests on the testing-env fail because the negative tests create files that `root` can see and modify. However, if anyone runs the tests locally, in non-root, it passes fine.
- This issue only seems to affect the new golang 1.19 image and not the previous golang 1.17 image
- Approving and merging this will create a new testing-env image which can be set in our github workflow and circleci to allow bumping dependencies that require modern versions of golang.
- Affects PR https://github.com/runatlantis/atlantis/pull/2521
- Affects PR https://github.com/runatlantis/atlantis/pull/2521
- https://snyk.io/blog/containerizing-go-applications-with-docker/
This command fails to run tests
```sh
$ docker run -it \
-w /atlantis \
-v $(pwd):/atlantis …
```
> testing-env: create default atlantis user

- .circleci/config.yml
- .github/workflows/test.yml
- Makefile
- go.mod
- go.sum
- server/controllers/events/events_controller_e2e_test.go
- server/core/runtime/policy/conftest_client.go
- server/core/runtime/policy/conftest_client_test.go
- server/events/command/name.go
- server/events/commit_status_updater.go
- server/events/markdown_renderer.go
- server/events/project_finder.go
- server/events/repo_branch_test.go
- Bump testing-env
- Bump go-cty@v1.12.1
- Fixed linting issues for go 1.9
- Latest version
- Related PR https://github.com/runatlantis/atlantis/pull/2689
- Related PR https://github.com/lyft/atlantis/pull/454
- https://github.com/zclconf/go-cty
> Bump testing-env and go-cty@v1.12.1

- server/events/vcs/github_credentials.go
- server/events/vcs/github_credentials_test.go
Currently `(c *GithubAppCredentials) GetUser()` is used only for `--hide-prev-plan-comments`.  However when using GitHub app, comments doesn't hide if we use spefic names which contains upper case, spaces and period. This is because GitHub use commend user name like `some-user-com[bot]`, not `Some User.com[bot]`.
We can get slug name from app.Slug.
- Create new GitHub App like `My Atlantis.app`
- Start local server with following options
```
export ATLANTIS_GH_APP_SLUG=my-atlantis-app
export ATLANTIS_HIDE_PREV_PLAN_COMMENTS=true
```
- Then hide comments successfully
----
- Closes #2695
- Closes #1161
> Fix GitHub app uses slug as user name to work --hide-prev-plan-comments correctly

- .circleci/config.yml
- .github/workflows/atlantis-image.yml
- rm duplicate make test-all
- no push to latest on refs with "pre"
- Remove redundant check since it's in both circleci and github actions
- Related to https://github.com/runatlantis/atlantis/pull/1781
- [How to add multiline `if` in gha](https://github.com/orgs/community/discussions/25641#discussioncomment-3248571)
- [Conditional operator or function for expression syntax](https://github.com/actions/runner/issues/409)
> chore: rm duplicate make test-all, no push to latest on refs with "pre"

- cmd/server.go
Tested in our dev env and seems to be working correctly with the flag added.
> fix: Add server flag for quiet policy checks as documented

- .github/workflows/lint.yml
- .github/workflows/test.yml
- runatlantis.io/.vuepress/config.js
- runatlantis.io/docs/server-configuration.md
Could go in separate PR(s)
- Mention `pre_workflow_run` can change `atlantis.yaml` on the fly but cannot change terraform files and ref https://github.com/runatlantis/atlantis/issues/2693
- Mention public blog posts https://github.com/runatlantis/atlantis/issues/2626
- Create customizing image doc (awscli v2, tflint, terragrunt, cdktf, checkov, etc)
- API docs
- Expose all docs in TOC to help spread docs and get updates
- Added reference in TOC to these docs
- https://www.runatlantis.io/docs/faq.html
- https://www.runatlantis.io/docs/stats.html
> docs: Small updates 🦃 

- .github/workflows/lint.yml
- .github/workflows/test.yml
- Add `ready_for_review` type to `test.yml` and `lint.yml` gha
- Run PR checks if the PR is moved to `ready-to-review` type
- Previous PR - Ignore if the PR is in draft - https://github.com/runatlantis/atlantis/pull/2711
> Run PR checks if the PR is moved to `ready_for_review` type

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- .github/workflows/testing-env-image.yml
- Run docker pull before building images
- This should speed up images by downloading the existing image first
- https://github.com/docker/build-push-action
> Run docker pull before building images

- runatlantis.io/docs/server-configuration.md
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- Allow `--gh-team-allowlist` to work with team names and slugs
- Closes https://github.com/runatlantis/atlantis/issues/2717
- Related doc PR https://github.com/runatlantis/atlantis/pull/2664
- Related doc PR https://github.com/runatlantis/atlantis/pull/2005
- Previous PR https://github.com/runatlantis/atlantis/pull/1974
- Previous PR https://github.com/runatlantis/atlantis/pull/1694
- Related discussion https://github.com/runatlantis/atlantis/discussions/2716
> Allow `--gh-team-allowlist` to work with team names and slugs

- .github/workflows/atlantis-image.yml
- Changed double quotes to single quotes in `atlantis-image.yaml` workflow
- This will fix the `bad indentation error` in the `atlantis-image.yaml` workflow
- This has been broken since the previous PR 😬 
- Previous PR https://github.com/runatlantis/atlantis/pull/2703
> Fix the `bad indentation error` in the `atlantis-image.yaml` workflow

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- .github/workflows/testing-env-image.yml
- testing/Dockerfile
This speeds up the Docker image builds by leveraging the GitHub Actions cache to avoid rebuilding unchanged layers.
An attempt at speeding up the builds in #2714 was incorrect, because a misunderstanding of what the `pull` option meant.
This replaces that option with options that instead tell the `build-push-action` to use GitHub Actions cache system.
It should help speed up the builds quite a bit because there otherwise currently isn't any cache used at all.
https://docs.docker.com/build/ci/github-actions/examples/#cache-backend-api
> Use GitHub Actions cache when building Docker images

- Dockerfile
This has the potential to speed up rebuilds of the Atlantis container significantly, especially for non-x86 platforms which are emulated when done in GitHub Actions.
It works by using cache mounts:
https://docs.docker.com/engine/reference/builder/#run---mounttypecache. They mean we can have specific paths set that are carried over from one image build to the next, regardless of which files are changed in the project. The files are however at the same time not part of the final image, which reduces the generated "builder" image from 1.66 GB to just 386 MB on the current main branch.
In my local tests, which doesn't make use of emulation, I saw a drop for the "go build" step going from taking just over 40 seconds with an empty cache to around 1 second when I make a one character change to a …
> Cache downloaded Go dependencies and Atlantis compilation in Docker

- runatlantis.io/docs/deployment.md
New method of deploying Atlantis in Azure Container Group with Terraform.
The current method using a bash script and Azure CLI is not very configurable and is very limited when it comes to holistic deployment of the Azure infrastructure. 
- https://github.com/jplane/atlantis-on-aci
- https://github.com/getindata/terraform-azurerm-atlantis
> docs: Add a new Azure deployment method

- runatlantis.io/docs/terraform-versions.md
- Add docs on terraform version constaints and specifiers
- Clarify the docs about setting the terraform version, especially since v0.21.0
- Companian to PR https://github.com/runatlantis/atlantis/pull/1776
> docs: terraform version usage after allowing additional `required_version` specifiers

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- Use correct image suffix for alpine/debian
- Used the `!` incorrectly. This will now tag the image as only `-alpine` when the `matrix.image_type` is `alpine`.
- Previous PR https://github.com/runatlantis/atlantis/pull/2773
- Previous PR https://github.com/runatlantis/atlantis/pull/2770
> Use correct image suffix for alpine/debian

- runatlantis.io/docs/faq.md
* It is now possible to use redis as a backend locking DB for Atlantis, this FAQ should be updated.
* The current FAQ is outdated after https://github.com/runatlantis/atlantis/pull/2491 was merged.
> docs(ha): wording update when using redis

- CHANGELOG.md
* Explicitly write the old Terraform versions removal as a breaking change in the CHANGELOG
* I've been surprised by this during upgrade to v0.21 
* https://github.com/runatlantis/atlantis/pull/2619
> docs(changelog): explicitly list the tf versions <1.x removal in the CHANGELOG.md

- .github/workflows/atlantis-image.yml
- add build-args to dev image
- the most recent prerelease tagged both the dev-debian and dev-alpine as the same image
- https://github.com/runatlantis/atlantis/pkgs/container/atlantis
- Previous PR https://github.com/runatlantis/atlantis/pull/2775
> bugfix: add missing build-args to dev image

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- runatlantis.io/docs/server-configuration.md
- Mention `--enable-regexp-cmd` requires the project `name` key
- Without the optional `name` key defined, the `--enable-regexp-cmd` with `atlantis plan -p .*` will return nothing.
- https://www.runatlantis.io/docs/server-configuration.html#enable-regexp-cmd
https://github.com/runatlantis/atlantis/blob/bab5c62451c405c8e93e492b33683c9541208069/server/events/project_command_builder.go#L494-L500
https://github.com/runatlantis/atlantis/blob/bab5c62451c405c8e93e492b33683c9541208069/server/core/config/valid/repo_cfg.go#L64-L70
> docs: Mention `--enable-regexp-cmd` requires the project `name` key

- server/controllers/events/events_controller.go
- server/controllers/events/events_controller_test.go
Aims to fix bug #2803 which causes Atlantis to ungracefully close a web request when a comment is deleted in a PR. 
A simple check to see if the "IsDeleted" property is set to true and return a 200 OK message if so. (ignored)
I've built the project locally with this change and confirm the issue is no longer present when testing in our dev environment. 
The bug causes Azure DevOps to disable the webhook connector when it sees a web request terminate ungracefully. Effectively bringing down the service until re-enabled.
closes #2803
Please let me know if anything else is needed and I'm happy to add - I haven't contributed to any projects this big before 😨
> Adding a check for deleted comments in AzureDevOps event handler

- testing/Dockerfile
- add `conftest` command in testing-image, not `conftest$version` command
Based on https://github.com/runatlantis/atlantis/pull/2807#discussion_r1051488180 discussion, we want to remove e2e ocontroller version specific conftest command like https://github.com/runatlantis/atlantis/blob/6a7f79e749a1604f54378e4920cf83c2888399ec/server/controllers/events/events_controller_e2e_test.go#L1366-L1372.
This version specific dependency is hard to upgrade conftest automatically.
To remove version dependency, I just add `conftest` comand. I will change e2e by using this command in the next PR.
- https://github.com/runatlantis/atlantis/issues/2638
- https://github.com/runatlantis/atlantis/pull/2807#discussion_r1051488180
> refactor: add conftest command into testing-image for refactoring e2e conftest ensure logic to upgrade conftest upgrading

- .circleci/config.yml
- .github/workflows/test.yml
- Makefile
- server/controllers/events/events_controller_e2e_test.go
- change testing-env image which contains `conftest` command
- https://github.com/runatlantis/atlantis/pull/2811 introduce it
- check e2e conftest ensure logic with `conftest` command, not `conftest$version` command.
Based on https://github.com/runatlantis/atlantis/pull/2807#discussion_r1051488180 discussion, we want to remove e2e controller version specific conftest command like https://github.com/runatlantis/atlantis/blob/6a7f79e749a1604f54378e4920cf83c2888399ec/server/controllers/events/events_controller_e2e_test.go#L1366-L1372.
This version specific dependency is hard to upgrade conftest automatically.
To remove version dependency, I want remove `conftest$version` command.
- https://github.com/runatlantis/atlantis/issues/2638
- …
> refactor: e2e test ensure conftest command to check conftest version is greater or equal to specific version

- server/events/markdown_renderer_test.go
- server/events/models/models.go
- server/events/models/models_test.go
- server/events/templates/policy_check_success_wrapped.tmpl
- Add `{{.PolicyCheckSummary}}` into tmpl
- fix PolicyCheckSummary extract regex
- original impl doesn't show output summary
- closes https://github.com/runatlantis/atlantis/issues/2756
> fix: Policy check summary not shown outside of "Show Output" details

- Dockerfile
- Dockerfile.dev
- server/controllers/events/events_controller_e2e_test.go
- testing/Dockerfile
update conftest to 0.37.0
latest and greatest
- https://github.com/open-policy-agent/conftest/releases/tag/v0.37.0
> chore(deps): update conftest to 0.37.0

- server/events/command/project_context.go
- server/events/command/scope_tags.go
- server/events/instrumented_project_command_runner.go
- server/events/project_command_context_builder.go
- server/metrics/scope.go
Added empty tags to metrics initialization to avoid errors when running commands.
Tried to hide the implementation behind the `ProjectScopeTags` so we can have an easy way to implement empty tags like this: 
```
projectTags := command.ProjectScopeTags{}
scope = metrics.SetScopeTags(scope.SubScope("project"), projectTags.Loadtags())
```
Instead of this:
```
scope = scope.SubScope("project")
scope = scope.Tagged(map[string]string{
"base_repo":         "",
"pr_number":         "",
"project":           "",
"project_path":      "",
"terraform_version": "",
"workspace":         "",
})
```
This should ensure that in the future if someone adds new tags to the `ProjectScopeTags` they still will be initialized empty while still can use the `SetProjectScopeTags` to add the values.
- This PR …
> bugfix: Initialize metrics with empty tags

- server/controllers/events/events_controller_e2e_test.go
- server/core/runtime/policy/conftest_client.go
- server/core/runtime/policy/conftest_client_test.go
- testing/Dockerfile
- use `conftest` command instead `conftest$version` command in the e2e test
- conftest_client try to find `conftest` command if version is not specified
- failed e2e test on the following PR. Because latest testing-env image contains conftest0.37.0, but e2e require conftest0.36.0.
- https://github.com/runatlantis/atlantis/pull/2844
- I will check after merge this PR
- update testing-image
- rebase and ci will succeed on https://github.com/runatlantis/atlantis/pull/2844
- I discussed to use conftest only in https://github.com/runatlantis/atlantis/pull/2844#issuecomment-1361664058.
- But users can customize conftest version on [PolicyCheck](https://github.com/runatlantis/atlantis/blob/9a38e354936fbf93282e4e934fa3439fc3bfd102/server/core/config/valid/policies.go#L18).
- So we need to …
> tests: e2e test to use conftest command instead version-specific command

- cmd/server.go
- runatlantis.io/docs/server-configuration.md
- server/controllers/events/events_controller_e2e_test.go
- server/core/terraform/mocks/mock_terraform_client.go
- server/core/terraform/terraform_client.go
- server/core/terraform/terraform_client_test.go
- server/events/project_command_builder.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/project_command_context_builder.go
- server/events/project_command_context_builder_test.go
- server/server.go
- server/user_config.go
- Move the TF version listing logic into `terraform_client.go`
- Add flag to enable or disable TF version listing & TF downloads
- Reuse tf download url
- Moved logic so it can leverage the existing `--tf-download-url` configuration option
- If unable to list TF versions, fall back to the previous exact version regex to extract the version.
From #2701, this does **not** address the `os.Exit()` calls in https://github.com/warrensbox/terraform-switcher/blob/107631ffa4108d172909149d295c64c08cbedf00/lib/list_versions.go#L109-L139, though it does equip the code to handle it if an upstream change is made to return errors rather than exiting.
- Closes #2701
> feat: Add flag to disable downloading tf for airgapped environments

- go.mod
- go.sum
- server/server.go
remove urfave/cli dependency
I tried to upgrade urfave/cli for https://github.com/runatlantis/atlantis/pull/2858, but not needed by following investigation.
This library is introduced for cli.NewApp, but currently atlantis use cobra, so `cli.NewExitError` has no meanings
- In the past, cli.NewApp is used https://github.com/runatlantis/atlantis/blob/5f47524655213ec829f9c81a85cd2cc38ee6a349/main.go#L51
- at that time, `cli.NewExitError` has effect to handling exit code https://github.com/runatlantis/atlantis/commit/5f47524655213ec829f9c81a85cd2cc38ee6a349
- But currently we use cobra, not cli.App
- https://github.com/runatlantis/atlantis/blob/bb6642c9136a72ee02459b55d5849bd348b4eb87/main.go
So `cli.NewExitError` has no meaning.
- cli.App used commit …
> chore(deps): remove urfave/cli

- .github/renovate.json5
- change renovate setting to use node LTS version for `cimg/node` image which is circleci node image
https://github.com/runatlantis/atlantis/pull/2862 try to upgrade cim/node image 19 with is not LTS version
- debug https://github.com/krrrr38/atlantis/pull/45/files
- closes https://github.com/runatlantis/atlantis/pull/2862
> fix: renovate upgrade cimg/node with LTS version

- server/events/comment_parser.go
- server/events/comment_parser_test.go
- Since pull #2805 makes the bot command customizable, this PR updates all the help text
to use the configured executable instead of always showing `atlantis`.
- If the executable is not Atlantis it's confusing for the help text to show atlantis as the executable.
- #2805
> fix(command_parser): help text to use executable command

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/using-atlantis.md
- server/controllers/events/events_controller_e2e_test.go
- server/controllers/events/testfixtures/test-repos/simple/exp-output-allow-command-unknown-import.txt
- server/events/command/name.go
- server/events/command/name_test.go
- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/server.go
- server/user_config.go
- server/user_config_test.go
- add `--allow-commands` whitelist server configuration
- This flag checks comment_parser and `version,plan,apply,unlock,approve_policies` is default.
- `--disable-apply` become deprecated. if set true, server remove `apply` command from `--allow-commands`.
- for backward compatibility, if `--enable-policy-check` is true,  `approve_policies` is allowd in `--allow-commands`.
- Users may not want to introduce a particular command such as `import`.
- Future commands may be added but required by `--allow-commands`.
- I added [import command](https://github.com/runatlantis/atlantis/pull/2783).
- Closes https://github.com/runatlantis/atlantis/issues/2871
> feat: --allow-commands restricts available atlantis commands

- docker-base/Dockerfile.alpine
- docker-base/Dockerfile.debian
- Updates `gosu`, `git-lfs` to the latest version, along with `curl`, `bash` in alpine, and the debian base image.
- `gosu` and `git-lfs` contains many CVEs, and haven't been update in a while. The other changes are more house keeping to keep them up to date as well.
- [gosu releases](https://github.com/tianon/gosu/releases)
- [git-lfs releases](https://github.com/git-lfs/git-lfs/releases)
- https://hub.docker.com/r/amd64/debian/
- Relates to https://github.com/runatlantis/atlantis/issues/2883#issuecomment-1367241025
> chore(deps): atlantis-base: Update gosu and git-lfs

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- docs: add yaml anchors
- Due to strict YAML checking and lack of YAML anchor experience, many users do not know how to DRY up the atlantis.yaml repo configuration
- These docs will help keep user atlantis.yaml files cleaner
- Relates to https://github.com/runatlantis/atlantis/issues/1553
- Thanks to https://github.com/runatlantis/atlantis/issues/260#issuecomment-637369952
> docs: add yaml anchors

- runatlantis.io/docs/server-configuration.md
Syncing doc environment variable name with the current code, as seen here (2022-12-30): https://github.com/demetriusmoro/atlantis/blob/main/cmd/server.go#L178
- Current var name in the doc (wrong): `ATLANTIS_AZUREDEVOPS_BASIC_AUTH`
- Current var name in code (correct): `ATLANTIS_AZUREDEVOPS_WEBHOOK_PASSWORD`
Fixing a variable name typo in the docs, to make it same than the actual code that reads this parameter.
The current variable name in the docs is not an actual valid parameter, people reading just the docs will get confused.
Doesn't actually have test, its is a doc-only related fix, the related code works as expected.
- Code that actually reads the parameter: https://github.com/demetriusmoro/atlantis/blob/main/cmd/server.go
- Direct link to the variable declaration: …
> fix: syncing doc variable name with current code

- CHANGELOG.md
- kustomize/bundle.yaml
- main.go
atlantis version has been changed to v0.22.0
atlantis version is not matching with release version and tests are failing when building custom image using atlantis as base image due to image and atlantis version mismatch.
- closes  #2909
- previous pr https://github.com/runatlantis/atlantis/pull/2734
> Release 0.22.0

- server/controllers/events/events_controller_e2e_test.go
- server/events/command_runner_test.go
- server/events/plan_command_runner.go
- server/server.go
- Implements a missing 'if' conditional and adds additional tests 
- The `dismissApprovalOnPlan` option has been executed without option to turn it off. 
- This only has been tested by implementing new unit tests
- Closes #2911
> fix(discardApprovalOnPlan): add missing conditional and tests

- .github/workflows/release.yml
- Fix bump-homebrew-action token
- use GitHub action to bump formula
- https://github.com/runatlantis/atlantis/actions/runs/3824537235/jobs/6506875885
> Disable bump-homebrew-action

- README.md
update the invite link for slack
old link expired
sent it to few people and is working
> chore: updating slack invite link

- server/events/command/project_result_test.go
- server/events/markdown_renderer_test.go
- server/events/models/models.go
At Grafana Labs we have been using Atlantis for several months, and a typical PR could affect over 10 to 20 different projects; these PRs happen several times a day, meaning Atlantis reports back plan summaries very often.
While looking at how to override the templates to better accommodate them to our needs, I've found that the `*PlanSuccess.Summary` method could be made much faster by simply extracting the compilation of the regexes outside the method instead of compiling them every time.
As described above we rely heavily on Atlantis giving us faster feedback. By improving the performance in speed and memory allocations the feedback cycle will be faster and also we will be reducing our carbon footprint.
I first introduced a benchmark for this method, and ran the tests and benchmark …
> Improve plan summary performance

- runatlantis.io/docs/server-configuration.md
As the atlantis user is restricted to the home directory of atlantis (`/home/atlantis`), setting the `--data-dir` flag to another path will result in a permission denied error. 
I've updated the documentation to be more explicit on this common pitfall.
This is a common made mistake as we nowhere document how restricted the atlantis user is,[ I had to look at the docker-base](https://github.com/runatlantis/atlantis/blob/main/docker-base/Dockerfile.alpine#L7-L18) to understand why, what and where the atlantis user permissions were applied.
- Closes #2903 
- Previous PR https://github.com/runatlantis/atlantis/pull/2908
> docs: Explicit restrictions of atlantis user apply to the --data-dir flag

- .github/renovate.json5
enable renovate gomodUpdateImportPaths option.
> If the user has enabled the option gomodUpdateImportPaths in the [postUpdateOptions](https://docs.renovatebot.com/configuration-options/#postupdateoptions) array, then Renovate uses [mod](https://github.com/marwan-at-work/mod) to update import paths on major updates, which can update any Go source file
https://docs.renovatebot.com/golang/
renovate major version up PR doesn't consider removing old version.
https://github.com/runatlantis/atlantis/pull/2928
- https://github.com/runatlantis/atlantis/pull/2928
> chore: enable renovate gomodUpdateImportPaths

- runatlantis.io/docs/deployment.md
- This pull request proposes adding a new way to deploy Atlantis on Google Cloud using Compute Engine
- The Terraform module features the creation of a Container-Optimized VM running Atlantis in a Docker container. The VM is managed by a Managed Instance Group and a stateful GCE Persistent Disk is attached to the VM. In addition to this, an External HTTPS Load Balancer is created that services the traffic destined for Atlantis to handle.
- As we're actively maintaining this production-ready Google Cloud Atlantis Compute Engine module it seemed logical to use to propose this deployment option to the Atlantis documentation.
- When proposing the use of Atlantis to many clients, we often receive feedback that a Google Kubernetes Engine (GKE) cluster, which is the only featured way to run …
> docs: add Google Cloud module to deployment

- runatlantis.io/docs/server-side-repo-config.md
Addin `api-secret` key to docs
missing config key for the API
Tested locally
#997
> docs: Add `api-secret` flag

- .github/workflows/renovate-config.yml
- .github/workflows/test.yml
use actions/checkout@v3 instead actions/checkout@v3.3.0.
Both `actions/checkout@v3` and `actions/checkout@v3.3.0` are existed in this repo.
minor version update is redundant like https://github.com/runatlantis/atlantis/pull/2943.
```
✘╹◡╹✘☆  ag uses: .github | perl -pe 's/.*uses: (.*)/$1/' | sort -u
actions/checkout@v3
actions/checkout@v3.3.0
actions/setup-go@v3
actions/setup-node@v3
actions/stale@v7
docker/build-push-action@v3
docker/login-action@v2
docker/metadata-action@v4
docker/setup-buildx-action@v2
docker/setup-qemu-action@v2
goreleaser/goreleaser-action@v4
mislav/bump-homebrew-formula-action@v2
reviewdog/action-golangci-lint@v2
```
after 
```
✘╹◡╹✘☆  ag uses: .github | perl -pe 's/.*uses: (.*)/$1/' | sort -u | grep checkout
actions/checkout@v3
```
- …
> chore: use actions/checkout@v3

- Dockerfile
- Bump base to 2023-01-09
- Latest dependency updates
- Relates to https://github.com/runatlantis/atlantis/pull/2896
- Relates to https://github.com/runatlantis/atlantis/pull/2954
- https://github.com/runatlantis/atlantis/pkgs/container/atlantis-base/62508117?tag=2023.01.09
> docker: bump base to 2023-01-09

- server/events/approve_policies_command_runner_test.go
Add tests to verify the owner checking in `ApprovePoliciesCommandRunner`
I'm trying to add support for checking group membership in #2953, but the current behaviour is not tested so making changes is risky.
Tested with `make test` - this PR only adds tests and does not change the production code.
- Dependency of #2953
> Add ApprovePoliciesCommandRunner owner tests

- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/server-side-repo-config.md
- server/controllers/events/events_controller_e2e_test.go
- server/controllers/github_app_controller.go
- server/core/config/raw/policies.go
- server/core/config/raw/policies_test.go
- server/core/config/valid/policies.go
- server/events/approve_policies_command_runner.go
- server/events/approve_policies_command_runner_test.go
- server/events/command_runner_test.go
- server/server.go
In addition to a list of usernames, support checking team membership when validating a particular user can approve policy violations. The new code path is only executed if team membership is configured, so it's a low impact change for existing installations.
This also documents a missing GitHub app permission - `GetTeamNamesForUser` was added in #1694 and requires the `members:read` scope, I had to add that to my GitHub app to test this feature.
~I need to make some doc updates for this, but wanted to get some feedback on the code first.~ docs updated
Maintaining a list of users by hand is a lot of toil for larger orgs.
- Tested against Github using a real GitHub app, org, and repo. ([gif](https://user-images.githubusercontent.com/398706/211519646-aaae07d1-7adb-4e26-a4ea-57b4012fe15a.gif)) …
> feat: Support team owners for conftest policies

- server/events/command_runner.go
- server/events/command_runner_test.go
- As described in https://github.com/runatlantis/atlantis/issues/1202, it can happen that atlantis keeps lock open when a PR is closed mid-planning.
- This PR allows to comment "atlantis unlock" on closed PRs to bulk delete any leftover locks.
- Ideally atlantis would signal any in-progress plans to gracefully terminate when a PR is closed before announcing that a PR has been closed, but this seems like a more complicated change.
- https://github.com/runatlantis/atlantis/issues/1202
> fix: allow to unlock closed PRs

- .circleci/config.yml
- .github/workflows/test.yml
- Makefile
- use testing-env:latest
- resolve chicken and egg issue wirh conftest
- reduce number of prs to run tests
- if an issue arrises, we can always go back to a date stamp pin
- see passing tests below
- this merge creates a new testing env https://github.com/runatlantis/atlantis/pull/2964
- this pr fails until the testing-env is bumped https://github.com/runatlantis/atlantis/pull/2963
> chore(deps): use testing-env:latest

- Dockerfile
- Bump atlantis-base:2023-01-11
- latest base image contains updated packages and updated base image FROM for both Alpine and debian
- renovatebot detects it but does not open a pr even when forced to open a pr using the dependency dashboard
- built the new base
- previous pr https://github.com/runatlantis/atlantis/pull/2965
- previous pr https://github.com/runatlantis/atlantis/pull/2962
- previous pr https://github.com/runatlantis/atlantis/pull/2961
> Bump atlantis-base:2023-01-11

- server/controllers/events/testfixtures/test-repos/import-workspace/exp-output-import-dir1-ops-dummy1.txt
- server/controllers/events/testfixtures/test-repos/import-workspace/exp-output-import-dir1-ops-dummy2.txt
- server/controllers/events/testfixtures/test-repos/import-workspace/exp-output-plan.txt
- fix `atlantis import` test
- Previous PR ran tests but not e2e tests. The e2e tests failed after the PR merge.
https://github.com/runatlantis/atlantis/blob/c77149396ac94c9836cbbdc07196d6dac3585530/server/controllers/events/events_controller_e2e_test.go#L449-L463
- Previous PR https://github.com/runatlantis/atlantis/pull/2937
- Bad run https://github.com/runatlantis/atlantis/actions/runs/3897759236/jobs/6655758097
- https://github.com/runatlantis/atlantis/tree/main/server/controllers/events/testfixtures/test-repos/import-workspace
> chore(test): fix `atlantis import` test

- server/events/instrumented_project_command_runner.go
Fixes approve policies calling apply runner.
closes #2974
> fix: Fix instrumented approve policies calling apply

- .github/renovate.json5
- feat: additional renovatebot configurations
- autoclose if no dependencies using `dependencydashboardautoclose`
- set pr hourly limit to 1 using `prhourlylimit` to avoid e2e failures
- manage yarn dependency updates using `lockfilemaintenance`
- current issue dashboard doesn't autodetect the `yarn.lock` yet
- enable vulnerability alerts using `vulnerabilityalerts`
- remove `prConcurrentLimit` since it defaults to 10 and we never hit it
- add a suffix to include the `packageFile` using the `commitMessageSuffix`
- This will add the package file name to the commit and the PR title
```bash
docker run \
-v $(pwd)/.github/renovate.json5:/usr/src/app/renovate.json5 \
--env LOG_LEVEL=debug \
--rm -it \
renovate/renovate renovate-config-validator
```
returns the same thing as the gh pr check
``` …
```
> feat: additional renovatebot configurations

- .github/workflows/codeql.yml
- testdrive/utils.go
- Reduce number of vulnerabilities introduced by code changes
- Starts https://github.com/runatlantis/atlantis/issues/2884
- More info https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
- Full list of advisories generated https://github.com/runatlantis/atlantis/security/code-scanning?query=pr%3A2879+tool%3ACodeQL+is%3Aopen
> feat(build): add vulnerability codeql scanning

- runatlantis.io/docs/server-configuration.md
missing doc for flag
The docs did not mention the relationship between `allowed_regexp_prefixes` in the `atlantis.yaml` file and the server config flag `enable-regexp-cmd`
https://www.runatlantis.io/docs/server-configuration.html#enable-regexp-cmd
> docs: Add clarification to `enable-regex-cmp` flag

- docker-base/Dockerfile.alpine
- chore(docker): bump-git-2.39
- resolve security issue
Waiting for git 2.39
```
$ docker run -it alpine:3.17 sh -c "apk update && apk info git"
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
v3.17.1-83-g24a1fb849a [https://dl-cdn.alpinelinux.org/alpine/v3.17/main]
v3.17.1-86-g720cea6326 [https://dl-cdn.alpinelinux.org/alpine/v3.17/community]
OK: 17684 distinct packages available
git-2.38.3-r1 description:
Distributed version control system
git-2.38.3-r1 webpage:
https://www.git-scm.com/
git-2.38.3-r1 installed size:
6284 KiB
```
- https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/
- https://gitlab.alpinelinux.org/alpine/aports/-/commit/2cee05a753c827cd5 …
> chore(docker): bump-git-2.39

- server/events/commit_status_updater.go
- server/events/commit_status_updater_test.go
- server/events/models/models.go
- server/events/models/models_test.go
- Add `PlanSuccess.DiffSummary` which returns only diff summary.
- use it on the pr status updater
`PlanSuccess.Summary` returns outside diff message, too. In the PR plan status doesn't need that information.
- closes https://github.com/runatlantis/atlantis/issues/3009
> fix: PR status summary should remove Note: Objects have changed outside of Terraform

- server/server.go
fix markdown renderer configuration order
- Even if disableApply, comment contains `To apply this plan, comment: atlantis apply -d .`.
- https://github.com/krrrr38/atlantis-debug/pull/9
- https://github.com/runatlantis/atlantis/discussions/3014#discussioncomment-4728231
> fix: markdown renderer use invalid disableApply flag with disableMarkdownFolding

- .github/workflows/atlantis-base.yml
- .github/workflows/atlantis-image.yml
- pin buildkit to v0.10.6
- fix intermittent ghcr push failures
- I have not tested my changes
- I used the workaround provided by maintainers and hoping for the best
- closes https://github.com/runatlantis/atlantis/issues/3017
- implements https://github.com/docker/build-push-action/issues/761#issuecomment-1383822381
> build(docker): fix intermittent ghcr push failures

- .circleci/config.yml
- .github/workflows/test.yml
- rm test job from circleci
- add `make check-fmt` to existing gha test job
- Reduce reliance on circleci
- `make check-lint` is already done by reviewdog so no need to do that in both gha and circleci. This is why `make check-lint` wasn't added to the PR.
- Similar to PR https://github.com/runatlantis/atlantis/pull/1781
> chore(test): remove redundant test job from circleci

- .circleci/config.yml
- remove unused `test` reference
- enable e2e again
```
e2e: requires job "test" but "test" is not part of this workflow.
The following jobs are unreachable: e2e
```
- Error shown here https://app.circleci.com/pipelines/github/runatlantis/atlantis?branch=labeler
- Previous PR that removed `test` https://github.com/runatlantis/atlantis/pull/3026
> fix(actions): remove unused `test` reference to enable e2e

- .github/workflows/labeler.yml
- change to pull_request_target per docs
- fix labeler error
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```
- mention of missing perm https://github.com/actions/labeler/issues/12#issuecomment-1095272652
- mention of pull_request_target https://github.com/actions/labeler/issues/136#issuecomment-1357839196
- should fix error in https://github.com/runatlantis/atlantis/actions/runs/3986925127/jobs/6837118127
> fix(actions): set labeler to use correct `on` event

- runatlantis.io/docs/custom-workflows.md
Fixes a misformatted table in the docs under `docs/custom-workflows.html#multiple-environment-variables-multienv-command`. 
- The text in the description column was broken over two rows, while the rest of the docs accepts long lines in one cell that wrap when displayed.
- The information on the fixed format expected appears to have been put into the table by mistake.
I have tested the changes by running `yarn run website:dev` locally. Screenshots of before/after:
Before:
After: 
This is my first PR for this repo, so please let me know if there are any issues, or if I have misunderstood anything.
> docs: fix table formating for multienv

- .circleci/config.yml
- .github/workflows/test.yml
- move website link checker to GitHub actions 
- move off of circleci
- #3028 
- #3026 
- #1781
> feat(actions): website link check

- .github/workflows/release.yml
- kustomize/bundle.yaml
- main.go
- Set version based on github release tag
- Set `kustomize` version to latest
- Set `rlcp` explicitly in `.goreleaser.yaml`
- Prevent having to do manual PRs right before a release by passing in the tag version to goreleaser automatically
- set `kustomize` to our stable version `latest` to avoid manual bumps
- set `rlcp` to avoid deprecation for december 2023
- Closes #2912 
- https://goreleaser.com/cookbooks/using-main.version/
- https://goreleaser.com/deprecations/#archivesrlcp
- [action run](https://github.com/nitrocode/atlantis/actions/runs/4011248679/jobs/6888629922) for my fork version of v0.22.9000 shows it passes the tag to the version as described in goreleaser docs
Validate goreleaser config
```shell
✗ goreleaser check
• loading config file …
```
> feat(release): version based on github release tag

- .github/workflows/atlantis-image.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile
- main.go
- Set version based on github release tag in docker
- Missing commit from previous pr to disable signing
- Used logger instead of fmt
- Quoted strings in Dockerfile
- add `workflow_dispatch` to `release` action
- goreleaser's `github` config is omitted
- Set version in docker container otherwise it will default to `dev` instead of the tag passed to it
- Disable signing since there is a missing GPG key (added TODO)
- Using logger so log entry only shows up as a debug message
- Dockerfile quotes to resolve hadolint issues
- `release` action can now be run manually to correct a broken tag (like the current one) without having to create a brand new release
- goreleaser now implicitly grabs the github info so if a user forks the repo, not only is there image built and uploaded on their fork, …
> fix(docker): Set version based on release tag, revert gorelease signing

- docker-entrypoint.sh
Restore functionality of calling the container with commands starting `atlantis`
Prior to v0.22.0 the container could be run with the command `atlantis server`. However this was broken by #2770:
```
Error: unknown command "atlantis" for "atlantis"
```
This PR reverts to previous functionality and matches the comment. Following calls all work again:
```sh
docker run atlantis server
docker run atlantis --help
docker run atlantis atlantis server
docker run atlantis atlantis --help
```
```sh
hadolint Dockerfile
```
produced no output but I didn't modify that file.
- related to https://github.com/runatlantis/atlantis/pull/2770
> fix(docker): docker-entrypoint when called with atlantis

- runatlantis.io/docs/server-configuration.md
Add docs for environment variable variant for autoplan config options
This should be a valid way to configure Atlantis, and the docs typically reflect both variants
> docs: add env var variants for autoplan config options

- go.mod
- go.sum
- server/core/config/valid/global_cfg.go
- server/core/redis/redis.go
- update module github.com/go-redis/redis/v9 to v9.0.1 which is moved into https://github.com/redis/go-redis
- https://github.com/runatlantis/atlantis/pull/3045
- closes https://github.com/runatlantis/atlantis/pull/3045
- https://github.com/redis/go-redis
> fix(deps): update module github.com/go-redis/redis/v9 to v9.0.1

- server/controllers/events/events_controller_e2e_test.go
- server/logging/log.go
- server/server.go
To suppress uber-go/tally logs which are not structured logs.
- discard `log` package logging
- it's enough to logs which are output on atlantis package.
uber-go/tally put non-structured logs using `log` package`.
https://github.com/uber-go/tally/commit/c347bbf48d7998560fa8a821d08ea5b425deda3e#diff-f65e5374d781f61272558959f338307fc0e51e9f59c0c75dc76d03dfd9dd2010R253
Then server output json and non-json logs.
https://github.com/runatlantis/atlantis/actions/runs/4051074308/jobs/6969044735
- begore
```
✘╹◡╹✘☆  go install && atlantis server --log-level info
2023/01/31 14:40:08 counters: 8, gauges: 25, histograms: 0
2023/01/31 14:40:09 counters: 8, gauges: 25, histograms: 0
{"level":"info","ts":"2023-01-31T14:40:09.032+0900","caller":"server/server.go:439","msg":"Utilizing BoltDB","json":{}} …
```
> feat: suppress log package logging

- go.mod
- go.sum
- server/core/config/valid/global_cfg.go
- server/events/comment_parser.go
- server/utils/slices.go
[chore: remove x package](https://github.com/runatlantis/atlantis/commit/cbb97e53543d3c3733456717a4d03d3123d31a8a)
for easy maintain packages https://github.com/runatlantis/atlantis/pull/3080#issuecomment-1409854485
- https://github.com/runatlantis/atlantis/pull/3080#issuecomment-1409854485
- https://github.com/golang/go/issues/57433
> chore: remove x package

- server/events/templates/import_success_wrapped.tmpl
- server/events/templates/state_rm_success_wrapped.tmpl
`server/events/templates/import_success_wrapped.tmpl` and `server/events/templates/state_rm_success_wrapped.tmpl` wrap templates are not processed correctly (others are correct like followings).
```
✘╹◡╹✘☆  ag -A1 '<details><summary>Show Output</summary>' server/events/templates/
server/events/templates/import_success_wrapped.tmpl
2:<details><summary>Show Output</summary>
3-```diff
server/events/templates/policy_check_success_wrapped.tmpl
2:<details><summary>Show Output</summary>
3-
server/events/templates/wrapped_err.tmpl
3:<details><summary>Show Output</summary>
4-
server/events/templates/plan_success_wrapped.tmpl
2:<details><summary>Show Output</summary>
3-
server/events/templates/state_rm_success_wrapped.tmpl
2:<details><summary>Show Output</summary>
3-```diff …
```
> fix import/state rm success wrapped template

- .circleci/config.yml
- Dockerfile
- Makefile
- e2e/go.mod
- go.mod
- testing/Dockerfile
- go1.20
- mark as draft PR as the corresponding golang images might not be available yet
- go1.20 release notes, https://tip.golang.org/doc/go1.20
> deps: bump to go1.20

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- add missing required `dir` to projects
- example of [DRYing up the project config](https://www.runatlantis.io/docs/repo-level-atlantis-yaml.html#example-of-drying-up-projects-using-yaml-anchors) is missing the `dir` value
- provided example gave the error `parsing atlantis.yaml: projects: (0: (dir: cannot be blank.).).` , with the extra `dir` value it works
- none
> fix(docs): Add missing dir to DRY repo level atlantis.yaml projects key 

- server/events/vcs/gitlab_client.go
- check for ci_still_running
- correct detailed merge status check
- closes https://github.com/runatlantis/atlantis/issues/3065
- introduced by https://github.com/runatlantis/atlantis/pull/2960
> bugfix(gitlab): correct detailed merge status check

- cmd/server.go
- go.mod
- go.sum
- server/events/modules.go
- server/events/project_finder.go
- Swap `moby` with `patternmatcher`
- Remove deprecated `fileutils.NewPatternMatcher` for supported library
- https://github.com/moby/moby/blob/c758d8b0406da2c3705c6efbdcdb6e920ee3ab75/pkg/fileutils/deprecated.go#L24-L28
- Closes https://github.com/runatlantis/atlantis/pull/3104
- Slowly implements https://github.com/runatlantis/atlantis/issues/2795
> chore(dependency): Swap `moby` with `patternmatcher`

- Dockerfile
- download transitive dependencies
- faster docker builds due to downloading dependencies instead of compiling them
- builds are usually 26 minutes
- https://github.com/montanaflynn/golang-docker-cache
- https://github.com/golang/go/issues/27719
> feat(docker): download transitive dependencies

- .github/renovate.json5
- .github/workflows/codeql-required.yml
- .github/workflows/lint-required.yml
- .github/workflows/test-required.yml
```
runner / golangci-lint
runner / revive
runner / errcheck
runner / gotest
Analyze (go)
Analyze (javascript)
```
Any others?
- once the repo owner sets required checks, automerge can be enabled for renovatebot pra
- this will save maintainer time and get security/dependency updates in much sooner
- closes #3112
- https://docs.renovatebot.com/configuration-options/#automerge
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
> feat(renovatebot): automerge enabled

- server/core/runtime/post_workflow_hook_runner.go
- server/core/runtime/pre_workflow_hook_runner.go
- Fixes workflow output not sending output for ws channel.
- Turns out if we set the first message as closed the Handle will close the channel before we send any message as can be seem [here](https://github.com/runatlantis/atlantis/blob/main/server/jobs/project_command_output_handler.go#L134), we need to have at least 2 messages one with our output and another one to close the channel.
- closes #3008
> fix(workflow-hook): pre/post hook not sending output due to invalid key

- server/events/comment_parser.go
- server/events/comment_parser_test.go
- server/utils/spellcheck.go
- server/utils/spellcheck_test.go
Add spellcheck for executable name
Sometimes users misspell `atlantis` word and are waiting for their PR to be applied. Decided to go with [terraform approach](https://github.com/hashicorp/terraform/tree/fc8fed0047e98b430f648c3659d22be6f8d52642/internal/didyoumean) and use https://github.com/agext/levenshtein 
Added unit tests and tested on my local atlantis server:
https://github.com/bighead-io/applications/pull/5#issuecomment-1436949866
(running atlantis under my personal user here)
Closes https://github.com/runatlantis/atlantis/issues/3069
> feat(executable-name): Add check for misspelled comment command

- go.mod
- server/core/terraform/terraform_client.go
- server/core/terraform/terraform_client_test.go
- Use go-version from hashicorp for version checking instead of semver
- add more test cases (I am just duplicating the existing code, feel free to refactor it/ give suggestion)
Currently there is a bug by setting "required_version = "\~> 1.0" " in version.tf, atlantis will choose 1.0.13 instead of 1.3.9
In terraform "\~>" allows only the rightmost version component to increment. (see reference below) 
- closes https://github.com/runatlantis/atlantis/issues/2806
- https://developer.hashicorp.com/terraform/language/expressions/version-constraints#-3
> fix: Use `hashicorp/go-version` to resolve `~> 1.0` to `1.x` instead of `1.0.x`

- Makefile
- main.go
- When new versions are built, we will be able to see the exact commit hash on the pod/ec2 where atlantis is deployed as well as its user interface
- This will help a lot if people use the `dev` image tag which currently does not show its short git sha in the tag itself (except in the image labels)
```bash
✗ go build -v -o atlantis .
✗ ./atlantis version
atlantis dev (commit: none) (build date: unknown)
```
With appropriate inputs that will come from goreleaser and in the Dockerfile
```
✗ go build -trimpath -ldflags "-s -w -X 'main.version=v0.99.0' -X 'main.commit=db70ffe' -X 'main.date=2022-02-24'" -v -o atlantis
✗ ./atlantis version
atlantis v0.99.0 (commit: db70ffe) (build date: 2022-02-24)
```
- Previous PR https://github.com/runatlantis/atlantis/pull/3051
> feat: Include commit and date in version

- .github/workflows/atlantis-image.yml
- ~enable build + push on pr on a condition~
- run condition:
- currently we only build when atlantis-image workflow is modified by a pr
- should we always run atlantis-image but only build when necessary?
- ideal
- build condition:
- at the moment, we always build when the run condition is met
- we could build only when there is a pr label present
- push condition:
- specific github pr label? - `push-image-from-pr`
- always? if we're building anyway, why not just push a specific pr tag up?
- slash command from maintainer?
- why build and NOT push ?
- Maybe only to verify changes to atlantis-image.yml continue to work.
- push repo:
- doesn't allow non-admins to push to runatlantis/atlantis ghcr
- testing if it will push to fork
- Output after merging PR #3159 
```
atlantis dev (commit: …
```
> feat(build): add new sha ghrc docker tags using docker/metadata-action

- main.go
- use shorter commit sha in version output
- The full commit sha is too long. The first 7 chars is unique enough.
```
✗ go build -v -ldflags "-X 'main.commit=53e9e5880b0c662192d414cc0b455d8188051b99'" -o atlantis . && ./atlantis version
atlantis dev (commit: 53e9e58) (build date: unknown)
✗ go build -v -o atlantis . && ./atlantis version
atlantis dev (commit: none) (build date: unknown)
```
- Previous PR #3159
> fix: use shorter commit sha in version output

- .github/workflows/atlantis-image.yml
- push image to repo name without org
- pushing to the org/repo causes an `insufficient_scope: authorization failed` error
- previously wasn't caught since I was skipping push in my tests...
Current
```
runatlantis/atlantis:pr-3164-debian
runatlantis/atlantis:dev-debian-54859c6
```
Before and currently proposed
```
atlantis:pr-3164-debian
atlantis:dev-debian-54859c6
```
- This was previously working without the org so this is reverting that one portion.
- Previous PR #3121
> fix: push image to repo name without org

- .github/workflows/atlantis-image.yml
- push to full ghcr repo name
- The tag requires the full ghcr path
Previously when working
https://github.com/runatlantis/atlantis/actions/runs/4268268678/jobs/7430636285
```
--tag ghcr.io/runatlantis/atlantis:dev
--tag ghcr.io/runatlantis/atlantis:dev-alpine
```
Currently broken
https://github.com/runatlantis/atlantis/actions/runs/4271736874/jobs/7436413322
```
--tag atlantis:dev
--tag atlantis:dev-alpine
```
This PR will bring back the previously working route
N/A
- Previous PR #3164 
- Previous PR #3121
> fix: push to full ghcr repo name

- runatlantis.io/docs/server-configuration.md
- add note of autoplan modules limitation
- The original author that contributed does not use a per repo configuration file and the reviewers (like myself) missed it when approving the PR.
- For now, we can document the limitation and remove it once a fix is contributed.
N/A
- Related to issue https://github.com/runatlantis/atlantis/issues/3122
- Related to PR https://github.com/runatlantis/atlantis/pull/2507
> chore(docs): add note of autoplan modules limitation

- runatlantis.io/docs/server-configuration.md
- remove deprecated flags from docs
- prepare for future removal of deprecated flags
N/A
- e.g. https://www.runatlantis.io/docs/server-configuration.html#allow-repo-config
> chore(docs): remove deprecated flags from docs

- .github/workflows/atlantis-image.yml
- add missing description to multiarch images
- Currently the description is missing
- See "about this version" under [dev-alpine-f7f35ce](https://github.com/runatlantis/atlantis/pkgs/container/atlantis/73249532?tag=dev-alpine-f7f35ce) tag
- This is the recommended change from [github](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images)
N/A
- https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images
- https://github.com/runatlantis/atlantis/pkgs/container/atlantis/73249532?tag=dev-alpine-f7f35ce
- https://github.com/docker/build-push-action/issues/447
> fix: add missing description to multiarch images

- server/events/working_dir.go
- omit checkout depth if it is zero
- git 2.32.0 does not like `--depth=0`, we use git 2.39.1
- in this PR, we omit the depth if the depth is zero which checks out all the commits in the branch
- closes https://github.com/runatlantis/atlantis/pull/3184
- closes #3183
- previous pr #2758 
- https://github.com/git/git/blob/master/Documentation/RelNotes/2.32.0.txt#L109
> fix(clone): omit checkout depth if it is zero

- server/events/working_dir.go
- omit checkout depth if it is zero
- git 2.32.0 does not like `--depth=0`, we use git 2.39.1
- in this PR, we omit the depth if the depth is zero which checks out all the commits in the branch
- attempts to close #3183
- previous pr #3185
- previous pr #2758 
- https://github.com/git/git/blob/master/Documentation/RelNotes/2.32.0.txt#L109
> fix(clone): omit checkout depth if it is zero for `git fetch`

- server/jobs/project_command_output_handler_test.go
Fix two race conditions in TestProjectCommandOutputHandler
- use buffered channels
- add missing wg.Wait()
The test github.com/runatlantis/atlantis/server/jobs , in TestProjectCommandOutputHandler, sometimes times out.
- closes #3193
> test(command-output): stabilize server jobs test

- runatlantis.io/docs/using-atlantis.md
Change `-d project1` to `-p project1` in docs about various atlantis commands.
The docs appear to incorrectly use `-d project1` while consistently documenting the actual option as being `-p`.
> docs(using-atlantis): correct usage of -p for projects

- .github/workflows/stale.yml
- close stale issues after 2 months of inactivity by reducing current 180 days after 31 days stale to 31 days after 31 days stale
- more reasonable setting given the number of abandoned prs and issues
N/A
- see prs and number of older issues
> fix: close stale issues after 2 months of inactivity

- .github/renovate.json5
- feat: schedule renovate daily
- prevent having to check off the updates in the renovate dashboard to open prs. This will hopefully open the prs every day
n/a
- https://docs.renovatebot.com/presets-schedule/#scheduledaily
- https://github.com/runatlantis/atlantis/issues/2818
> feat: schedule renovate daily

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- server/events/vcs/testdata/github-branch-protection-require-linear-history.json
Account for branch protection rule "Require Linear History" when choosing merge method
When repo config allows merge commits:
But branch protection rules requires linear history (aka banning merge commits):
Current logic will always pick `merge` method by default. This PR fixes that.
- Closes #1176
> fix: allow `Require Linear History` when selecting merge method

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
To address #3210 , poll [the Gitlab `/changes` endpoint](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-merge-request-changes) until `changes_count` is no longer an empty string.  `changes_count` is one of several fields that changes type when Gitlab's eventual consistency resolves and merge request changes are returned in the response.  It's the most relevant choice of field for #3210 which is concerned with `Client.GetModifiedFiles()`. 
Recent backwards-incompatible changes in Gitlab's API break the workflow in Atlantis where the Gitlab client expects accurate values to be available immediately.  Gitlab is [documenting this change in behavior](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/115210) and not planning on reverting it, so Atlantis must adapt. …
> Poll Gitlab until changes are available

- server/events/vcs/gh_app_creds_rotator_test.go
- server/events/vcs/git_cred_writer_test.go
Tests no longer write to .gitconfig and .git-credentials in $HOME.
Tests should not write to git configuration files directly in the user's home directory.
Rreproduction steps to see the problem (fails without this patch):
```
touch $HOME/.gitconfig $HOME/.git-credentials
sudo chattr -i $HOME/.gitconfig $HOME/.git-credentials
make test
```
closes #2604
> Tests should update only test-local git configuration files

- kustomize/bundle.yaml
- runatlantis.io/docs/deployment.md
- set recommended k8s name label
- recommended by docs
- See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels.
> fix(kustomize): Use k8s recommended name label

- Dockerfile
The runatlantis/atlantis#3001 PR got auto-merged too quickly leaving out a lingering commit that fixes the new image build process.
> ci: fix pipefail in golang builder image

- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
- server/events/vcs/testdata/github-branch-protection-require-linear-history.json
Currently as it stands in the latest release and since 0.23.2, repositories with branch protections enabled are seeing a breaking change to their workflows.
In summary, the GH user used by Atlantis to interface with GitHub API is unable to access the branch protection endpoint unless their permissions are set to `Admin`. Currently, we only advertise `Write` access` for the user. See [docs](https://www.runatlantis.io/docs/access-credentials.html#github-user)
*Note:* [GH Apps](https://www.runatlantis.io/docs/access-credentials.html#permissions) are unaffected since they are should be giving `Read` permissions on repo "Administration"
Reverts "fix(github): branch protection not supported (#3276)"
Reverts "fix: allow `Require Linear History` when selecting merge method (#3211)"
Closes #3320
> fix: revert branch protection feature causing breaking change

- Dockerfile
- docker-compose.yml
- add atlantis user to debian image
- It appears that when #3001 combined the Dockerfiles, the bit that adds the `atlantis` user was not added to the Debian build stage
- Also correct some trailing spaces and missing EOL in `docker-compose.yml`
```
% docker run --platform linux/amd64 -it ed5edec1285d /bin/bash
root@87731013d732:/# getent passwd atlantis
atlantis:x:1000:1000::/home/atlantis:/bin/bash
```
- #3001 
Closes #3318
> fix(atlantis-image): add missing atlantis user in Debian image

- .github/workflows/atlantis-image.yml
The atlantis-image workflow was attempting to push to our ghcr repo on a forked PR when that shouldn't be allowed. It was failing thankfully due to GITHUB_TOKEN permissions properly set to read-only.
The original conditional should have been `github.event.pull_request.head.repo.full_name == github.repository` not `!=` but I found a cleaner way.
https://github.com/runatlantis/atlantis/actions/runs/4671885635/jobs/8273419737?pr=3317
> ci: fix docker push logic when PR originates from fork

- Dockerfile
Docker builds are failing due to an invalid curl package version 8.01 instead of 8.0.1-rc1. This is also breaking builds for Debian since we concurrently fail both if one fails. I also took the opportunity to optimization the images and optimize the go package cache. 
https://github.com/runatlantis/atlantis/actions/runs/4724997776
> fix: alpine build failures, misc tweaks to cache

- runatlantis.io/docs/custom-workflows.md
- runatlantis.io/docs/post-workflow-hooks.md
- runatlantis.io/docs/pre-workflow-hooks.md
- server/core/runtime/post_workflow_hook_runner.go
- server/core/runtime/post_workflow_hook_runner_test.go
- server/core/runtime/pre_workflow_hook_runner.go
- server/core/runtime/pre_workflow_hook_runner_test.go
- server/core/runtime/run_step_runner.go
- server/core/runtime/run_step_runner_test.go
This change adds `PULL_URL` to environment variables.
It is convenient to have the PR URL available so that we can link the PR that triggers the infrastructure changes from the audit logging system. For example, the google cloud provider adds user-supplied justification into google cloud audit logging via `CLOUDSDK_CORE_REQUEST_REASON` environment variable.
Built an image with this PR's change and confirmed that the audit logging system contains the `PULL_URL`. The following workflow was used to export `CLOUDSDK_CORE_REQUEST_REASON` env var.
```
workflows:
default:
apply:
steps:
- env:
name: CLOUDSDK_CORE_REQUEST_REASON
command: echo "$PULL_URL"
- apply
```
https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#request_reason
> feat: add PULL_URL to environment variables

- cmd/server.go
- server/controllers/events/events_controller.go
- server/controllers/events/events_controller_test.go
- server/core/config/raw/repo_cfg.go
- server/core/config/valid/repo_cfg.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/instrumented_client.go
- server/events/vcs/mocks/mock_client.go
- server/events/vcs/not_configured_vcs_client.go
- server/events/vcs/proxy.go
- server/server.go
- server/user_config.go
Adds 👀  reaction to the comment whenever it detects an `atlantis` command.
I've tested this on a dev instance of Atlantis and it works as expected for my trivial test cases,
but not sure what kind of unit tests you'd like to see for this, so opening it for discussion.
I guess this could also be behind a command line flag, but I'm not sure if that's necessary?
Note that I've stubbed the other VCS providers, as I don't have access to any of them for testing,
I suppose at least bitbucket could support this feature as well tho.
- Emojis (github reactions) on atlantis command comments like `atlantis apply ` can give us assurance that Atlantis has picked up the job
- Partially implements https://github.com/runatlantis/atlantis/issues/1084 for Github
> feat: Github reaction emojis on PR comments

- .github/workflows/atlantis-image.yml
Update atlantis-image workflow to build/push the docker image when the following files have updates:
- go.mod
- go.sum
- package.json
- yarn.lock
Automated tools like dependabot and renovate bump these files only and wouldn't normally trigger the workflow.
If there is any version update on any dependency, we should be rebuilding the app and docker image to ensure no conflicts. We were previously only building on go code changes.
https://github.com/runatlantis/atlantis/pull/3352
https://github.com/runatlantis/atlantis/pull/3346
https://github.com/runatlantis/atlantis/pull/3330
> fix(atlantis-image): build atlantis image when all packages update

- .github/workflows/atlantis-image-required.yml
There are still some corner cases where atlantis-image doesn't run, thus blocking PRs for passing. This should properly handle all cases by inverting the paths with paths-ignore.
There are still some corner cases where atlantis-image doesn't run, thus blocking PRs for passing. This should properly handle all cases by inverting the paths with paths-ignore.
https://github.com/runatlantis/atlantis/pull/3374
https://github.com/runatlantis/atlantis/pull/3330
> fix(ci): Create atlantis-image-required.yml

- server/controllers/events/events_controller.go
- server/controllers/events/events_controller_test.go
This commit improves on that to make it possible to implement reactions in other VCS providers and also reuse the existing comment parsing.
My initial implementation of the reactions have a couple of problems:
* The reaction happens inside the github block so it can't be implemented for other VCS providers
* It re-implements comment parsing so it does not work for new supported calling forms like `@bot-nick apply`
This PR attempts to remedy the above problems by passing the comment ID to handleCommentEvent and doing
the reaction from there. The test written for the functionality continues to pass, indicating that react is 
still being called :) I've also added a check to allow disabling reactions by setting them to the empty
string.
Other VCS providers can then be implemented by passing a …
> feat(reaction): disable reactions by setting an empty string

- runatlantis.io/docs/server-configuration.md
Add more context to the `atlantis-url` parameter in the server-configuration documentation.
Some users had similar issues with this part and have commented on it in the #community slack channel.
- [Slack channel link to have more context ](https://atlantis-community.slack.com/archives/C5MGGAV0C/p1683277236911529)
> chore(docs): Add notes to atlantis-url in server-configuration

- .github/workflows/atlantis-image.yml
- Disables pushing a dev tag within an unmerged pr commit event.
- Also disabled image pushing at all unless the event comes from the main branch
Currently, the workflow updates the dev tag on unmerged pr commit events. This should only happen on the main branch. This is additional logic to prevent such possibilities
> fix(ci): push docker dev tag only on merge to main

- .adr-dir
- docs/adr/0001-record-architecture-decisions.md
We need to record the architectural decisions made for Atlantis. The project is a very decentralized project. It suffers from frequent one-timer contributors and an ever-changing team of maintainers.
By utilizing the ADR process, we can improve who decisions are made and bring transparency to past decisions to assist future contributors and maintainers to confidently steer the project.
https://github.com/runatlantis/atlantis/pull/3345
> docs(adr): setup ADR process 0001

- server/events/instrumented_project_command_runner.go
- Add `project` and `commandName` SubScope to CommandRunner scope.
- Metrics:
- `atlantis_cmd_comment_%COMMAND_project_execution_success` -> `atlantis_project_%COMMAND_execution_success`
- With only `atlantis_project_execution_success` metric there was no way of knowing if it was a `plan`, `apply`, etc.
`atlantis_cmd_comment_%COMMAND_project_execution_success` - > `atlantis_project_%COMMAND_execution_success`
```
atlantis_cmd_comment_plan_execution_time{quantile="0.5"} 4.06519725
atlantis_cmd_comment_plan_execution_time{quantile="0.75"} 4.06519725
atlantis_cmd_comment_plan_execution_time{quantile="0.95"} 4.06519725
atlantis_cmd_comment_plan_execution_time{quantile="0.99"} 4.06519725
atlantis_cmd_comment_plan_execution_time{quantile="0.999"} 4.06519725 …
```
> fix(metrics): add missing stat metric scopes

- scripts/e2e-deps.sh
- scripts/e2e.sh
- v3 became the stable version recently and we haven't updated our scripts yet. This is a temporary change until we upgrade to ngrok v3.
- `http` proto was deprecated so it returned an empty string
Error with localhost
```
2023/05/22 14:05:38 cleaning workspace /tmp/atlantis-tests
2023/05/22 14:05:38 creating atlantis webhook with http://localhost:4141/events url
2023/05/22 14:05:39 error creating atlantis webhook: POST https://api.github.com/repos/runatlantis/atlantis-tests/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom Message:Sorry, the URL host localhost is not supported because it isn't reachable over the public Internet}]
```
What we should see
```
2023/05/13 02:51:56 cleaning workspace /tmp/atlantis-tests
2023/05/13 02:51:56 creating atlantis webhook with …
```
> fix(tests): Pin ngrok to v2 and use https

- .github/workflows/atlantis-image.yml
- fix(atlantis-image): push on release tag
- 0.24.0 is missing a release image tag with the same name. This will correct it in the future.
- works in my [fork](https://github.com/nitrocode/atlantis/actions/runs/5052591870). I disabled the action but you can see that push is true because the disabled step says build and push.
> fix(atlantis-image): push on release tag

- server/events/instrumented_project_command_runner.go
- Use the `CommandName.String()` from the `ctx` instead of fixed string.
- Since the whole metrics implementation was deploy it never used the `commandName` argument from `RunAndEmitStats` function you can see it clearly in the first commit it was only use for `logger.Err()`
- https://github.com/runatlantis/atlantis/pull/2147/files#diff-161796dd18c10dc19d3513064a1bcc27d4a5e2fc9c2276d82e741aa85f89c79eR24-R58
- All this time the metrics we saw with plan/apply/policy_check those strings came from the actual atlantis commands from the GitHub comments.
- Then this happened: https://github.com/runatlantis/atlantis/issues/3236
- In my previous PR, I start using for the time the `commandName` argument in order to fix the previous mention issue and that when we saw the first panic that was cause …
> fixbug: Update commandName in RunAndEmitStats

- server/events/post_workflow_hooks_command_runner.go
- server/events/pre_workflow_hooks_command_runner.go
Moved the generation of the `HookID` from outside the workflow hook processing loop to inside, so a unique id gets created for each hook.
- Fixes #3453 
```yaml
repos:
- id: /.*/
pre_workflow_hooks:
- description: pre workflow test 1
run: echo "pre workflow test 1"
- description: pre workflow test 2
run: echo "pre workflow test 2"
post_workflow_hooks:
- description: post workflow test 1
run: echo "post workflow test 1"
- description: post workflow test 2
run: echo "post workflow test 2"
```
> fix (workflow-hook): Make Unique Output IDs for Separate Pre and Post Workflow Hooks

- server/server.go
- server/server_test.go
VCSClient was inadvertently removed from the commandrunner instantiation in #3086.
https://github.com/runatlantis/atlantis/pull/3086/files#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4L780
This has caused server panics during the course of normal operations.
Bugfix.
Added a unit test to ensure that VCSClient is passed to commandRunner during server initialization.
- Fix #3446
> fix: Initialize VCSClient for commandrunner to remove recent server panics

- runatlantis.io/docs/custom-workflows.md
Fixed indent in Environment of  Custom Workflow run command.
The custom run command Notes describes many environment variable entries. However, it was difficult to read due to incorrect indentation.
before:
after:
> [Document] fix list indent Custom Workflows run command environments

- runatlantis.io/docs/repo-level-atlantis-yaml.md
As the title states.
It is desirable to run terraform plan/apply even if only provider versions are updated.
> docs: include .terraform.lock.hcl to when_modified examples

- CHANGELOG.md
Minor ease-of-use change to link to the releases page so that when people (like me) google  "atlatnis change log" it's easier to get to releases.
> Include link to releases page in Changelog

- server/events/markdown_renderer.go
- server/events/models/models.go
- server/events/models/models_test.go
- This PR adds an additional struct to the data passed down to the templates in the Markdown renderer with stats about a successful plan: number of resources to add, update, destroy, if it include changes (something that's already covered but I started working on this branch before that change went in) and if there are any resources changed outside of Terraform.
- The benefit of passing down this stats won't probably be notable with the default templates as they are, but it could, however, allow users to render a successful plan like the following:
---
| environment | add | change | destroy |
|-|-|-|-|
| `staging` | 3 | 1 | 0 |
| `dev` | 0 | 0 | 5 |
- `prod-01`
- `prod-02`
---
The template code to do something like that could be:
```
{{ $withChangesOutside := false }}
| environment | add …
```
> feat(stats): pass plan stats to markdown templates

- server/events/mock_workingdir_test.go
- server/events/mocks/mock_comment_building.go
- server/events/mocks/mock_working_dir.go
- server/events/project_command_runner.go
- server/events/working_dir.go
- server/events/working_dir_test.go
When using the merge checkout strategy, only check for upstream changes and re-clone when creating a plan. 
Previously we would check for upstream changes and merge them during any call to Clone(), but if we had already made a plan, this would remove the generated plan. This would always happen if any workflow hooks were defined, and any other PRs had been merged between plan and apply.
It is only safe to re-clone and merge new upstream changes and after grabbing the directory lock, but before creating a plan.
- closes #3474
- closes #3487
- closes #3488
> fix: Check for upstream changes to merge only when planning

- .github/workflows/atlantis-image.yml
- fix(github-actions): pin buildx to v0.11.2
- resolve intermittent build failures
- at one point we did not have a pin, which gave us many build failures. Then we pinned to v0.10.6 and experienced no build failures. Then buildkit released a fix in v0.11.2 and instead of pinning, we removed the pin to use the latest again. I think a recent release maybe v0.11.6 or earlier caused a regression, albeit rare.
- if pinning to v0.11.2 doesn't resolve this then we pin to v0.10.6 again
- https://github.com/docker/build-push-action/issues/761#issuecomment-1406261692
- https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
- https://github.com/runatlantis/atlantis/actions/runs/5139979174/jobs/9250992369
- previous pr #3018 (pin to v0.10.6) and #3121 (remove pin)
- …
> fix(github-actions): pin buildx to v0.11.2

- runatlantis.io/docs/access-credentials.md
This PR updates the documentation to clarify there is no need to have manual webhooks created when using GitHub App method.
It is not clear that you don't need a webook with GitHub App and users might create that when setting up Atlantis. This leads to locking errors on Atlantis server.
- documents https://github.com/runatlantis/atlantis/issues/2346
> fix(docs): Update access-credentials.md

- server/core/runtime/models/shell_command_runner.go
- server/core/runtime/models/shell_command_runner_test.go
- server/core/terraform/terraform_client.go
- server/core/terraform/terraform_client_internal_test.go
This PR adds the wall clock duration of executing any Terraform command to the logs.
This information is useful for observability purposes.
Tested the changes running Atlantis locally. Because it relies on `time.Now` adding tests that are not flaky is difficult.
- closes #3413.
> feat: Add Terraform command duration to log messages

- server/controllers/templates/web_templates.go
Remove the incorrect `?discard=true` query string from the `lock` and `unlock` conditions in the `applyLockModalSetup` function.
- Fixes #3510 
Tested locally
> fix: Remove the 'Plan Discarded' Message from the Enable/Disable Apply Commands

- runatlantis.io/docs/server-configuration.md
- server/controllers/events/events_controller.go
- server/controllers/events/events_controller_test.go
- server/events/event_parser.go
- server/events/event_parser_test.go
- server/events/mocks/mock_event_parsing.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/bitbucketcloud/client.go
- server/events/vcs/bitbucketserver/client.go
- server/events/vcs/client.go
- server/events/vcs/github_client.go
- server/events/vcs/gitlab_client.go
- server/events/vcs/instrumented_client.go
- server/events/vcs/mocks/mock_client.go
- server/events/vcs/not_configured_vcs_client.go
- server/events/vcs/proxy.go
Adds reaction emojis to Atlantis command comments on GitLab merge requests.
- Replace stub GitLab `ReactToComment` function with a call to `g.Client.AwardEmoji.CreateMergeRequestAwardEmojiOnNote`
- GitLab requires the `MergeRequestIID` (`pullNum`) and `NoteID` (`commentID`) properties for the call. `pullNum` was not currently being passed to the `ReactToComment` function so this has been added to all the VCS `ReactToComment` functions and calls. `commentID` has been added as an output of `ParseGitlabMergeRequestCommentEvent`.
Missing documentation for the `emoji-reaction` property has also been added.
Bring Atlantis GitLab VCS support more inline with the GitHub VCS support.
- #1084
- Closes #3455
> feat: Add GitLab Reaction Emojis on MR Comments

- .github/workflows/atlantis-image.yml
- chore(buildkit): pin to v0.10.6
- Reduce the number of failures when pushing images
- Previous PR https://github.com/runatlantis/atlantis/pull/3481
- Broken run using v0.11.2 https://github.com/runatlantis/atlantis/actions/runs/5250852852/jobs/9485217740
- https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
> chore(buildkit): pin to v0.10.6

- Dockerfile
- re-add terraform 1.4
- maintain 4 releases as we previously had
- Add 1.4 again since renovate updated to 1.5 and removed 1.4 by accident. Difficult to prevent this.
- We previously had 4 releases so this maintains 4 releases cached in the container since each release is 80 MB making it expensive in bandwidth.
- Previous PR https://github.com/runatlantis/atlantis/pull/3514
- https://releases.hashicorp.com/terraform/
> chore(Dockerfile): re-add terraform 1.4

- cmd/server.go
- cmd/server_test.go
I couldn't help noticing that the words `branch` and `merge` are scattered throughout the `cmd` package so this is just a proposal to replace them with `const`.
I am not sure how to handle [this](https://github.com/runatlantis/atlantis/blob/main/server/server.go#L461) one however as it creates a cyclic dependency between `cmd` and `server` packages.
We can discard this RP altogether or perhaps use a dedicated package for constants? Open to suggestions / discussion.
> chore: using constants for checkout strategies

- runatlantis.io/docs/policy-checking.md
Fix the documentation of the policy approval command introduced by #3351
There's a typo, the command in the doc before this patch does not exist
#3351
> docs: fix policy-checking command example

- server/controllers/events/events_controller_e2e_test.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
Looks like some of the changes I did to the tests didn't make it into PR #3503 :man_facepalming: 
Fix broken tests
#3503
> fix: Tests broken by #3503

- server/events/automerger.go
- server/events/command_runner_test.go
Tests were broken after merging #3379 ; the logic for reconciling automerge between project and global levels was incorrect, as global settings were being used when project-level automerge was configured true. This change addresses the issue by passing project-level settings in whole if a project is being used.
To fix broken tests and broken automerge logic.
* previously failing e2e tests are now passing.
> fix: broken automerge logic

- .github/workflows/website.yml
- https://github.com/runatlantis/atlantis/actions/runs/5652166425/job/15311381309
missing backslash
- Because I was doing a lot and tests were passing originally 👍 
- https://github.com/runatlantis/atlantis/actions/runs/5652166425/job/15311381309
> fix(website-test): missing backslash for muffet

- Dockerfile
- Updates apk packages with proper pinning after updates.
- Alpine docker images were failing due to minor version bumps (not patch)
https://github.com/runatlantis/atlantis/actions/runs/5652166423/job/15311381044#step:10:1709
> fix: alpine package versions bump

- .github/workflows/website-required.yml
- This needs to match up with the website / link_check
If it doesn't, it won't allow non-website related JS files to block PRs
> fix(ci): link_check required

- server/core/runtime/policy/conftest_client.go
Update the ConfTest log message if the default conftest version is not found from `warning` to `info`, as this message complete with a Go stack trace is logged even if conftest is not configured. 
Remove an irrelevant Go stack trace log entry which is logged on every Atlantis service start. 
Log entry before the change:
```
{"level":"warn","ts":"2023-07-28T14:13:14.405+0100","caller":"policy/conftest_client.go:151","msg":"failed to get default conftest version. Will attempt request scoped lazy loads DEFAULT_CONFTEST_VERSION not set"
,"json":{},"stacktrace":"github.com/runatlantis/atlantis/server/core/runtime/policy.NewConfTestExecutorWorkflow\n\t/mnt/c/Users/Simon/Documents/GitHub/X-Guardian/atlantis/server/core/runtime/policy/conftest_client.go:151\n …
```
> fix: Update Conftest 'Failed to get default conftest version' Log entry to Info

- server/logging/simple_logger.go
Fixes the Simple Logger `Log` function so that the sugared logger is used to log the correct caller, the same as all the other log functions.
The wrong caller is currently logged for this function
Locks controller 'Apply Lock' log entry before the change:
```
{"level":"info","ts":"2023-07-28T14:13:33.829+0100","caller":"logging/simple_logger.go:159","msg":"Apply Lock is acquired on 2023-07-28 14:13:33","json":{}}
```
after this change:
```
{"level":"info","ts":"2023-07-28T14:08:03.793+0100","caller":"controllers/locks_controller.go:149","msg":"Apply Lock is acquired on 2023-07-28 14:08:03","json":{}}
```
> fix: Update the Simple Logger Log Function to log the Correct Caller

- runatlantis.io/docs/security.md
- runatlantis.io/docs/server-configuration.md
- server/events/repo_allowlist_checker.go
- server/events/repo_allowlist_checker_test.go
Update the flag an optional flag `--repo-allowlist` to allow for rules that begin with `!` to omit repos.
Existing allow lists (as long as they don't have rules that start with `!`) would be unaffected
In general, useful to be able to exclude repos included by a glob. As a specific example, in our setup, we have repos foo/* that we want to be tracked by atlantis, but sometimes we want to omit a repo to do some testing, so this will allow us to do `--repos-allowlist='foo/*,!foo/bar'`.
I searched the whole repo for "allow.?list" and updated each place it occurred. 
I added several unit tests to the previous code that matched the allow list.
Closes #1180
> feat: Allow for negations in repo allowlist

- runatlantis.io/docs/repo-level-atlantis-yaml.md
- server/core/config/parser_validator_test.go
- server/core/config/raw/autoplan.go
- server/core/config/raw/autoplan_test.go
- server/core/config/raw/project_test.go
- server/core/config/raw/repo_cfg_test.go
- server/core/config/valid/repo_cfg_test.go
- server/events/project_finder_test.go
When `projects` are specified and `when_modified` is not specified via
the config file, changing `.terraform.lock.hcl` file won't trigger auto
plan. This is because the default `raw.WhenModified` does not include
`.terraform.lock.hcl`.
Note that when projects are auto detected, changing
`.terraform.lock.hcl` triggers auto plan. This is because the
`cmd.DefaultAutoplanFileList` includes `.terraform.lock.hcl`.
It is desirable to run terraform plan/apply even if only `.terraform.lock.hcl` are updated.
I added a unit test and also tested this behavior by running atlantis with this change.
See also https://github.com/runatlantis/atlantis/pull/3466.
> fix: auto plan when .terraform.lock.hcl changed

- server/controllers/events/events_controller_e2e_test.go
- server/events/command_requirement_handler.go
- server/events/command_requirement_handler_test.go
- server/events/github_app_working_dir.go
- server/events/github_app_working_dir_test.go
- server/events/mock_workingdir_test.go
- server/events/mocks/mock_working_dir.go
- server/events/post_workflow_hooks_command_runner.go
- server/events/post_workflow_hooks_command_runner_test.go
- server/events/pre_workflow_hooks_command_runner.go
- server/events/pre_workflow_hooks_command_runner_test.go
- server/events/project_command_builder.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/project_command_runner.go
- server/events/project_command_runner_test.go
- server/events/working_dir.go
- server/events/working_dir_test.go
Update the `server/events/working_dir` file logging configuration:
- Add logging messages to state changing functions (`Delete` and `DeleteForWorkspace`).
- Update functions in working_dir (`Clone`, `HasDiverged`, `forceClone`, `recheckDiverged`), to use the parent object logger rather than requiring a logger passed to each function. This simplifies the code in the calling functions and unit tests.
> chore: Update server/events/working_dir Logging Configuration

- server/events/github_app_working_dir_test.go
- server/events/plan_command_runner_test.go
- server/events/project_command_builder.go
- server/events/project_command_context_builder.go
- server/events/project_finder.go
- server/events/working_dir_locker.go
- server/events/working_dir_locker_test.go
Fix the following Go static check errors:
```json
{
"resource": "server/events/github_app_working_dir_test.go",
"message": "package \"github.com/petergtz/pegomock/v4\" is being imported more than once (ST1019)\n\tgithub_app_working_dir_test.go:8:2: other import of \"github.com/petergtz/pegomock/v4\"",
"startLineNumber": 7,
},{
"resource": "server/events/plan_command_runner_test.go",
"message": "type RepoModel is unused (U1000)",
"startLineNumber": 499,
},{
"resource": "server/events/project_command_builder.go",
"message": "*&x will be simplified to x. It will not copy x. (SA4001)",
"startLineNumber": 737,
},{
"resource": "server/events/project_command_context_builder.go",
"message": "should omit comparison to bool constant, can be simplified to prjCfg.PolicyCheck (S1002)", …
```
> chore: Fix Go Static Check Errors

- .github/workflows/lint-required.yml
- .github/workflows/lint.yml
- .golangci.yml
Fixes the [golangci-lint](https://golangci-lint.run/) configuration by making the following changes:
- Adds a run timeout of 10 minutes. The current lint run takes longer than the default of 1 minute.
- Removes the following deprecated linters:
- `deadcode`
- `structcheck`
- `varcheck`
- Removes the separate `revive` and `errcheck` lint jobs, as these were always attempting to run all the linters each time, due to this repo having a `.golintci.yml` file with explicit enabled linters. See: https://github.com/golangci/golangci-lint/issues/1972
- Fix the `paths` in the `lint` GitHub Workflow config.
- Fix the `paths-ignore` in the `lint-required` GitHub Workflow config.
Note: `linter / runner / revive` and `linter / runner / errcheck` will need removing from the required status checks in any …
> chore: Fix golangci-lint Configuration

- server/events/vcs/gitlab_client_test.go
* Fix failing test caused by https://github.com/runatlantis/atlantis/pull/3428
> fix: gitlab client failing test

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
By fixing nil pointer reference in #3428 we unveiled yet another bug now that the code is able to run further:
When an MR with no HeadPipeline exists its commits are set to skipped by default and thus create some mess when running "PullMergeable" (rendering the MR useless)
The bug was caught by the tests, however, in an attempt to make the build pass and unblock we create a patch to ignore that test.
In order to prevent further problems, this MR:
* Updates the test stack to run all plan/apply commands in the context of "HeadLess" Pipelines
* Fixes the default of skipped pipeline to false (as it is better to assume it is NOT skipped since that prevents the merge in most cases)
* Make all integration tests pass
* Original MR: https://github.com/runatlantis/atlantis/pull/3428
* Tests Patch …
> fix(gitlab): Prevent considering non-head pipelines skipped by default

- runatlantis.io/docs/server-configuration.md
precidence -> precedence
Additional markdown formatting: no trailing/empty lines, extra EOL space.
> docs: fix typo

- runatlantis.io/docs/server-side-repo-config.md
> docs: Fix server side repo config document typo

- runatlantis.io/docs/server-configuration.md
Added information how to obtain `--gh-app-slug` value from installed app
It was very confusing and docs were not clear on that Github specific thing.
> docs: updated server-configuration.md on GirhubApp slug

- runatlantis.io/docs/pre-workflow-hooks.md
Update the Pre Workflow Hooks documentation with details of the new `fail-on-pre-workflow-hook-error` server configuration flag. This was missed from PR #3729.
> docs: Update Docs for the Server Config Flag to Enable Failure on Pre Workflow Hook Errors

- server/events/command_requirement_handler.go
- server/events/command_requirement_handler_test.go
- server/events/project_command_runner_test.go
Changed verbiage on comment that is posted on a PR when the approval is required and not given.
The comment currently says "Pull request must be approved by at least one person other than the author before running apply". However that's not always true. What the code is actually looking for is for whether the relevant VCS calls this request "approved". In my case of gitlab, but presumably in other VCSs as well, there are a lot of things that could go into determining whether an approval is "sufficient" or not, which may or may not include a person other than the other approving. This causes confusion for users who, understandably, think they need to find someone else to approve their MR, when they might not.
Additionally, I don't see any code in …
> fix: Change message for when request is not approved to be more accurate

- .github/workflows/test.yml
* Failure to run tests on `main`: https://github.com/runatlantis/atlantis/actions/runs/6112372312/job/16589702601
* Caused by https://github.com/runatlantis/atlantis/pull/3675
* The code must be checked out to run properly on push events (main branch) as mentioned in https://github.com/dorny/paths-filter?tab=readme-ov-file#supported-workflows
> fix: checkout before `dorny/paths-filter`

- server/core/terraform/terraform_client_test.go
hashicorp has released a 1.3.10 version of terraform, so the test needs to be updated.
Maybe a slightly more lenient check would be appropriate here.
> fix: latest terraform 1.3.* is now 1.3.10

- runatlantis.io/docs/custom-workflows.md
- Docs to implement target plan, import, and state removal workaround for Terragrunt
- Documentation updated to include a full Terragrunt custom workflow that has the capabilities to use the commands not supported natively for Terraform wrappers.
- By default, Atlantis doesn't support targetted plans/applies, imports, and state removes for Terragrunt out of the box. This update provides a workaround that works, and other people might find useful
- N/A
- No supporting issue number. However this was discussed in the community Slack.
> docs: Update Terragrunt custom workflows docs 

- .github/release.yml
Refactored the release notes a bit to catch-all at the end and surface fixes/features better.
docs were excluded but we auto-tag docs when the docs are touched even in fix/feature PRs. This caused important changes to be excluded from release notes.
fixes #3667
> ci: auto generated release notes

- Dockerfile
In the Alpine Docker image, those 2 variables are not available, but they are available in the ubuntu version : 
DEFAULT_CONFTEST_VERSION
DEFAULT_TERRAFORM_VERSION
Some have expressed the need to use the DEFAULT_TERRAFORM_VERSION and DEFAULT_CONFTEST_VERSION in the alpine image. Right now, we're rebuilding the image to include this environment variable. 
I have tested my changes by building locally
> feat: set default tf & conftest env vars for apline

- server/core/runtime/mocks/mock_status_updater.go
- server/core/runtime/runtime.go
- server/events/mocks/mock_event_parsing.go
- server/events/mocks/mock_job_url_setter.go
- server/events/project_command_runner.go
- server/jobs/job_url_setter.go
- server/jobs/mocks/mock_project_status_updater.go
Change some function parameter names from "result" to "res" so `pegomock` creates valid go code automatically.
pegomock generates code that among other things contains `result := ...`, which breaks if result exists as a function parameter.  I don't know how this was handled before, I suspect manual editing after running make go-generate?
> fix: make go-generate now creates working mocks out of the box

- .github/workflows/website.yml
Website test failure from external sources
Atlassian rate limiting or blocking link checker
https://github.com/runatlantis/atlantis/actions/runs/6401854367/job/17377576143?pr=3810
> fix(ci): website tests 403 atlassian links

- server/events/vcs/instrumented_client.go
When the underlying GitHub Client returns an error it gets swallowed in this wrapper method. Not only that but also the emitted metrics are wrong, as it counts one error AND success at the same time.
We've found this @grafana when using Atlantis in a massive repository with many changes per minute, and sometimes Atlantis leave a comment saying it's automatically merging but then nothing happens. But checking the logs, we've found the following error message:
Unable to merge pull, error: merging pull request: PUT     https://api.github.com/repos/grafana/redacted/pulls/XXX/merge: 405 Base branch was modified. Review and try the merge again. []
And because the error is swallowed and `InstrumentedClient.MergePull` returns `nil`, then `Automerger` fails to leave a comment saying merging …
> fix: Return error on `InstrumentedClient.MergePull`

- .github/workflows/test.yml
Adding slack integration to alert on the gotest job failure on the main branch
Quick feedback loop on triaging the broken main build
> ci: add slack alerting per gotest job failed on main branch

- runatlantis.io/docs/access-credentials.md
Add instructions on using a GitHub app created externally to the documentation.
Add notes about the difference from using Atlantis to create the app
Very open to rewording this, I just wanted to finally open a PR for it
There is no documentation around using an externally created app.
There are benefits to both and it should be highlighted to users who may have more than one Atlantis installation
closes #3281
> docs: Update the GitHub app installation instructions to include a section on manually creating a GitHub app and using it with Atlantis

- server/controllers/events/events_controller_e2e_test.go
Determine how many expected comments and webhooks there are in the events controller e2e test by making use of a variable that tracks whether or not plans need to be discarded.
This was a very subtle bug that I noticed when working on #2992. Right now we use the `ExpParseFailedCount` flag to decrement not only the number of webhooks we expect to have fired, but also the number of comments that are expected. When the controller fails to parse the command, it does not fire a webhook (https://github.com/runatlantis/atlantis/blob/main/server/controllers/events/events_controller.go#L577), however it *does add a comment*. We then unconditionally add `1` to the expected number of comments to handle the comment for the cleanup of locks, but *this does not happen in this case*. Therefore two …
> fix: Better determine number of expected comments and webhooks in e2e test

- Dockerfile
provide terraform 1.6.3 support for atlantis
the new version of terraform was released yesterday
I have compiled my own atlantis image with terraform 1.6.3 and it works
> feat: bump terraform default version to 1.6.3

- .github/cherry-pick-bot.yml
Enable cherry-pick-bot to help manage the new release cycle
We are using a new release cycle where minor versions are branched from main to help insulate fixes from features when doing patch releases.
https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot#configuring
> chore: enable cherry-pick-bot.yml

- server/events/command_runner.go
- server/events/pre_workflow_hooks_command_runner.go
- server/server.go
When a pre-workflow hook is launched for plan and apply commands, set the relevant plan/apply commit status to `pending` at the start of the hook. This prevents a VCS auto-merge feature from prematurely merging the PR when the pre-workflow hook finishes.
Also, if `fail-on-pre-workflow-hook-error` is set, update the relevant plan/apply commit status to 'failed' at the end of the hook.
Also fix the current 'unable to update pre workflow hook status' message text.
- Fixes #3875 
Tested locally
> fix: When GitHub/GitLab Auto-Merge Is Used with Atlantis Pre Workflow Hooks, the PR will be Merged Prematurely

- .github/renovate.json5
- .github/workflows/renovate-config.yml
This fixes renovate to also autoMerge fixes to our release branches.
This improves automation so we don't have to manually cherry-pick and backport dependency bumps 
https://docs.renovatebot.com/configuration-options/#basebranches
> fix(renovate): add release branches to renovate

- .github/workflows/atlantis-image.yml
- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Not all workflows were running the release branches.
extra character. `s/releases/release`
> ci(workflows): actually run GHA workflows on s/releases/release branches

- Dockerfile
- docker-entrypoint.sh
- Make standard use of the `atlantis` user and not root.
- Removed gosu, as we're using the `atlantis` user anyways
- Set `DOCKER_CONTENT_TRUST=1` anywhere we build
- gosu has various security issues reported ([see reported issues](https://github.com/tianon/gosu/issues))
- it's not a good practice to use the root user by default
- Original PR #3886
- Closes #3777 
- Partially fixes #3789
> fix: use the non-root atlantis user instead of root (cherry-pick #3886)

- cmd/server.go
- server/user_config.go
Remove `--repo-whitelist` flag.
This flag was deprecated in https://github.com/runatlantis/atlantis/commit/8ac19e4017cf69b0afb1d6a58740f97a5e894b0d
This setting only appeared in configuration, and any behavior changes had been deferred to `--repo-allowlist`, so unit tests passing should be sufficient.
The only functional change of this PR is then:
```
Error: unknown flag: --repo-whitelist
```
- Partially addresses #2992
> feat: Remove deprecated repo whitelist flag

- Dockerfile
- remove unused packages after setcap removal
- unneded packages
- smaller image size
- https://github.com/runatlantis/atlantis/pull/3964#issuecomment-1804608527
> fix: remove unused packages after gosu cleanup

- server/events/vcs/gitlab_client.go
when mr.HeadPipeline is missing and the gitlab client retries, it logs mr.HeadPipeline.Source which causes a panic:
```
runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:261 (0x4507d7)
runtime/signal_unix.go:861 (0x4507a5)
github.com/runatlantis/atlantis/server/events/vcs/gitlab_client.go:391 (0xdebc50)
github.com/runatlantis/atlantis/server/events/vcs/proxy.go:84 (0xdf1ecc)
github.com/runatlantis/atlantis/server/events/commit_status_updater.go:135 (0x1005e77)
github.com/runatlantis/atlantis/server/events/commit_status_updater.go:111 (0x1005a5a)
github.com/runatlantis/atlantis/server/events/pre_workflow_hooks_command_runner.go:146 (0x101b995)
github.com/runatlantis/atlantis/server/events/pre_workflow_hooks_command_runner.go:90 (0x101afbd) …
```
> fix: removing mr.Headpipeline.Source log when mr.HeadPipeline is missing

- Dockerfile
Use new version curl 8.5, since 8.4 is now absent from alpine.
https://github.com/runatlantis/atlantis/pull/3911 is failing tests because of:
```
> [linux/amd64 alpine 8/8] RUN apk add --no-cache         ca-certificates~=20230506         curl~=8.4         git~=2.40         unzip~=6.0         bash~=5.2         openssh~=9.3_p2         dumb-init~=1.2         gcompat~=1.1:
0.175 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
0.353 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
0.774 ERROR: unable to select packages:
0.776   curl-8.5.0-r0:
0.776     breaks: world[curl~8.4]
```
This seems to be because curl released 8.5.0 a few days ago: https://curl.se/changes.html#8_5_0
Alpine apparently only keeps the newest: …
> fix: Bump curl from 8.4 to 8.5

- server/events/plan_command_runner.go
set policy_check status to successful after a `atlantis plan` command finds no projects that are modified. This makes
`atlantis plan` behave like `autoplan` in this regard.
If you have set policy_check as a required status in github, this would only work with autoplan for PRs that did not modify any projects. The code path for autoplan and "atlantis plan" were different in this regard, but autoplan is not always appropriate.
> fix: set policy_check status to success for PRs with no modified projects

- server/events/command_runner_test.go
- server/events/vcs/mocks/mock_client.go
Use built in functionality in the mocks that are generated by make go-generate
tests should work after regenerating mocks
> refactor: regen mocks, use existing VerifyWasCalled(Never())

- .github/workflows/website.yml
not quite sure why renovate is not working, but this is the PR to bump the muffet dependency to the latest.
> chore: bump muffet from 2.6.3 to 2.9.3

- server/events/working_dir.go
fix mergeAgain function for when the PR is created from a fork
Fixes https://github.com/runatlantis/atlantis/issues/4034. When the PR is generated from a fork, mergeAgain function is incorrectly merging against baseBranch from the fork repository, instead of baseBranch from baseRepository.
mergeAgain() is called because merge strategy is enabled, and the workdir is not up to date with the last changes on the upstream repository base branch (origin) (https://github.com/alanbover/atlantis/blob/main/server/events/working_dir.go#L132)
Hence, mergeAgain() replicates the state from forceClone() https://github.com/alanbover/atlantis/blob/main/server/events/working_dir.go#L263. But note that head remote is added in a later step https://github.com/alanbover/atlantis/blob/main/server/events/working_ …
> fix: update working_dir.go

- server/events/markdown_renderer_test.go
Fixes CI in markdown_renderer_test.go
https://github.com/runatlantis/atlantis/pull/4049 broke CI by changing the produced value for a number of rendered templates. I noticed this when running `make test` locally as well as in the failing tests for an unrelated PR https://github.com/runatlantis/atlantis/actions/runs/7234266257/job/19710468454?pr=4064.
I created this PR mechanically with the following command:
```
sed -i 's/delete all plans/**delete** all plans/g' server/events/markdown_renderer_test.go
```
Before:
```
atlantis % go test github.com/runatlantis/atlantis/server/events      
% https://dev.azure.com/owner/project/_git/repo
% https://dev.azure.com/owner/project/_git/repo
% https://owner.visualstudio.com/project/_git/repo
% https://dev.azure.com/owner/project/_git/repo
% …
```
> fix: CI for markdown renderer

- CONTRIBUTING.md
- GOVERNANCE.md
- MAINTAINERS.md
- USERS.md
- Adds GOVERNANCE.md, officially defines the project governance for Atlantis.
As the Atlantis project evolves, we need proper documentation around our policies and procedures regarding governance of the project.
> chore: add governance process to Atlantis

- server/events/project_command_builder.go
This changes the log line for projects changed on MR to print an integer instead of a character literal.
`%q` prints out a [a single-quoted character literal safely escaped with Go syntax.](https://pkg.go.dev/fmt) when given an integer for formatting. This results in log lines that look like:
```
0 projects are changed on MR '墤' based on their when_modified config
```
or are completely empty. This changes the format string from `%q` to `%d` so that an integer is printed instead of a character literal.
I have run atlantis locally and verified the log output.
> fix: ensure the MR log line prints an integer and not a rune

- server/events/project_command_builder.go
Update release branch from #4078
> fix: ensure the MR log line prints an integer and not a rune (#4078)

- server/events/vcs/github_client.go
- server/events/vcs/gitlab_client.go
Fixes https://github.com/runatlantis/atlantis/issues/4081
Wraps any logging that was added from https://github.com/runatlantis/atlantis/pull/3876 with an `if resp != nil` check, to avoid any panics
N/A
https://github.com/runatlantis/atlantis/issues/4081
https://github.com/runatlantis/atlantis/pull/3876
> fix: Prevent panics when logging HTTP response status in github and gitlab client

- server/events/vcs/testdata/gitlab-changes-pending.json
Change type of `labels` from string to array in gitlab test data.
Debugging why unit tests on https://github.com/runatlantis/atlantis/pull/4028 are failing, it turns out that label parsing was updated in `0.95` such that the empty string is failing:
```
unexpected error: json: cannot unmarshal string into Go struct field alias.labels of type gitlab.Labels
```
This doesn't appear to correspond to any actual changes in the API, so I don't think any non-test code needs to be updated, it's just whenever this testdata was written it was filled in with the wrong type. If you look even now at an MR in the gitlab API, you'll see it's an empty array, not an empty string:
```
atlantis % curl -sS 'https://gitlab.com/api/v4/projects/lkysow%2Fatlantis-example/merge_requests/13'  | jq .labels
[]
``` …
> chore: fix label type in gitlab testdata

- server/core/runtime/policy/conftest_client.go
- server/core/runtime/policy/conftest_client_test.go
Download the conftest binary that corresponds to the correct architecture
The current conftest binary architecture is hardcoded, causing failures on ARM-based instances. This pull request will dynamically determine the architecture and download the correct binary.
N/A
> fix: download conftest binary for correct arch

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/command-requirements.md
- server/controllers/events/events_controller_e2e_test.go
- server/core/config/parser_validator_test.go
- server/core/config/valid/global_cfg.go
- server/core/config/valid/global_cfg_test.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/repo_branch_test.go
- server/server.go
- server/user_config.go
Require settings in user_config.go for RequireApproval, RequireMergeable, and RequireUndiverged, and remove the flags RequireApproval and RequireMergeable.
Requested by #2992, the options were deprecated by https://github.com/runatlantis/atlantis/commit/d78b106cab5c28d9e50e75034bcd7020b561ef63.
The vast majority of the use cases of these flags were by setting them to `false` in tests which called `NewGlobalCfgFromArgs`. Indeed, the only time they were explicitly set to true was in `TestNewGlobalCfgFromArgs` itself.
RequireUndiverged was actually not set as an actual flag, despite being set in server/user_config.go, so no flag configuration to be removed then.
This change left deprecationWarnings() a functional no-op. We switched from cobra's "deprecated" to "hidden" in …
> chore: Remove settings for require approval, mergeable, undiverged

- package.json
- yarn.lock
Updated dependencies `vuepress` and `@vuepress/plugin-docsearch` from `2.0.0-beta.66` to `2.0.0-rc.0`.
There are two open PRs from renovate attempting to make these changes:
https://github.com/runatlantis/atlantis/pull/3962
https://github.com/runatlantis/atlantis/pull/3970
However, they are both failing on CI:
https://github.com/runatlantis/atlantis/actions/runs/7339572431/job/19984042669?pr=3962
https://github.com/runatlantis/atlantis/actions/runs/7339571043/job/19984040138?pr=3970
with the following error:
```
✖ Rendering 40 pages - failed in 54ms
Error: usePageLang() is called without provider.
```
Researching a bit, it seems like the reason is that the renovate PRs were updating one of these packages at a time. If you update both (as this PR does) you don't get the error: …
> chore(deps): Update vuepress to v2.0.0-rc.0

- runatlantis.io/docs/command-requirements.md
- runatlantis.io/docs/server-configuration.md
- Add `--gh-app-slug` information in `--hide-prev-plan-comments` section when using Github App.
- Add `--checkout-strategy` in `UnDiverged` section.
Easy to miss these information first time.
> feat(docs): Update docs for `--hide-prev-plan-comments` and `UnDiverged`

- server/core/config/parser_validator_test.go
- server/events/project_command_builder_internal_test.go
- server/events/project_command_builder_test.go
- server/events/repo_branch_test.go
Fix issues found by linter
#4047 introduced linting issues, as marked by https://github.com/runatlantis/atlantis/actions/runs/7339840711/job/19984795341.
Unclear why CI was still marked as passed, we should look into that.
Produced the change by running `gofmt -s -w` on the three relevant files.
#4047
> chore: fix linting issues

- scripts/e2e.sh
Fixes ngrok tunneling so that Github webhooks can hit the private instance of Atlantis in the CircleCI runners.
E2E tests are failing due to: 
```
ERROR:  authentication failed: Usage of ngrok requires a verified account and authtoken.
ERROR:  
ERROR:  Sign up for an account: https://dashboard.ngrok.com/signup
ERROR:  Install your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken
ERROR:  
ERROR:  ERR_NGROK_4018
ERROR:  
```
https://ngrok.com/docs/errors/err_ngrok_4018/
https://app.circleci.com/pipelines/github/runatlantis/atlantis/6186/workflows/c2454924-90a4-4564-bcad-53eb29150f31/jobs/16363
> fix(e2e-tests): add ngrok authtoken

- cmd/server_test.go
- go.mod
- go.sum
- server/core/config/parser_validator.go
- server/core/config/parser_validator_test.go
- server/core/config/raw/autodiscover_test.go
- server/core/config/raw/autoplan_test.go
- server/core/config/raw/metrics_test.go
- server/core/config/raw/policies_test.go
- server/core/config/raw/project_test.go
- server/core/config/raw/raw_test.go
- server/core/config/raw/repo_cfg_test.go
- server/core/config/raw/stage_test.go
- server/core/config/raw/step_test.go
- server/core/config/raw/workflow_step_test.go
- server/core/config/raw/workflow_test.go
Upgrade `gopkg.in/yaml` from v2 to v3.
Keeping dependencies up to date.
This was built off of a failing renovate run. There are two issues to deal with upgrading from v2 to v3.
1. UnmarshalStrict is no longer available (https://github.com/go-yaml/yaml/issues/602). You have to use Decode() with KnownFields set to true. Decode has slightly different semantics to Unmarshal (https://github.com/go-yaml/yaml/issues/805), so I wrapped these calls in the unit tests. In the actual code I just write the full implementation out so it's more clear, but that would have been quite a bit of copy/paste for unit tests.
2. There's a bug in yaml v3 where it doesn't parse empty elements in arrays properly (https://github.com/go-yaml/yaml/issues/805). We were only doing this in unit tests, so I had to in a …
> chore: Upgrade yaml v3

- cmd/server_test.go
Add entry to testFlags for DisableGlobalApplyLockFlag
Should be done for all new flags.
Note: This is too easy to happen by accident at this point, I am working on preventing these issues: #4063 
Ran CI
New flag introduced in: #4158
> chore: Add missing flag test for DisableGlobalApplyLockFlag

- cmd/server_test.go
- server/user_config.go
Add a unit test to make sure that all the values in server.UserConfig appear in server_test.testFlags
When you add a flag you're supposed to add it to four places: cmd/server.go as a const, cmd/server.go as part of a map for flags, cmd/server_test.go to test, and the configuration struct in server/server.UserConfig. Per #4063, if you forget some combination of these a unit test already fails (example: https://github.com/runatlantis/atlantis/blob/v0.27.1/cmd/server_test.go#L124). This adds an additional unit test to make sure a different misconfiguration doesn't occur.
Ran unit tests.
Partially addresses: #4063
Prevents recurrence of issues like: #4183, #4064
> feat: Prevent unused flags

- server/controllers/templates/web_templates.go
- server/controllers/templates/web_templates_test.go
- server/events/models/models.go
- server/events/post_workflow_hooks_command_runner.go
- server/events/pre_workflow_hooks_command_runner.go
- server/jobs/project_command_output_handler.go
- server/static/css/custom.css
- Correct naming of pre and post workflow with their description fields
- Uppercase removed from main page
As correctly described in #4132, the jobs were not clearly identifiable on the home page. 
Several fields have been added to the output structure of the various jobs to enable them to be displayed. 
On the PR, with a repos yaml like this :
```yaml
pre_workflow_hooks: 
- run: echo toto
description: echo toto
- run: echo toto2
post_workflow_hooks: 
- run: echo tata
description: echo tata
workflow: custom
workflows:
custom:
plan:
steps:
- run: echo hi
- init
- plan
- run: echo hello
```
the page looks like this :
Unfortunately, the project and workspace fields will remain empty due to the differences between a job and hook context. 
The templating test has been enhanced with …
> fix: unnamed jobs in ui

- Dockerfile
```
$ asdf list-all terraform | grep 1.4.
1.4.0-alpha20221109
1.4.0-alpha20221207
1.4.0-beta1
1.4.0-beta2
1.4.0-rc1
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
1.4.7
```
```
$ asdf list-all terraform | grep 1.5.
1.5.0-alpha20230405
1.5.0-alpha20230504
1.5.0-beta1
1.5.0-beta2
1.5.0-rc1
1.5.0-rc2
1.5.0
1.5.1
1.5.2
1.5.3
1.5.4
1.5.5
1.5.6
1.5.7
```
```
$ asdf list-all terraform | grep 1.6.
1.1.0-alpha20210616
1.1.0-alpha20210630
1.6.0-alpha20230719
1.6.0-alpha20230802
1.6.0-alpha20230816
1.6.0-beta1
1.6.0-beta2
1.6.0-beta3
1.6.0-rc1
1.6.0
1.6.1
1.6.2
1.6.3
1.6.4
1.6.5
1.6.6
```
> chore(dockerfile): update to use 1.4.7,1.6.6

- server/core/db/boltdb_test.go
- server/core/locking/locking_test.go
- server/core/redis/redis_test.go
- server/events/delete_lock_command.go
- server/events/delete_lock_command_test.go
- server/events/models/models.go
- server/events/models/models_test.go
- server/events/project_command_runner.go
- server/events/project_finder.go
- server/events/pull_closed_executor_test.go
Add logic of project name into locks.
I'm actually not totally sure why `Project` in models didn't have a `ProjectName` before. Adding this made it so we can, e.g., correctly identify the project plan files that need to be deleted when we run atlantis unlock (See #3845)
This is not a total fix, and instead kicks the can down the road a little bit. Specifically, I do *not* implement `project_finder()` to understand about project names, because frankly I'm not totally sure how, so I just assume the project doesn't have a name (i.e. empty string for ProjectName). That said, this is *no worse* than the current implementation, which *implicitly* assumes the project doesn't have a name "deeper" in the call stack.
In this sense, in my opinion this PR is a net positive, in that it moves us in the …
> feat: Add logic for project name into lock

- go.mod
```sh
$ go version
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
```
after the change
```sh
$ go version
go: downloading go1.22.0 (darwin/arm64)
go version go1.22.0 darwin/arm64
```
- relates to https://github.com/golang/go/issues/65568
Thanks @lukemassa for calling it out.
> fix: update go version in go.mod

- server/core/runtime/plan_step_runner.go
- server/core/runtime/plan_step_runner_test.go
Reverts linter change from https://github.com/runatlantis/atlantis/commit/56e38b415135c9f9e7b0df7fb52210f532afebda (#3690) which breaks TF v1.1 detection
Reverts a simple commit for a single file to fix remote operations for TF v1.1+
Without this revert you can't use Atlantis with Terraform Cloud v1.1+, see #2793 for why this was introduced in the first place.
To prepare this I did
`git checkout 2e6758e -- server/core/runtime/plan_step_runner.go`
and picked the corresponding change from `server/core/runtime/plan_step_runner_test.go`
> revert: regression: remote ops detection TF v1.1

- server/events/pending_plan_finder.go
- server/events/pending_plan_finder_test.go
Improve error message printed by atlantis in case of errors coming from `git ls-files . --others` command when calling `atlantis apply`
For make debugging easier. My case was that I had defined Terragrunt cache directory (which is not git repository) just parallel to workspace directories. At first glance it was not obvious seeing such error what is going about, but after take a look in source code I found what exactly atlantis does under the hood. Improved error message could make cause finding much faster.
Added unit test on previously uncovered code
It may also be helpful by debugging already existing issues like e.g. #2168 or #3139
> fix: improve git error log while running 'atlantis apply'

- server/events/project_command_builder.go
- server/events/project_command_builder_test.go
Detect workspaces from subdirectories during autodiscovery.
* When using terraform cloud configurations for multiple projects / modules in a single repo the default Atlantis workflow will fail
closes #3252 
supersedes #3253
> fix: auto-discover workspaces when in subdirectories

- Dockerfile
The [current Alpine build fails](https://github.com/runatlantis/atlantis/actions/runs/8328227196/job/22787734568) with
```
unable to select packages:
0.731   ca-certificates-20240226-r0:
0.732     breaks: world[ca-certificates~20230506]
0.734     satisfies: libcurl-8.5.0-r0[ca-certificates]
```
I would like for it to successfully build
It should build 
N/A
> fix(deps): Update alpine ca-certificates package version to 20240226-r0 in Dockerfile

- .dockerignore
- Dockerfile
- scripts/download-release.sh
- Add the opentofu binary so it's available to users who customize their workflows
- I kept the `COMMAND_DIR` for backwards compatibility but I don't think we should store a directory of terraform versions in here because using tf instead of terraform and opentofu instead of tofu is inconsistent. It's also necessary or there will be softlink conflicts. I'd prefer to store the binaries in a separate directory so we can keep the dir names consistent with the binaries.
- The reason `tofu` is used instead of `opentofu` is because `tofu` is their official binary name
```bash
✗ shellcheck scripts/download-release.sh
✗
```
```bash
✗ hadolint Dockerfile
✗
```
```bash
✗ docker build -t atlantis-test:latest -f ./Dockerfile .
=> exporting to image …
```
> feat: add opentofu binary to container

- server/events/project_command_builder_test.go
Sort results of `builder.BuildAutoplanCommands` before comparing to expected values in tests.
The tests are currently flakey, per: https://github.com/runatlantis/atlantis/pull/4363#issuecomment-2016939837.
A potential follow up might be to have `BuildAutoplanCommands` return a sorted list, but that might have more implications so I'll leave that for now.
`make test` now consistently passes.
https://github.com/runatlantis/atlantis/pull/4363#issuecomment-2016939837.
> fix: Sort results in command builder before comparing

- server/events/templates/policy_check_results_wrapped.tmpl
When using custom policy checking, PolicyCheckSummary is empty. This creates an empty codeblock in the output which is misleading.
Example Image
Empty codeblock is misleading! At first glance, it gives the impression that it is an empty output / policy checks have passed.
> fix: Make PolicyCheckSummary rendering optional

- server/events/markdown_renderer_test.go
Fixes an issue in the markdown renderer test changes introduced by  https://github.com/runatlantis/atlantis/pull/4254
I don't know how this passed the tests check in the previous PR.
> chore: Markdown Renderer Test Fix

- .github/renovate.json5
- use best-practices preset
- add osv vulnerabilities
- separate multiple releases so prs don't propose going from v1 to v4
- this is the best configuration preset that renovate maintains
- https://docs.renovatebot.com/presets-config/
- https://docs.renovatebot.com/upgrade-best-practices/
- https://www.jvt.me/posts/2024/04/12/use-renovate/
- https://docs.renovatebot.com/presets-default/#separatemultiplemajorreleases
- https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts
> feat(renovate): separate major, osv sec, best practices

- .github/renovate.json5
- .github/workflows/atlantis-image.yml
- create a package rule to match both go and golang
- renovate go version in multiple places instead of a single place
- Uses the same pr `types` as the lint and other actions. This is because when I switched from draft to ready-for-review, it did not trigger the required checks.
None. Opened a discussion in renovatebot and this was suggested.
- https://github.com/renovatebot/renovate/discussions/28402#discussioncomment-9110035
- Fixes PRs like #4405 where go.mod is updated but dockerfile is not
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
> chore: renovate both docker and go.mod in one pr

- Dockerfile
- use golang tag so renovate maintains it
- consistent builds
- refs are immutable vs tags are not
Locally
- Related PR #4424
> chore(docker): use golang tag so renovate maintains it

- Dockerfile
- scripts/download-release.sh
Fixes pathing when copying opentofu/terraform bins to release image
It seems in the deps container it symlinks to `/tmp/build/{tofu,terraform}${version}`. Not sure if that was intended and the `COPY` from deps was just forgotten 🤷. Let me know the intention and I can edit the PR.
Thanks
In the current on dev image the terraform bins do not exist:
```
➜  ~ docker run -it ghcr.io/runatlantis/atlantis:dev-debian bash
No files found in /docker-entrypoint.d/, skipping
atlantis@616313fed2f9:/$ terraform -v
bash: terraform: command not found
atlantis@616313fed2f9:/$ find -name terraform
find: './etc/ssl/private': Permission denied
find: './proc/tty/driver': Permission denied
find: './var/cache/ldconfig': Permission denied
find: './var/cache/apt/archives/partial': Permission denied
find: …
```
> build: fix build terraform/opentofu build pathing

- .github/workflows/test.yml
- Makefile
- scripts/fmt.sh
- server/controllers/events/testdata/test-repos/import-multiple-project/dir1/main.tf
- server/controllers/events/testdata/test-repos/import-multiple-project/dir2/main.tf
- server/controllers/events/testdata/test-repos/import-multiple-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/import-multiple-project/exp-output-plan-again.txt
- server/controllers/events/testdata/test-repos/import-single-project-var/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/import-single-project-var/main.tf
- server/controllers/events/testdata/test-repos/import-single-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/import-single-project/main.tf
- server/controllers/events/testdata/test-repos/import-workspace/dir1/main.tf
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/dir1/main.tf
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/dir2/main.tf
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/exp-output-plan-again.txt
- server/controllers/events/testdata/test-repos/state-rm-single-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/state-rm-single-project/exp-output-plan-again.txt
- server/controllers/events/testdata/test-repos/state-rm-single-project/main.tf
- server/controllers/events/testdata/test-repos/state-rm-workspace/dir1/main.tf
- server/controllers/events/testdata/test-repos/state-rm-workspace/exp-output-plan-again.txt
Version v3.6.1 of the `random` provider changed the behavior of `keepers` in https://github.com/hashicorp/terraform-provider-random/pull/385
This upstream change caused the extra `keepers = {}` output in our test output due to how the `value` of `keepers` inside the provider is processed. 
Since `keepers` are optional in the provider and `{}` is same as `absent` (or `null`) for our use-cases, I'm removing the empty `keepers = {}` from the `.tf` files
I also fixed `make check-fmt` since it was failing silently with `goimports` not being installed in CI.
I like tests passing 
All changes are test related - and pure output focused - shouldn't affect any _actual_ behavior
* https://github.com/hashicorp/terraform-provider-random/pull/385
* …
> fix: GitHub tests emitting unexpected keepers = {}

- server/core/terraform/terraform_client.go
- server/core/terraform/terraform_client_test.go
Short-term fix for #4471. With this change Atlantis will only download terraform version `1.8.1` or lower, still respecting constraints set in `required_version` field. If `required_version` is set to `>=1.8.2` or higher Atlantis will fallback to default version. 
Terraform packaging was changed in release 1.8.2 (see https://github.com/hashicorp/terraform/releases/tag/v1.8.2) and Atlantis throws an error for every default and custom workflow when trying to download it. Proper, long-term fix is described here - https://github.com/runatlantis/atlantis/issues/4472#issuecomment-2075001953.
I have added two test cases to an existing test, but haven't run full Atlantis with this change.
- See #4471 and #4472 for more info about issue and various workarounds.
> fix: Prevent download terraform with version 1.8.2 or higher

- .github/workflows/test.yml
- Makefile
- scripts/fmt.sh
- server/controllers/events/testdata/test-repos/import-multiple-project/dir1/main.tf
- server/controllers/events/testdata/test-repos/import-multiple-project/dir2/main.tf
- server/controllers/events/testdata/test-repos/import-multiple-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/import-multiple-project/exp-output-plan-again.txt
- server/controllers/events/testdata/test-repos/import-single-project-var/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/import-single-project-var/main.tf
- server/controllers/events/testdata/test-repos/import-single-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/import-single-project/main.tf
- server/controllers/events/testdata/test-repos/import-workspace/dir1/main.tf
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/dir1/main.tf
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/dir2/main.tf
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/state-rm-multiple-project/exp-output-plan-again.txt
- server/controllers/events/testdata/test-repos/state-rm-single-project/exp-output-autoplan.txt
- server/controllers/events/testdata/test-repos/state-rm-single-project/exp-output-plan-again.txt
- server/controllers/events/testdata/test-repos/state-rm-single-project/main.tf
- server/controllers/events/testdata/test-repos/state-rm-workspace/dir1/main.tf
- server/controllers/events/testdata/test-repos/state-rm-workspace/exp-output-plan-again.txt
chore: Cherry-pick #4462 "GitHub tests emitting unexpected keepers = {} " into release-0.27
Want this fix in 0.27
N/A
#4462
> chore: Cherry-pick #4462 into release-0.27

- Dockerfile
Cherry picking fix #4376 into release-0.27.
Needed to get tests to pass there.
N/A
#4376
> chore: Cherry pick #4376 into release 0.27

- server/core/terraform/terraform_client.go
- server/core/terraform/terraform_client_test.go
Cherry pick #4474 into release-0.27
Bugfix we want in 0.27 release
N/A
#4474
> chore: Cherry pick #4474 into release-0.27

- runatlantis.io/docs/server-configuration.md
Fixing misspelled environment variable of `--disable-markdown-folding` server config option. If using current environment variable, it won't function.
Reduce confusion of atlantis users, who wants to disable markdown folding feature through environment variable.
`ATLANTIS_DISABLE_MARKDOWN_FOLDER=true` didn't have any effect on atlantis behaviour, `ATLANTIS_DISABLE_MARKDOWN_FOLDING=true` did the job.
- https://www.runatlantis.io/docs/server-configuration.html#disable-markdown-folding
> docs: typo in server-configuration.md

- runatlantis.io/docs/using-slack-hooks.md
- Added clarity to the documentations that the configuration expects the channel id and not the channel name. 
- Current documentation is ambiguous with regards to weather the configuration file expects channel name or channel id.
Nil 
Nil
> fix(slack-hooks): updated example for atlantis configuration

- .github/workflows/pr-size-labeler.yml
- increase size of xl threshold
- disable fail if xl
- explicit message instead of implicit message
- disable fail message to not irk anyone as we roll out this action
- increase thresholds since the code base requires many changes (lots of copy paste at times) to get features out
- Previous PR #4526
> fix(pr-size-labeler): increase size of xl threshold, disable fail

- runatlantis.io/.vitepress/sidebars.ts
Replace spelling error in Docs sidebar :  Glossry w/ Glossary
Professionalism.
Not a code change.
> fix: fix nav bar typo with `Glossary`

- runatlantis.io/.vitepress/sidebars.ts
- runatlantis.io/docs.md
- runatlantis.io/docs/pre-workflow-hooks.md
- runatlantis.io/docs/server-side-repo-config.md
- runatlantis.io/guide.md
Now with a fully fledged left menu nav bar 
I like navigating to all pages in the docs
Works on my machine
N/A
> fix(docs): fix left navbar menu items

- runatlantis.io/.vitepress/config.ts
- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/command-requirements.md
- runatlantis.io/docs/configuring-webhooks.md
- runatlantis.io/docs/custom-workflows.md
- runatlantis.io/docs/deployment.md
- runatlantis.io/docs/locking.md
- runatlantis.io/docs/post-workflow-hooks.md
- runatlantis.io/docs/pre-workflow-hooks.md
- runatlantis.io/docs/repo-level-atlantis-yaml.md
- runatlantis.io/docs/requirements.md
- runatlantis.io/docs/security.md
- runatlantis.io/docs/server-configuration.md
- runatlantis.io/docs/server-side-repo-config.md
- runatlantis.io/docs/terraform-cloud.md
- runatlantis.io/docs/using-atlantis.md
- runatlantis.io/guide/testing-locally.md
Moving the Table of Content to the TOC right-bar to free up space 
It makes it easier to navigate long pages such as the `Server Configuration` page by having the TOC persistently available on the right side.
There can be follow-up tuning trimming down the individual headlines a bit to make it easier to scan, but feel like it should be its own change set.
> fix(docs): move TOC to the right nav bar to free up vertical space

- package.json
- pnpm-lock.yaml
- runatlantis.io/.vitepress/components/Banner.vue
- runatlantis.io/.vitepress/components/shims.d.ts
- runatlantis.io/.vitepress/config.ts
- runatlantis.io/.vitepress/theme/index.ts
add site banner for survey
fixes #4553 
took inspirations from https://github.com/faker-js/faker/pull/1487
> feat(docs): add site banner for survey

- runatlantis.io/.vitepress/theme/index.scss
The header is placed kinda odd (pic 1) and not aligned with the rest of the header
leading to content scrolling "behind" the header (pic 2)
if we remove the `padding-top` it looks correct (pic 3)
and matches the native vitepress design  (pic 4)
It looks nice
N/A
N/A
> fix(docs): fix placement of top header

- runatlantis.io/.vitepress/theme/index.scss
The `home` page had a forced `max-width` of `960px` for the top nav bar, making it look like this (pic 1)
meaning that when you navigate to _any_ other page, the top bar would "jump" and all icons/menus would get new placements, making for a surprising change in layout and "jolt" to the reading process (pic 2)
With this change, the top bar is consistently sized and placed across all pages (pic 3), making for a more consistent and easier to scan experience for folks
This is consistent with how the native VitePress them work as well
--
Navigating from [homepage](https://deploy-preview-4560--runatlantis.netlify.app/) to [docs](https://deploy-preview-4560--runatlantis.netlify.app/docs.html) and then going back and forth in history shows this clearly
> fix(docs): fix home header width so the menu doesn't jump around when navigating

- netlify.toml
Fix Content-Security-Policy (CSP) errors on the new site.
* Google Analytics work
* Netlify "preview" iframe works
* Google Tag Manager works
* Algolia search works
Considering there are no auth or PII on the site, I wonder if it would be simpler to just not enforce CSP to begin with though 🤔 
Preview site: https://deploy-preview-4567--runatlantis.netlify.app/
> fix(docs): Fix Content-Security-Policy (CSP) rules for website

- runatlantis.io/.vitepress/navbars.ts
In case folks dismiss the survey top bar, its still easily accessible.
I've had folks at $DayJob ask about the survey link twice today, because they dismissed the banner out of habit (looks like a banner/cookie content block) without reading it first.
I personally dismissed it at work without thinking because I needed to go to the docs fix an issue for a engineer, and the bar was visually distracting and looked like marketing - didn't even think about it, just removed it like a cookie consent banner by pure habit 
So been needing to go to the source code 3 times today to dig up the banner URL because of "click to dismiss"-habits, so thought it was likely other folks had similar experience.
Preview:  https://deploy-preview-4574--runatlantis.netlify.app/
> fix(docs): Add link to Survey in top bar

- Dockerfile
- testing/Dockerfile
fixes #4598 
```
$ regctl image digest golang:1.22.3
sha256:f43c6f049f04cbbaeb28f0aad3eea15274a7d0a7899a617d0037aec48d7ab010
$ regctl image digest golang:1.22.3-alpine
sha256:b8ded51bad03238f67994d0a6b88680609b392db04312f60c23358cc878d4902
$ regctl image digest debian:12.5-slim
sha256:804194b909ef23fb995d9412c9378fb3505fe2427b70f3cc425339e48a828fca
$ regctl image digest alpine:3.19.1
sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
```
---
relates to #4456
> fix: fix docker base image sha

- .github/workflows/atlantis-image.yml
- .github/workflows/release.yml
we dont do pre-release nowadays, removing the refs to avoid confusion.
> chore(release): remove pre-release refs

- runatlantis.io/docs/server-configuration.md
Update configuration docs to link to slack docs for slack api token
Currently says slack is not fully supported.
doc only
> docs: Remove todo and link to slack documentation

- README.md
- runatlantis.io/.vitepress/components/Banner.vue
- runatlantis.io/.vitepress/navbars.ts
Remove link to survey
We've closed the survey, we'll publish the results as a blog post soon.
> chore: Remove link to survey

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/server.go
- server/user_config.go
A tiny fix to correct the terminology used for the Github App Installation ID so it includes "App" as does the rest of the Github App configuration items.
This is a trivial PR to build on @john-tipper 's fine work - it's not intended to devalue the serious effort made to address the original requirement (thank you!) 
purely for naming consistency and ease of use.
Existing tests updated to use the new name.
Documentation updated too.
fixes #4579
> fix: add app to the github app installation id

- README.md
- Fix link to superdope badge
- remove codecov badge, I think we removed codecov after it had its hack
> fix: badges on readme

- server/events/plan_command_runner.go
Preventing merging without running atlantis apply on Gitlab
Preventing merging without running atlantis apply on Gitlab
https://github.com/runatlantis/atlantis/issues/4372
> fix: Preventing merging without running atlantis apply on Gitlab

- runatlantis.io/blog/2024/integrating-atlantis-with-opentofu.md
seeing linting failures in https://github.com/runatlantis/atlantis/actions/runs/9571798324/job/26389710489?pr=4683
---
```
$ markdownlint-cli2  runatlantis.io/**/*.md
markdownlint-cli2 v0.13.0 (markdownlint v0.34.0)
Finding: runatlantis.io/blog.md runatlantis.io/blog/2017/introducing-atlantis.md runatlantis.io/blog/2018/atlantis-0-4-4-now-supports-bitbucket.md runatlantis.io/blog/2018/hosting-our-static-site-over-ssl-with-s3-acm-cloudfront-and-terraform.md runatlantis.io/blog/2018/joining-hashicorp.md runatlantis.io/blog/2018/putting-the-dev-into-devops-why-your-developers-should-write-terraform-too.md runatlantis.io/blog/2018/terraform-and-the-dangers-of-applying-locally.md runatlantis.io/blog/2019/4-reasons-to-try-hashicorps-new-free-terraform-remote-state-storage.md …
```
> fix(blog): fix blog post linting issue

- runatlantis.io/.vitepress/components/Banner.vue
now with both announcements in the new release, time to comment out the banner for the next round of use.
> docs: comment out banner

- Dockerfile
Changes the base Debian image from 12.5-slim to 12.6-slim
The last update to 12.5-slim was 20 days ago
Building the container and running it via Docker Desktop
12.5 is no longer listed as a supported tag on [Docker Hub](https://hub.docker.com/_/debian)
> chore: 12.5-slim tag is no longer receiving updates, switch to 12.6-slim

- server/events/plan_command_runner.go
Reverts runatlantis/atlantis#4651
After checking this in more detail, we decided to revert this change.
This changes the user interface with the status in Gitlab.
in autoplan the status hang forever.
> revert: "fix: Preventing merging without running atlantis apply on Gitlab"

- e2e/e2e.go
- e2e/github.go
- e2e/main.go
Remove `context.Context` from struct in `GithubClient` in e2e tests.
Storing context in a struct is explicitly discouraged: https://go.dev/blog/context-and-structs
The reason I'm doing this now is because I am starting to work on #4582, so simplifying the code here first will make this easier.
I ran ./scripts/e2e.sh manually and it passed.
https://go.dev/blog/context-and-structs
> chore: do not store context in struct for e2e tests

- e2e/e2e.go
- e2e/github.go
- e2e/main.go
- e2e/vcs.go
Separate github specific code from business logic of e2e code.
Creating `VCSClient` interface consolidates VCS-related code to make it easier to write e2e test for other VCSs.
Even without adding new VCSs, this cleans up the code to make it more modular.
Ran the e2e tests manually
Working towards: #4731
> chore: make e2e code generic to vcs

- testdrive/testdrive.go
- Correct error print on repo fork failed.
> chore: correct typo in error printing

- Dockerfile
- go.mod
- testing/Dockerfile
Signed-off-by: Rui Chen <rui@chenrui.dev>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Rui Chen <rui@chenrui.dev>
Fix Ca-cert package for Alpine
Update go 
Images are not building in alpine
tested localy and in githubaction
https://github.com/runatlantis/atlantis/actions/runs/9943081422/job/27466060928
> fix: Apkfix-cherrypick-0.28

- .github/workflows/test.yml
Add `**.tmpl` files to the CI test job filters list.
Currently, if only Go template files are updated in a PR, the test CI does not run. This has caused an issue with https://github.com/runatlantis/atlantis/pull/4787 being merged without the relevant test files being updated.
> fix: Add Template Files to CI Test Job Filters

- server/events/templates/policy_check_results_wrapped.tmpl
Reverts runatlantis/atlantis#4787
---
this is causing all tests failing, thus reverting it.
> chore: revert "fix: added a space line"

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
The SetCommitStatus call in the GitLab clients UpdateStatus function will now send the pipelineID when the MR is found. 
This should prevent Atlantis from making duplicate pipelines in GitLab
These changes have been running on our private Atlantis for around a month
This should fix 
#3373 and #3722 
I've also opened #4784 separately as it's not quite the same issue. Let me know if it would be better to combine these
> fix: send pipelineID in gitlabs SetCommitStatus if the mr gets found, fallback to branch ref

- runatlantis.io/docs/policy-checking.md
- runatlantis.io/docs/server-side-repo-config.md
- server/core/config/raw/policies.go
- server/core/config/valid/policies.go
- server/events/project_command_runner.go
- server/events/project_command_runner_test.go
introducing `SelfApprove` flag to control if the author can approve.
I think it makes sense to have the ability to control if the author can approve the policy checks. 
- https://github.com/runatlantis/atlantis/issues/4813
> feat: selfapprove flag for approving policies

- e2e/e2e.go
Log error that comes from `cleanup()` function in e2e tests.
Since the cleanup function is deferred, we swallow the error and there's no way for the end user to know that it occurred.
I decided against trying to return this error from the main function, or even something like a log.Fatal, since it's just for cleanup, so stopping earlier isn't going to help anyone.
I ran a version of this PR with an intentional error in cleanup, and observed it did not fail the tests but did log:
https://github.com/runatlantis/atlantis/actions/runs/10356111645/job/28665262207?pr=4835#step:7:52
Found while working on #4582
> feat: Log error on cleanup in e2e

- e2e/e2e.go
- e2e/github.go
- e2e/vcs.go
- Have `DeleteBranch()` take the bare branch name, not `heads/<branchName>` (the latter is apparently a github implementation detail)
- Instead of hard-coding the semantics of the "status" of an atlantis run, defer into the VCS. For example, Github has a state called `failure` whereas gitlab has a state called `failed`, both of which mean the same thing, and indicate that the run is done
Make the e2e tests more agnostic to which VCS they are being run on. This will make it more straightforward to add new VCSs.
The e2e tests themselves passing should be good enough.
Working towards #4582.
> chore: Make e2e tests more vcs agnostic

- scripts/e2e.sh
Make it so when the e2e.sh script ends, it also cleans up the background processes of atlantis and ngrok.
Additionally, quit the script early if atlantis or ngrok fail to start up.
While I was working on the e2e golang code, it ended up that multiple copies of both atlantis and ngrok were running on my computer, which got confusing.
Another annoyance was if atlantis or ngrok fail to start, the script kept going, then failed in a confusing way. Now the script makes sure the process stays up after the two second pause.
I ran the script locally. Also the CI ran successfully, including my new output.
> chore: Improve process management in e2e test

- runatlantis.io/docs/access-credentials.md
- server/controllers/github_app_controller.go
Adds the `actions:read` permission to the GitHub app. Both to the documentation and to the setup endpoint.
As of https://github.com/runatlantis/atlantis/commit/ed7b744695ca057ac2bd995b0f6bb6d92d2aa259, this permission is needed when the `--gh-allow-mergeable-bypass-apply` setting is enabled.
> fix: Permission for GitHub app to support mergeable minus apply check

- server/events/vcs/gh_app_creds_rotator.go
Change the log line to prevent logging the GitHub App token in logs.
- Resolves https://github.com/runatlantis/atlantis/issues/4060
- Tokens should not be in the logs due to security implications
Confirmed Atlantis continues to successfully start.
- Close https://github.com/runatlantis/atlantis/issues/4060
> fix: dont log GitHub app token in logs

- server/events/command_runner.go
* Reverts user team lookup behavior for autoplans to be conditional, instead of always performing a lookup
* Team authorization change in #4864 caused lookup behavior for autoplans to always fetch membership, instead of conditionally like comment commands.  This changed the required scope of Github tokens to add additional permissions that weren't needed.
* Fixes breaking change introduced in #4864
> fix: only lookup user team memberships if using team authz

- scripts/pin_ci_terraform_providers.sh
- server/controllers/events/testdata/null_provider_lockfile_old_version
Fixes the e2e tests. Some open PRs are failing on the e2e tests with an outdated lockfile. I've updated the null provider from 3.2.2. to 3.2.3, and locked it with the same platforms is seemed to be locked with before:
```
terraform providers lock -platform=linux_amd64 -platform=linux_arm64 -platform=darwin_amd64 -platform=darwin_arm64 
```
Current error: 
> running "/usr/local/bin/terraform init -input=false" in "/tmp/TestSimpleWorkflow_terraformLockFilesimple_with_plan_comment_lockfile_staged3170145570/001/repos/runatlantis/atlantis-tests/2/default": exit status 1
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of hashicorp/null from the dependency lock file
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of …
> fix: Update lock for e2e tests

- pnpm-lock.yaml
- runatlantis.io/docs/custom-workflows.md
- runatlantis.io/docs/repo-and-project-permissions.md
seeing
```
markdownlint-cli2 v0.13.0 (markdownlint v0.34.0)
Finding: runatlantis.io/**/*.md
Linting: 53 file(s)
Summary: 1[8](https://github.com/runatlantis/atlantis/actions/runs/10985180193/job/30496678585?pr=4934#step:3:9) error(s)
Error: runatlantis.io/docs/custom-workflows.md:486:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash] https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md004.md
Error: runatlantis.io/docs/custom-workflows.md:486 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- Appending tags to every reso..."] https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md032.md
Error: runatlantis.io/docs/custom-workflows.md:487:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash] …
```
> fix: fix markdown lint errors

- .github/workflows/testing-env-image.yml
- perm removal from testing-env-image
- Due to the action pushing an image on merge which failed cause of the `read` perms
- The atlantis-image action isn't affected
- Previous PR #4954 
- https://github.com/runatlantis/atlantis/actions/runs/11056560874/job/30718385762
> ci: perm removal from testing-env-image

- server/core/terraform/terraform_client.go
Small follow up to #4499. When working with OpenTofu, Atlantis will talk about terraform in some of the error messages. This is confusing when using OpenTofu. For example, when setting `ATLANTIS_DEFAULT_TF_VERSION=1.5.7` to get the latest version of Terraform published under the MPL, then migrating to tofu by setting `ATLANTIS_TF_DISTRIBUTION=opentofu` you will get this confusing message:
> error downloading terraform version 1.5.7: No such version: 1.5.7
This change will now output:
> error downloading tofu version 1.5.7: No such version: 1.5.7
Better UX for error cases
Just an error message change, so haven't done any detailed integration testing for this.
Follow up to #4499
> fix: Update error messages when working with OpenTofu

- runatlantis.io/docs/custom-workflows.md
- docs: add an anchor for native env vars
- It's difficult to navigate to the full list of environment variables
- It's far easier to create an anchor so these vars are linkable
N/A
- Here is the next linkable section https://www.runatlantis.io/docs/custom-workflows#environment-variable-env-command
> docs: add an anchor for native env vars

- Dockerfile
- docker-entrypoint.sh
By default, dumb init forward SIGTERM signals to all child processes. This causes Atlantis to shutdown ungracefully when running a Terraform command. The process tree looks as follows:
> dumb-init -> atlantis -> sh -> terraform -> provider(s).
When the container runtime stops the container while Atlantis is running a Terraform command (E.g Kubernetes node scale down), dumb-init will forward the SIGTERM to all these processes in reverse order. Both Terraform and Atlantis will trap the signal and try to exit gracefully, however the provider will crash, resulting in Atlantis commenting the following on a PR:
```
Stopping operation...
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
╷
│ Error: execution halted
│ 
│ 
╵
╷
│ Error: …
```
> fix: Run dumb-init with --single-child for graceful termination

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/server-configuration.md
- server/events/vcs/git_cred_writer.go
- server/events/vcs/github_client_internal_test.go
- server/events/vcs/github_client_test.go
- server/events/vcs/github_credentials.go
- server/events/vcs/github_token_rotator.go
- server/events/vcs/github_token_rotator_test.go
- server/server.go
- server/user_config.go
Adds a `gh-token-file` server setting that can be used instead of `gh-token`. The token is read from disk as part of the GitHub client transport, allowing the token to be rotated without needing to restart the Atlantis process. I've also re-used the `.git-credentials` token rotator from the GitHub app integration to ensure that `write-git-creds` will update the `.git-credentials` file as the `gh-token-file` is updated. This only works for GitHub, we use a --gh-* prefixed flag like the other gh configs. This could be extended to the other VCS options as needed.
We run about ~150 Atlantis instances in our organisation in our GitHub org. GitHub have a hard limit on 100 GitHub apps per org, and charge a seat per service account user. To get around these challenges we have developed a GitHub …
> feat: GitHub - Support loading git token from disk

- runatlantis.io/docs/using-atlantis.md
Fix the auto-merge merge method link in the 'Using Atlantis' docs.
```
http://localhost:8080/docs/using-atlantis.html
id #how-to-set-merge-method-for-automerge not found	http://localhost:8080/docs/automerging.html#how-to-set-merge-method-for-automerge
```
> chore(docs): Fix Using Atlantis Merge Method Link

- .github/workflows/website.yml
Replace `**.js` with `runatlantis.io/**` in the website GitHub workflow link-check job filter.
So that any changes to website files in PRs will trigger the link-check job.
> chore(workflow): Fix Website GitHub Workflow link-check Job Filter

- runatlantis.io/docs/provider-credentials.md
Fix the markdown formatting on `provider-credentials.md`
```
Error: runatlantis.io/docs/provider-credentials.md:61 MD058/blanks-around-tables Tables should be surrounded by blank lines 
https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md058.md
```
> chore(docs): Fix formatting on provider-credentials.md

- .github/workflows/website.yml
Add a `User-Agent` header to the muffet step in the Website Link GitHub check.
The `muffet` step is frequently failing with the following:
```
http://localhost:8080/contributing/glossary.html
timeout	https://azure.microsoft.com/en-us/products/devops
```
There is an issue discussing this here: https://github.com/raviqqe/muffet/issues/306 and the solution is to add a `User-Agent` header to muffet.
Testing this locally, setting the User-Agent to `curl` fixed the Microsoft site, but then caused 429 errors on  https://developer.hashicorp.com/terraform/cdktf. Setting the User-Agent to `muffet` solved both issues.
> chore: Add User Agent to Website Link GitHub Check Muffet Step

- server/events/event_parser.go
- server/events/event_parser_test.go
- server/server.go
Quick follow up to #3208.
I noticed during testing that we need to also set the token file here. I believe I must have been testing by running against a PR with a commit that was already checked out on the persistent volume. Atlantis detected that it didn't need to perform a `git clone` command.
I've updated my testing to include testing with a new PR and new commit, forcing a clean checkout.
The GitHub client credentials are separate to the git client credentials, so we must set the token file here too when configuring Atlantis for a token file rather than the token directly.
Tested this with a clean clone in my environment.
#3208
> fix: GitHub - Support Token File for Git Commands

- server/controllers/events/events_controller.go
Fixes [https://github.com/runatlantis/atlantis/security/code-scanning/12](https://github.com/runatlantis/atlantis/security/code-scanning/12)
To fix the reflected cross-site scripting vulnerability, we need to ensure that any user-controlled input is properly sanitized or escaped before being included in the HTTP response. In this case, we can use the `html.EscapeString` function from the `html` package to escape any potentially dangerous characters in the `githubReqID` before including it in the `resp.body`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> fix: code scanning alert no. 12: Reflected cross-site scripting

- server/events/templates/plan_success_wrapped.tmpl
Without this, we would typically get
```
Plan: 3 to add, 0 to change, 0 to destroy.:twisted_rightwards_arrows: Upstream was modified, a new merge was performed.
```
With this, we should be getting whitespace before the `:twisted_rightwards_arrows` part.
Without this, we would not have our beautiful :twisted_rightwards_arrows: rendered as an emoji.
> fix: rendering of merge emoji when upstream was modified

- server/events/markdown_renderer_test.go
Fix the failing markdown renderer test in the `release-0.27` branch.
- https://github.com/runatlantis/atlantis/pull/4389
> chore: Markdown Renderer Test Fix (release-0.27)

- server/events/project_command_runner.go
detailed logging when prevent_self_approval is set to true
> chore: adding more detailed logs for policy approval

- Dockerfile
the tf support aligns with  https://endoflife.date/terraform
> chore: bump opentofu to 1.8.8, add tf 1.9.8, and drop 1.6/1.7 support

- .github/renovate.json5
per security policy doc, only supports 0.31 and 0.32, which are the most two recent releases. 
closes #5215
closes #5216
closes #5217
closes #5218
closes #5219
relates to https://github.com/runatlantis/atlantis/issues/2818
> chore(renovate): only support most two recent releases 0.31 and 0.32

- Dockerfile
bump ca-certificates to `20241121-r1` to fix CI build
> chore(deps): bump ca-certificates to `20241121-r1`

- .github/workflows/atlantis-image.yml
- README.md
Fix strategy so "skip build" has same matrix as "test" for build.
Otherwise these checks are never satisfied in situations where the build doesn't occur
This PR is not a good test of itself, since it changes the github CI file, thus triggering the builds explicitly :). After this is merged, I'll try another PR that shouldn't trigger a build and we'll confirm they are "skipped"
> chore: Fix build CI mismatch

- server/events/project_command_builder.go
Split up `buildAllCommandsByCfg` into several helper functions.
I went in to make a change to this function and found it to be very complicated (250+ lines!), so wanted to break it up before working on it. I imagine a lot of logic has been added to this important function over time, seems like it's worth fixing up.
Pulling out the `shouldSkipClone` also made it clear that the repoCfg determined in that function is *different* from the one used to determine the merged projects. In the previous code that wasn't clear, just a comment saying "this is discarded" that if you missed you might end up reusing accidentally.
It also allowed me to refactor the code to make better use of the "happy path" pattern to prevent nested else statements.
I just relied on the existing unit tests, I'm happy to …
> chore: Split up buildAllCommandsByCfg for readability and modularity

- server/events/project_command_builder.go
Collapse and clarify logs in determining merged project configs.
I didn't quite understand this when going through #5245, but the logs and comments under automatic detection made it seem like it was conditional on other projects not being found, however that's not the case. If automatic detection is enabled, we simply run it. Maybe that used to be the case, but now this log and comment is a bit misleading and redundant.
This also allowed fewer parameters to be passed into this function, which feels more correct to me; it's a detail that this function doesn't quite "know" that the reason hasRepoCfg is false is that it couldn't find the file. That logging can and should happen closer to when the parsing actually happens.
Normal CI
> chore: Clarify logs in determining merged project configs

- runatlantis.io/docs/server-configuration.md
- docs: github emu mention on hiding prev comments
- Github EMU should be 1:1 with non github EMU
- This is only for the github user. 
I verified in my own environment
- https://github.com/runatlantis/atlantis/blob/52f8e05034b71ce1ec008a324bc0ffd13f113800/server/events/vcs/github_client.go#L292-L293
> docs: github emu mention on hiding prev comments

- .github/workflows/atlantis-image.yml
we implemented image signing in #5185. unfortunately a logic flaw was introduced in this change which broke multi-architecture builds. the change modified the build steps to use a matrix build. however, the matrix was incorrectly configured, which caused the last arch in the build sequence (linux/arm/v7) to overwrite the other 2 tags. effectively, we steamrolled ourselves.
this change corrects the error by simplifying the matrix. instead of using six parallel build steps, we use a single build step which pushes a multi-arch manifest in one shot. this has the added benefit of speeding builds up. 
atlantis guarantees the availability of images for multiple CPU architectures. this promise must be kept.
tested by building images in my fork.
* debian: …
> fix: ensure multi-image builds succeed

- server/events/comment_parser.go
- server/events/comment_parser_test.go
Small change to trim backticks (`` ` ``) from MR comments to help with copy pasting atlantis commands from Gitlab. This is in addition to trimming whitespace.
Gitlab adds backticks when copy pasting code, which currently fails with atlantis and requires having to remove them before submitting the comment.
For example, copying this pre-populated code
Becomes 
Added a unit test
> feat: Trim backticks from MR comments (for Gitlab)

- go.mod
- go.sum
- server/events/vcs/github_client.go
- server/events/vcs/github_client_test.go
_This is a recreation of #4926 as that one seems abandoned by the author_
* Add retry mechanism for GitHub API secondary rate limit
* Implement a retry mechanism for GitHub client API calls when encountering secondary rate limit responses.
* In large-scale deployments, a single PR can affect hundreds of projects.
* When attempting to plan/apply for a non-mergeable PR, Atlantis may try to set the PR status hundreds of times in a short period, triggering GitHub's secondary API rate limit.
* This results in Atlantis appearing to stop mid-operation: some projects are marked as failed, and no comments are posted.
* This issue can occur in other scenarios where Atlantis is used at scale.
* Utilize the go-github-ratelimit library, as recommended in the official go-github README:
> "You can use …
> feat: Add rate limit handling for GitHub client

- server/core/config/valid/repo_cfg.go
- server/core/config/valid/repo_cfg_test.go
- server/events/project_command_builder.go
Simplify use of the doublestar Match for ignore paths by using MatchUnvalidated.
We already explicitly validate all patterns when parsing the config, there's no reason to run Match(), which does additional validation and optionally returns an error.
I didn't quite understand how this package worked until a conversation with the maintainer (https://github.com/bmatcuk/doublestar/issues/85), and now I think this is the correct approach.
Running unit tests.
> chore: Simplify use of the doublestar Match for ignore paths

- go.mod
Ran `go mod tidy`
Good to keep tidy. I recently added this dependency, not sure why it was "indirect" before, but it's a real dependency.
N/A
N/A
> chore: Go mod tidy

- .github/workflows/atlantis-image.yml
Reverts runatlantis/atlantis#5253
This needs reverting following on from https://github.com/runatlantis/atlantis/pull/5257 as it is no longer correct, and is blocking the CI of PRs that don't build images, e.g.: https://github.com/runatlantis/atlantis/pull/5276
> chore: Revert "chore: Fix build CI mismatch"

- server/core/config/parser_validator.go
- server/core/config/parser_validator_test.go
- server/core/config/raw/autodiscover.go
- server/core/config/raw/global_cfg.go
- server/core/config/raw/project.go
- server/core/config/raw/raw.go
- server/core/config/raw/raw_test.go
Remove references to `pkg/errors` from server/core/config packages.
Per #5269 we should be removing this dependency. I picked this package first because it has a somewhat complicated use of the pkg/errors and I wanted to make sure it worked as expected.
Running unit tests
- Partially addresses: #5269
> chore: Remove some references to pkg/errors

- server/events/project_command_builder.go
Remove all usages of `errors.Cause()`
We are replacing `pkg/errors` with the standard library `errors` (#5269). One method the standard library does not have is Cause(). It *does* have errors.Is, which is in fact just a thin wrapper around the std library's (https://github.com/pkg/errors/blob/master/go113.go#L16), so even though this package is importing and using pkg/errors, when it is changed to import and use std library, this new line will be a no-op.
Ran unit tests.
- Partially addresses: #5269
> chore: Remove usage of errors.Cause

- .goreleaser.yml
`archives.format` is deprecated see https://goreleaser.com/deprecations/#archivesformat
```
• DEPRECATED: archives.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
```
> chore(goreleaser): update for deprecated attributes

- server/events/vcs/gitlab_client.go
Refactor the way retries work in `UpdateStatus` in gitlab.
I noticed this while working on #5269; we can't prove that by the time we get to "return err" we'll actually have a non-nil error to wrap. In practice this won't happen, if you carefully follow the paths (and note that `StatusConflict` will cause err to be non-nil), but it's hard to see. Additionally there were comments like "if we get here, then..." and "return the error, which might be nil", which to me is a code smell that the logic is hard to follow.
Instead I refactored following the example of the retry library we were using https://pkg.go.dev/github.com/jpillora/backoff
Another oddity that took me a bit to understand was that, whether there was a conflict or not, we retry if there's an error and we haven't hit our max …
> chore: Refactor retries in gitlab set status

- server/events/vcs/azuredevops_client.go
Fix some errors in azuredevops that are unintentionally returning nil.
Each of these call sites is proceeded by `if err != nil { return }`, so if we reach these lines of code, we know that `err` is `nil`. However, `errors.Wrap` is documented to return nil if err is nil. https://pkg.go.dev/github.com/pkg/errors#Wrap. This means we are actually returning a `nil` error in these cases, which is not intentional
Unit tests.
Found while working on #5269.
Similar issue to #5294.
> fix: Unintentional nil errors in azuredevops client

- server/controllers/events/events_controller.go
- server/controllers/websocket/mux.go
- server/core/db/boltdb.go
- server/core/redis/redis.go
- server/core/runtime/models/shell_command_runner.go
- server/events/pending_plan_finder.go
- server/events/vcs/azuredevops_client.go
- server/events/vcs/gitlab_client.go
- server/server.go
- testdrive/testdrive.go
Add nil checks before returning wrapped errors.
Partially in prep for #5269, since if we return `fmt.Errorf("... : %w", err)` when err is nil, it won't, as `errors.Wrap(err, "...")` does in this situation, return nil.
Additionally, I find that relying on `errors.Wrap(err, "...")` to return `nil` if err is nil a bit hard to read. It can also lead to subtle bugs like #5294 and #5312.
I also put a few errors that were split between lines onto one line, which is more specifically in prep for #5269 (which I am writing a script to do replacements for mechanically).
Just running unit tests.
Cleaning up code to make #5269 a bit simpler (though I think this change is worth doing on its own).
> chore: Add nil checks before returning wrapped error

- e2e/gitlab.go
- runatlantis.io/contributing/events-controller.md
- runatlantis.io/docs/access-credentials.md
- runatlantis.io/docs/command-requirements.md
- runatlantis.io/guide/testing-locally.md
updated gitlab links (both ee and ce paths are no longer applicable, not sure when that happened, but there was [some discussion on reddit](https://www.reddit.com/r/gitlab/comments/18xkwlu/gitlabce_documentation/) one year ago).
updating the links to new one.
> docs: update gitlab links

- .github/workflows/test.yml
bump ngrok to 3.19.1 
need to figure out a way to have renovate to update it, there is some discussions on archlinux about it, https://aur.archlinux.org/packages/ngrok
> chore(deps): bump ngrok to 3.19.1

- README.md
relates to https://github.com/runatlantis/atlantis/pull/5336
> fix: update cncf invite link

- .github/workflows/testing-env-image.yml
fix testing-image push flow issue
```
ERROR: failed to solve: failed to push ghcr.io/runatlantis/testing-env:2025.03.04: unexpected status from POST request to https://ghcr.io/v2/runatlantis/testing-env/blobs/uploads/: 403 Forbidden
```
https://github.com/runatlantis/atlantis/actions/runs/13644220126/job/38140024300#step:9:595
relates to #5271
> fix(workflows/testing-env-image): add `packages: write` for ghcr image push

- Dockerfile
https://github.com/runatlantis/atlantis/pull/5235 for release 0.32
> chore(deps): bump ca-certificates to `20241121-r1` (release-0.32)

- .github/renovate.json5
drop 0.31 release line support (we only support latest two release lines)
closes #5399
closes #5400
closes #5404
closes #5406
> chore(deps): drop 0.31 release line support

- Dockerfile
- Bumps Debian base image from 12.8 to 12.9
- Fixes security vulns outlined on [this page](https://www.debian.org/News/2025/20250111)
- Verified image builds using `docker build -t logan-test .`
- Closes #5386
> chore: Bump Debian from 12.8 to 12.9

- scripts/e2e.sh
we used to have `runatlantis` and `run-atlantis` orgs, both have the `atlantis-tests` repo, which is a big confusing. after I setup the repo sync from `github.com/runatlantis/atlantis-tests` to `gitlab.com/runatlantis/atlantis-tests`, @jamengual has deleted `run-atlantis/atlantis-tests` repo. So converging the refs in here. 
cc @lukemassa
> chore: update gitlab repo ref

- .github/release.yml
- ci(release): separate section for docs and deps
- Generally people only care about changes to the binary than the website
- Let's keep website and docs as separate sections
- No reason to ignore renovatebot as users generally care about updates to dependencies. We can move that to a separate section too.
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes?search-overlay-open=true
> ci(release): separate section for docs and deps

- cmd/server.go
- cmd/server_test.go
- runatlantis.io/docs/api-endpoints.md
- runatlantis.io/docs/server-configuration.md
- server/server.go
- server/user_config.go
This PR adds a new `--enable-profiling-routes` flag that when true will mount the `net/http/pprof` endpoints, allowing to perform [continuous profiling] on the running server. This will allow a deeper inspection on how the application behaves, where the most CPU and memory is consumed, and so on. See [profiling Go programs] for additional information.
At Grafana Labs we use Atlantis with a large number of environments (740+) and when making a change that affects too many environments we have experienced slowness or OOM kills. We would like to make use of [Grafana Pyroscope](https://grafana.com/oss/pyroscope/) to investigate why this happens and hopefully contribute back.
Added flag test.
[continuous profiling]: https://grafana.com/docs/pyroscope/latest/introduction/continuous-profiling/ …
> feat: add HTTP pprof endpoints

- server/events/vcs/github_client.go
- GitHub client-side rate-limiting was introduced in v0.33.0.
- It was done so with the use of a hard-coded (i.e. not admin-configurable) "total sleep limit" client option, which allows developers to set a maximum total amount of time the rate-limiting client shall spend sleeping between requests. There is no documentation as to why that decision was made, that I was able to find.
- When the total amount of time sleeping exceeds this limit, further requests are not rate-limited, defeating the rate-limiting mechanism altogether and causing GitHub secondary rate limits.
- This means that, in a big enough deployment of Atlantis (one that would cause GitHub API request bursts big enough to exceed 1 minute of total sleep), the client-side rate-limiting mechanism is disabled, which is …
> fix: Remove GitHub rate-limit client total sleep limit

- runatlantis.io/docs/server-configuration.md
- server/events/event_parser.go
- server/events/event_parser_test.go
1)Changes for [Azure Devops Organization URL 2018 change](https://learn.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration)
2)Unit tests
All details in [here](https://github.com/runatlantis/atlantis/issues/5595)
More history in this [ticket](https://github.com/runatlantis/atlantis/issues/1858)
[x] I have tested my changes by running an Atlantis Image in ECS & AWS
Closes #5595
> feat: enable compatible change for legacy and new ADO url

- server/events/command_runner_test.go
- server/events/plan_command_runner.go
Updated Atlantis behavior to retain the apply lock when re-running plan if there are no changes.
Ensured the lock is only removed when actual changes are detected between re-runs
Addresses community-reported issue [#5568](https://github.com/runatlantis/atlantis/issues/5568) where users observed unintended lock removals during no-op plans.
Fixes an issue where Atlantis incorrectly removes the apply lock when a plan is re-run, even if no changes are detected.
Preserves expected workflow and safety in CI/CD pipelines by preventing premature unlocks
✅ Manually tested locally:
Created an apply lock by running plan and apply.
Re-ran plan without making any changes — lock was preserved as expected.
Introduced a change and re-ran plan — lock was correctly removed.
Verified this behavior in a …
> fix: preserve Atlantis apply lock after plan 

- .github/release.yml
This pull request includes a minor update to the `.github/release.yml` file. The change removes the lock emoji from the "Security changes" section title for consistency with the other section titles.
> fix(docs): generate release notes

- CONTRIBUTING.md
- docker-compose.yml
Closes #5680
See https://ngrok.com/docs/using-ngrok-with/docker/ for additional usage information on ngrok & Docker.
> fix: use the official ngrok image

- runatlantis.io/docs/access-credentials.md
This PR adds detail for creating tightly-scoped Personal Access Tokens when integrating with GitHub.
In order to save others the toil of trial and error.
I noted which requests failed in the logs and worked through each with the official PAT permissions doc as a reference, until all requests succeeded (from opening a PR, getting the statuses, the plan comment, commenting back `atlantis help` to closing the PR and seeing the final "locks deleted" comment)
https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28
> docs: add specific permissions required for GitHub PATs

- Dockerfile
Bumps the ca-certificates to the latest Alpine 3.21 version: https://alpine.pkgs.org/3.21/alpine-main-aarch64/ca-certificates-20250619-r0.apk.html
> build: bump ca-certificates to 20250619-r0

- runatlantis.io/docs/server-configuration.md
- Removed non-existent flags that were never implemented:
- --enable-lock-retry (claimed v0.23.0+, never existed)
- --enable-plan-queue (claimed v0.23.0+, never existed)
- --lock-retry-delay (claimed v0.23.0+, never existed)
- --lock-retry-max-attempts (claimed v0.23.0+, never existed)
- Fixed incorrect version annotations:
- --api-secret: v0.1.0+ → v0.22.2+ (added in PR #2940)
- Redis flags: v0.48.0+ → v0.19.9+ (added in PR #2491)
- SSL flags: v0.44.0+ → v0.2.4+ (added in PR #233)
- TFE flags: v0.45.0+ → v0.8.3+ (added in PR #706)
- GitLab flags: v0.40.0+ → v0.2.0+ (added in PR #190)
- Gitea flags: v0.32.0+ → v0.28.0+ (added in PR #4229)
- Various other flags corrected to their actual introduction versions
- Early flags: v0.1.0+ → v0.1.3+ (CLI was added in v0.1.3)
This fixes the …
> fix: correct version annotations and remove non-existent flags from docs

- runatlantis.io/docs/repo-level-atlantis-yaml.md
Replace HTML badge elements with clean YAML comments in the 'Example Using All Keys' section of the repo-level atlantis.yaml documentation to improve readability while preserving version information.
- **Converted HTML badges to comments**: Replaced `<Badge text="vX.X.X+" type="info"/>` with `# Available since vX.X.X`
- **Improved readability**: The YAML example is now much cleaner and easier to read
- **Maintained version info**: All version information is preserved as inline comments
- **Better copyability**: Users can now easily copy the YAML without HTML elements
**Before:**
```yaml
version: 3 <Badge text="v0.1.0+" type="info"/>
automerge: true <Badge text="v0.15.0+" type="info"/>
```
**After:**
```yaml
version: 3 # Available since v0.1.0
automerge: true # Available since v0.15.0
``` …
> docs: replace version badges with comments in repo-level atlantis.yaml example

- CODE_OF_CONDUCT.md
This pull request makes a small update to the project's Code of Conduct, specifically clarifying the contacts for reporting unacceptable behavior. The change updates the list of project team members to message on Slack if there are any issues.
- Updated the enforcement section in `CODE_OF_CONDUCT.md` to direct reports to `@PePE Amengual`, `@Dylan Page`, or `@chenrui333` instead of `@lkysow`.
closes https://github.com/runatlantis/atlantis/issues/3745
> docs: Update enforcement contacts in CODE_OF_CONDUCT.md

- Dockerfile
- Fixed Docker build failures by updating Alpine package versions to match Alpine 3.21.3
- Added renovate annotations for automatic package updates
- Changed from fuzzy to exact version matching for better reproducibility
All PRs were failing with Docker build errors due to outdated Alpine package versions, specifically the ca-certificates package which was trying to use version `20250619-r0` that doesn't exist in Alpine 3.21.3.
1. **Updated all Alpine package versions** to the correct versions available in Alpine 3.21.3:
- ca-certificates: 20250619-r0
- curl: 8.12.1-r1
- git: 2.47.3-r0
- unzip: 6.0-r15
- bash: 5.2.37-r0
- openssh: 9.9_p2-r0
- dumb-init: 1.2.5-r3
- gcompat: 1.1.0-r4
- coreutils-env: 9.5-r2
2. **Added renovate annotations** for each package using the repology datasource, …
> fix: update Alpine package versions to fix Docker build failures

- Dockerfile
Backport of PR #5760 to fix Docker build failures in the release-0.35 branch.
All PRs targeting the release-0.35 branch are failing with Docker build errors due to outdated Alpine and Debian package versions. This includes security updates like PR #5756.
This PR backports the package version fixes from main branch:
- ca-certificates: 20241121-r1 → 20250619-r0
- curl: 8.12.1-r1
- git: 2.47.3-r0
- unzip: 6.0-r15
- bash: 5.2.37-r0 (also in builder stage)
- openssh: 9.9_p2-r0
- dumb-init: 1.2.5-r3
- gcompat: 1.1.0-r4
- coreutils-env: 9.5-r2
- ca-certificates: 20230311+deb12u1
- curl: 7.88.1-10+deb12u12
- git: 1:2.39.5-0+deb12u2
- unzip: 6.0-28
- openssh-server: 1:9.2p1-2+deb12u7
- dumb-init: 1.2.5-2
- gnupg: 2.2.40-1.1
- openssl: 3.0.17-1~deb12u2
1. **Alpine**: Changed from fuzzy version …
> fix: backport Alpine and Debian package version fixes to release-0.35

- .github/workflows/atlantis-image.yml
- Dockerfile
Backport of PR #5760 to fix Docker build failures in the release-0.34 branch.
All PRs targeting the release-0.34 branch will fail with Docker build errors due to outdated Alpine and Debian package versions, similar to the issue seen in release-0.35.
This PR backports the package version fixes from main branch:
- ca-certificates: 20241121-r1 → 20250619-r0
- curl: 8.12.1-r1
- git: 2.47.3-r0
- unzip: 6.0-r15
- bash: 5.2.37-r0 (also in builder stage)
- openssh: 9.9_p2-r0
- dumb-init: 1.2.5-r3
- gcompat: 1.1.0-r4
- coreutils-env: 9.5-r2
- ca-certificates: 20230311+deb12u1
- curl: 7.88.1-10+deb12u12
- git: 1:2.39.5-0+deb12u2
- unzip: 6.0-28
- openssh-server: 1:9.2p1-2+deb12u7
- dumb-init: 1.2.5-2
- gnupg: 2.2.40-1.1
- openssl: 3.0.17-1~deb12u2
1. **Alpine**: Changed from fuzzy version matching …
> fix: backport Alpine and Debian package version fixes to release-0.34

- server/events/vcs/gitlab_client.go
- server/events/vcs/gitlab_client_test.go
Pull gitlab is mergeable logic into a helper function
It's easier to read and to test if the complex logic lives in its own "pure" function.
Specifically, we didn't have any test for if a project has AllowMergeOnSkippedPipeline but we fail pipeline. This is because when added a few more tests here #5863, it was too difficult to mock in a separate project.
I tried to do that in this PR, but it was really difficult to plumb into the mocked HTTP server, and honestly the logic we were testing was being spread around so much it really wasn't even a useful test.
Added new tests
N/A
> chore: Pull gitlab is mergeable logic into a helper function
