README.md
Had to remove the "fork" because code searches didn't work.
Fixes #52
=> Add credit to Hootsuite

README.md
=> Update README to repo-whitelist clearer.

main.go
=> Get configs from environment variables

README.md
`-tfvars=` isn't a valid terraform argument.
=> docs: Minor correction with regards to `-var-file`

Gopkg.lock, server/events/vcs/gitlab_client.go, vendor/github.com/lkysow/go-gitlab/merge_requests.go
Updated to a patched version of go-gitlab with the correct fields set.
Fixes #114
=> Fix bug with GitLab approvals not being required

README.md
Hi Luke!
Hopefully, you don't mind linking to a new project which I have just started.
PS: Check your email :)
=> Added a note about terraform-aws-atlantis project

bootstrap/bootstrap.go, bootstrap/utils.go
Previously, we started ngrok/atlantis server in the background and then
did a sleep to ensure the processes were running or just assumed they
were up. Now, we wait for a specific output to ensure those processes
are running before continuing on with the rest of the script.
Fixes #92.
=> Wait for ngrok/atlantis output during bootstrap

deployment.yaml, runatlantis.io/docs/deployment.md, server/server.go, server/server_test.go
=> Add /healthz endpoint.

runatlantis.io/docs/atlantis-yaml-reference.md, server/events/runtime/apply_step_runner.go, server/events/runtime/plan_step_runner.go, server/events/runtime/run_step_runner.go, server/events/runtime/run_step_runner_test.go, server/events/runtime/runtime.go, server/events/runtime/runtime_test.go, server/events/yaml/raw/project.go, server/events/yaml/raw/project_test.go
Env var is set to where Atlantis expects the planfile to be.
Fixes #168.
=>  Set PLANFILE environment variable in run step.

runatlantis.io/guide/atlantis-yaml-use-cases.md, server/events/project_command_builder_test.go, server/events/project_finder_test.go, server/events/yaml/parser_validator_test.go, server/events/yaml/raw/autoplan.go, server/events/yaml/raw/autoplan_test.go, server/events/yaml/raw/config_test.go, server/events/yaml/raw/project_test.go, server/testfixtures/test-repos/modules-yaml/atlantis.yaml
This is so .tfvars files match.
=> Change default when_modified to **/*.tf*

runatlantis.io/docs/deployment.md
Just a few broken links/anchors
=> Docs: Fix broken links

server/events/runtime/init_step_runner.go, server/events/runtime/init_step_runner_test.go
=> Return error if `terraform init` fails.

runatlantis.io/docs/atlantis-yaml-reference.md, server/events/runtime/run_step_runner.go, server/events/runtime/run_step_runner_test.go
Commits from @mootpt with small change to ensure tests cover difference between base and head repo.
=> Expose repo name, owner, and branch to run step runner for custom steps

.circleci/config.yml, Dockerfile, testing/Dockerfile
Hi!
This upgrades the used version of Terraform to 0.11.8.
Would be awesome to get a release very soon! 😄 
Thanks for supporting the project! 👍
=> Bum terraform version to 0.11.8

runatlantis.io/docs/deployment.md
Minor clarification in deployment.md RE how to use Atlantis with multiple GitLab repositories.
=>  Update instructions for multiple GitLab Repos. 

CONTRIBUTING.md
=> Add docs for how to run tests in Docker

helm/atlantis/templates/statefulset.yaml, helm/atlantis/values.yaml, server/events_controller_e2e_test.go, server/testfixtures/test-repos/simple-yaml/exp-output-apply-all.txt, server/testfixtures/test-repos/simple-yaml/exp-output-apply-default.txt, server/testfixtures/test-repos/simple-yaml/exp-output-apply-staging.txt, server/testfixtures/test-repos/simple/exp-output-apply-var-all.txt, server/testfixtures/test-repos/simple/exp-output-apply-var-default-workspace.txt, server/testfixtures/test-repos/simple/exp-output-apply-var-new-workspace.txt, server/testfixtures/test-repos/simple/exp-output-apply-var.txt, server/testfixtures/test-repos/simple/exp-output-apply.txt, server/testfixtures/test-repos/tfvars-yaml-no-autoplan/exp-output-apply-default.txt, server/testfixtures/test-repos/tfvars-yaml-no-autoplan/exp-output-apply-staging.txt, server/testfixtures/test-repos/tfvars-yaml/exp-output-apply-default.txt, server/testfixtures/test-repos/tfvars-yaml/exp-output-apply-staging.txt
- Set fsGroup for correct file permissions
- Set memory default to 256 since Atlantis doesn't need more unless you
have large TF
- Use latest version of Atlantis
Fixes #342
=> Fix helm chart.

.gitignore, helm/atlantis/Chart.yaml, helm/atlantis/OWNERS, helm/atlantis/README.md, helm/atlantis/templates/NOTES.txt, helm/atlantis/templates/secret-aws.yaml, helm/atlantis/templates/secret-gitconfig.yaml, helm/atlantis/templates/secret-webhook.yaml, helm/atlantis/templates/service.yaml, helm/atlantis/templates/statefulset.yaml, helm/atlantis/templates/tests/test-atlantis-configmap.yaml, helm/atlantis/templates/tests/test-atlantis-pod.yaml, helm/atlantis/test-values.yaml, helm/atlantis/values.yaml
Use helm chart from https://github.com/helm/charts/pull/8177
Fixes #361
=> Update local helm chart until official one lands.

helm/atlantis/templates/ingress.yaml
=> Use correct service name and port for ingress.

runatlantis.io/docs/deployment.md
There's no download link, added the one from getting-started.md
=> Added download link

server/events/runtime/apply_step_runner.go, server/events/runtime/apply_step_runner_test.go
-target doesn't work with terraform apply when the apply is being run on
a planfile (which is how Atlantis runs plan). We should give the user an
error if they attempt this.
Fixes #399
=> Warn if using -target flag with apply.

server/events/vcs/gitlab_client.go
Resolves [runatlantis/atlantis#413](https://github.com/runatlantis/atlantis/issues/413)
=> Add old path of moved file to list of modified files

server/events/runtime/init_step_runner.go, server/events/runtime/init_step_runner_test.go
adding -upgrade to terraform init & get cmd as per #443 
New to the project so not sure if this needs adding anywhere else. Just let me know if this isnt enough?
=> Add -upgrade to terraform init cmd

server/events/pending_plan_finder.go, server/events/pending_plan_finder_test.go
=> Ignore .terragrunt-cache dirs.

.circleci/config.yml, Dockerfile, testing/Dockerfile
Closes #530 
Thanks @chenrui333
=> Update Terraform to 0.11.13

Dockerfile
=> Use latest base image.

runatlantis.io/docs/deployment.md
Tweaking the language here to emphasize the bidirectional nature of communication needed for Atlantis.
=> Update docs around Atlantis Routing

cmd/help_fmt.go, cmd/server.go
A new help format that keeps everything at 80 chars.
=> New help format.

runatlantis.io/.vuepress/public/_redirects
=> Add redirects for old docs

server/events/comment_parser.go
=> Add missing closing backticks for help output

server/events/markdown_renderer.go, server/events/markdown_renderer_test.go, server/testfixtures/test-repos/automerge/exp-output-autoplan.txt, server/testfixtures/test-repos/modules-yaml/exp-output-autoplan.txt, server/testfixtures/test-repos/server-side-cfg/exp-output-autoplan.txt, server/testfixtures/test-repos/simple-yaml/exp-output-apply-all.txt, server/testfixtures/test-repos/simple-yaml/exp-output-autoplan.txt, server/testfixtures/test-repos/simple/exp-output-apply-var-all.txt, server/testfixtures/test-repos/tfvars-yaml/exp-output-autoplan.txt
Fixes #604 
Bitbucket's custom markdown renderer :shakesfistat:
=> Add newline so bitbucket formats markdown

server/events_controller.go
Should help with folks debugging, especially for BB Server.
=> Log repo name if does not match whitelist

server/events/vcs/bitbucketcloud/client.go, server/events/vcs/bitbucketcloud/client_test.go, server/events/vcs/bitbucketcloud/models.go
=> Switch to Bitbucket 2.0 API for mergeable check

Dockerfile, docker-base/Dockerfile
=> Upgrade to alpine 3.10

.circleci/config.yml, Dockerfile, testing/Dockerfile
Upgrade terraform version to 0.12.4
=> Upgrade terraform to 0.12.4

.circleci/config.yml, Dockerfile, testing/Dockerfile
Relates to #708
Keep terraform up to date :)
=> Upgrade terraform to 0.12.5

runatlantis.io/docs/deployment.md
This fixes a typo in Docker customisation documents.
=> Fix terragrunt typo

server/events/vcs/github_client.go, server/events/vcs/github_client_test.go
=> Fix for Issue 727

server/server.go, server/server_test.go, server/web_templates.go
=> Issue 720: display workspace name in locks UI list 

.circleci/config.yml, Dockerfile, testing/Dockerfile
=> tf: v0.12.10

server/events/runtime/plan_step_runner.go
=> Log output of failed terraform workspace new cmd

runatlantis.io/docs/deployment.md
This adds a note to the docs for the `volumeMounts` when using a StatefulSet in Openshift.
=> Documentation update for StatefulSet deployment in Openshift

.circleci/config.yml, Dockerfile, testing/Dockerfile
=> Bump terraform to  v0.12.14

server/events/event_parser.go, server/events/event_parser_test.go, server/events/vcs/fixtures/fixtures.go
AzureDevops: Support slashes in branch names
=> Fixes #835

kustomize/bundle.yaml, runatlantis.io/docs/deployment.md
=> Fixing Kustomization bundle and clarifying Kustomize documentation

cmd/server.go
Was getting an azdo warning when not using azdo
=> Only warn about azdo if flag set

.circleci/config.yml, Dockerfile, testing/Dockerfile
=> tf 0.12.17

docker-entrypoint.sh
Resolves https://github.com/runatlantis/atlantis/issues/870
=> correctly identify atlantis subcommands in docker entrypoint

.circleci/config.yml, Dockerfile, testing/Dockerfile
=> terraform 0.12.18

runatlantis.io/docs/custom-workflows.md
=> Document env step

cmd/server.go, cmd/server_test.go, runatlantis.io/docs/server-configuration.md, server/events/command_runner.go, server/events/command_runner_test.go, server/events/yaml/raw/project_test.go, server/server.go, server/user_config.go
* Closes #884
* Carries awesome work from @kinghrothgar in #885
* Closes #885
=> Added flag --silence-fork-pr-errors

runatlantis.io/docs/server-side-repo-config.md
It was a copy-paste of allowed_overrides.
Please verify that I got the default value and description right.
=> Fix docs for server-side repo config allow_custom_workflows

server/events/yaml/raw/step.go, server/events/yaml/raw/step_test.go
This is currently preventing us from autogenerating our atlantis configuration using the existing typings, would be great to get this in!
=> Implement marshal functions for Step

server/events_controller.go, server/events_controller_test.go
Prevents pull request updated events from triggering autoplan when the event was caused by a change in approvals.
=> Azure Devops - Fixes #946

runatlantis.io/docs/server-configuration.md
See discussion in https://github.com/runatlantis/atlantis/pull/994#discussion_r416914804
=> Add note about how to set boolean flags

Dockerfile
Fixes https://github.com/runatlantis/atlantis/issues/869#issuecomment-633526563
=> Use atlantis-base:v3.3 with git-lfs

runatlantis.io/docs/access-credentials.md, runatlantis.io/docs/server-configuration.md
Various clarifications and improvements to documentation
=> Update documentation for GitHub App and Configuration Flags

docker-base/Dockerfile
Upgrading the base container to the latest version release of gosu.
=> Upgrading base container to latest gosu.

.circleci/config.yml, Dockerfile, testing/Dockerfile
=> bump to tf-0.12.28

docker-base/Dockerfile
Upgrading to the latest version of Alpine Linux.
This provides a few upgrades to the base libs.
=> Upgrading the base container.

Dockerfile
=> Upgrade atlantis-base to v3.5

runatlantis.io/docs/deployment.md
=> Update helm deployment instructions for the new Helm repo

.circleci/config.yml, Dockerfile, testing/Dockerfile
Signed-off-by: Rui Chen <rui@meetup.com>
=> chore(deps): terraform 0.13.4

runatlantis.io/docs/access-credentials.md, runatlantis.io/docs/deployment.md, runatlantis.io/guide/testing-locally.md
https://app.circleci.com/pipelines/github/runatlantis/atlantis/484/workflows/b88e1ab2-3be7-4967-b821-f7867b78ce2f/jobs/5487
=> Fix broken links

.github/dependabot.yml
- chore(deps): add dependabot for go modules
- chore(deps): support docker
---
This would automate the dependency updates.
=> chore(deps): add dependabot support

.circleci/config.yml, Dockerfile, testing/Dockerfile
- chore(deps): terraform 0.14.0
- add 0.13.5 as avail version
=> chore(deps): terraform 0.14.0

.circleci/config.yml, Dockerfile, testing/Dockerfile
Reverts runatlantis/atlantis#1305
=> Revert "chore(deps): terraform 0.14.2"

.circleci/config.yml, Dockerfile, scripts/e2e.sh, testing/Dockerfile
Reverts runatlantis/atlantis#1307
=> chore(deps): terraform 0.14.2

runatlantis.io/docs/access-credentials.md, runatlantis.io/guide/testing-locally.md
Fixes anchor name changes in the Bitbucket Cloud docs
=> fix dead anchor in bitbucket docs

runatlantis.io/docs/custom-workflows.md, runatlantis.io/docs/pre-workflow-hooks.md, server/events/runtime/pre_workflow_hook_runner.go, server/events/runtime/pre_workflow_hook_runner_test.go, server/events/runtime/run_step_runner.go, server/events/runtime/run_step_runner_test.go
=> Feature: Add HEAD_COMMIT env var

runatlantis.io/docs/server-configuration.md, runatlantis.io/docs/server-side-repo-config.md
Initial barebones documentation. Will be adding more examples and better docs during the beta.
=> Add policy checking configuration docs

runatlantis.io/docs/custom-workflows.md, runatlantis.io/docs/policy-checking.md, server/events/runtime/executor.go, server/events/runtime/mocks/mock_versionedexecutorworkflow.go, server/events/runtime/policy/conftest_client.go, server/events/runtime/policy/conftest_client_test.go, server/events/runtime/policy_check_step_runner.go, server/events/runtime/policy_check_step_runner_test.go, server/events/yaml/raw/step.go, server/events_controller_e2e_test.go, server/testfixtures/test-repos/policy-checks-extra-args/atlantis.yaml, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-apply-failed.txt, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-apply.txt, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-approve-policies.txt, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-auto-policy-check.txt, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-auto-policy-check.txt.act, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-autoplan.txt, server/testfixtures/test-repos/policy-checks-extra-args/exp-output-merge.txt, server/testfixtures/test-repos/policy-checks-extra-args/main.tf, server/testfixtures/test-repos/policy-checks-extra-args/policies/policy.rego, server/testfixtures/test-repos/policy-checks-extra-args/repos.yaml
This should allow us to support flags such as `--all-namespaces`
=> Add extra args support to policy check step runner.

README.md
The site would be shutdown July 1st
---
=> doc: remove microbadger ref

runatlantis.io/docs/policy-checking.md, runatlantis.io/docs/server-side-repo-config.md
to improve the docs based on https://github.com/runatlantis/atlantis/issues/1607
=> Clarifying policy checking docs

.circleci/config.yml, runatlantis.io/docs/requirements.md, runatlantis.io/docs/terraform-cloud.md
Should fix
> error when reading response headers: small read buffer. Increase ReadBufferSize.
errors
=> Increase buffer size for website link check

.github/workflows/atlantis-base.yml, docker-base/Dockerfile
=> workflow: automate atlantis-base image build

Dockerfile
=> docker: update atlantis-base per ghcr.io migration

.circleci/config.yml
=> ci: remove docker_master job in circleci

.circleci/config.yml
=> ci: update to use ghcr.io images

server/events/project_command_context_builder.go
=> Fix policy check loading the tf version

.github/workflows/atlantis-image.yml
=> workflow: add steps for releasing tagged images

.github/workflows/test.yml
Brought this over from our fork
=> workflow: add tester gh action

.circleci/config.yml, .github/workflows/test.yml, .github/workflows/testing-env-image.yml, CONTRIBUTING.md
replacing https://hub.docker.com/r/runatlantis/testing-env
similar to #1648
=> workflow: add testing-env image build/publish process

server/server.go
=> fix a log error typo

runatlantis.io/docs/apply-requirements.md
It generated confusing ToC/menu
=> Fix title level

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> release: 0.17.5

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> release: 0.18.0

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> release: 0.18.1

server/core/terraform/terraform_client.go
Fixes #1517 and basically is a rebased version of #1578.
=> Fix support for terraform workspaces

.circleci/config.yml, Dockerfile, testdrive/utils.go, testing/Dockerfile
Upgrading to the latest Terraform release
=> deps: terraform 1.1.5

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> release: 0.18.5

server/events/vcs/gitlab_client_test.go
=> fix(gitlab): update tests

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> release: 0.19.1

.github/workflows/test.yml
=> workflow(tester): fix gotest runs for fork PRs

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> Release v1.9.4

CHANGELOG.md
Add changelog section as a follow-up of https://github.com/runatlantis/atlantis/pull/2362
=> Add section for --var-file-allowlist in changelog

CHANGELOG.md, kustomize/bundle.yaml, main.go
=> release v0.19.7

.circleci/config.yml, runatlantis.io/docs/using-slack-hooks.md
This PR is like #2407 
CI on master branch failed.
https://app.circleci.com/pipelines/github/runatlantis/atlantis/2487/workflows/504291f6-34ea-4e9a-b8c4-648b1cc39780/jobs/10679
=> Fix   website_link_check CI error

server/controllers/api_controller.go
=> Allow manual PR number

runatlantis.io/docs/repo-level-atlantis-yaml.md, server/events/apply_command_runner.go, server/events/plan_command_runner.go, server/events/project_command_pool_executor.go
it's just two copying project contexts, so I think it isn't bad
=> feat: support parallel execution with order groups

.circleci/config.yml, Dockerfile, testdrive/utils.go, testing/Dockerfile
Includes some useful new features like optional variables
=> deps: bump tf to 1.3.0

Dockerfile
Base atlantis docker file of same alpine version with latest security updates.
=> Golang alpine update

.github/workflows/atlantis-image.yml
Reverts runatlantis/atlantis#2556
=> Revert "Fix concurrency in `atlantis-image` workflow"

runatlantis.io/docs/apply-requirements.md
docs: typo ATLANTIS_GH_ALLOW_MERGEABLE_BYPASS_APPLY
Previous PR https://github.com/runatlantis/atlantis/pull/2568 by @chroju
=> docs: typo ATLANTIS_GH_ALLOW_MERGEABLE_BYPASS_APPLY

.github/ISSUE_TEMPLATE/feature_request.md
- Use commented out descriptions in feat req
- This allows people to create feature requests without keeping the templated text
- Less mental energy to remove all the templated text
- See this recent issue #2648
=> Use commented out descriptions in feat req

cmd/server.go, runatlantis.io/docs/server-configuration.md, server/controllers/websocket/mux.go, server/controllers/websocket/mux_test.go, server/controllers/websocket/writer.go, server/server.go, server/user_config.go
Add support for enabling same-origin check for WebSocket connection
=> Add argument for enabling same origin check for websocket connections

.github/workflows/atlantis-image.yml
- Used a separate env var in `atlantis-image.yaml` workflow
- This should fix the issue in the `atlantis-image.yaml` workflow
- Previous PR https://github.com/runatlantis/atlantis/pull/2722
- https://github.com/actions/runner/issues/409#issuecomment-752775072
=> atlantis-image: yaml fix using a separate env var

.circleci/config.yml, Dockerfile, testdrive/utils.go, testing/Dockerfile
- deps: update to use tf 1.3.6
=> deps: update to use tf 1.3.6

docker-base/Dockerfile.alpine
- docker-base: alpine: pin git=2.38.2-r0
- Fix broken docker-base builds
- Previous PR https://github.com/runatlantis/atlantis/pull/2770
=> docker-base: alpine: pin git=2.38.2-r0

.github/workflows/atlantis-base.yml, .github/workflows/atlantis-image.yml
- Use correct image suffix for alpine/debian
- We want a prefix only if the image is NOT alpine. This is to keep backwards compatibility.
- Previous PR https://github.com/runatlantis/atlantis/pull/2774
=> Use correct image suffix for alpine/debian (again)

Dockerfile
- Use atlantis-base:2022.12.12
- Latest base
- Depends on PR https://github.com/runatlantis/atlantis/pull/2773
- Depends on PR https://github.com/runatlantis/atlantis/pull/2774
- Depends on PR https://github.com/runatlantis/atlantis/pull/2775
- Previous PR https://github.com/runatlantis/atlantis/pull/2770
=> Use atlantis-base:2022.12.12

.github/dependabot.yml
- Add dependabot for e2e and base container
- Keep dependencies up to date
- https://github.com/dependabot/feedback/issues/145
- current dependencies controlled by dependabot https://github.com/runatlantis/atlantis/network/updates
=> Add dependabot for e2e and base container

go.mod, go.sum, server/core/config/parser_validator.go, server/core/config/parser_validator_test.go, server/events/comment_parser.go
- Use google/shlex
- Deprecate archived dependency and use latest official dependency
- Related issue https://github.com/runatlantis/atlantis/issues/2795
- Old version https://github.com/flynn-archive/go-shlex
- New version https://github.com/google/shlex
=> chore(deps): Use google/shlex

Makefile, go.mod, go.sum, server/controllers/events/events_controller.go, server/controllers/events/events_controller_e2e_test.go, server/controllers/events/github_request_validator.go, server/events/apply_command_runner_test.go, server/events/command_runner.go, server/events/command_runner_test.go, server/events/event_parser.go, server/events/event_parser_test.go, server/events/mocks/matchers/ptr_to_github_issuecommentevent.go, server/events/mocks/matchers/ptr_to_github_pullrequest.go, server/events/mocks/matchers/ptr_to_github_pullrequestevent.go, server/events/mocks/matchers/ptr_to_github_repository.go, server/events/mocks/mock_event_parsing.go, server/events/mocks/mock_github_pull_getter.go, server/events/vcs/fixtures/fixtures.go, server/events/vcs/github_client.go, server/events/vcs/github_credentials.go, server/events/vcs/instrumented_client.go, testdrive/github.go, testdrive/testdrive.go
- Use go-github v48
- Latest go-github library
- Related issue https://github.com/runatlantis/atlantis/issues/2795
- Old version https://github.com/google/go-github/releases/tag/v31.0.0
- New version https://github.com/google/go-github/releases/tag/v48.2.0
=> chore(deps): Use go-github v48

go.mod, go.sum, server/middleware.go, server/server.go
- Upgrade negroni to v3
- Deprecate older version 
- Latest version
- Closes https://github.com/runatlantis/atlantis/pull/2859
=> chore(deps): Upgrade negroni to v3

.github/workflows/release.yml
- Add bump homebrew formula gha
- Bump brew formula upon every non pre release
- Closes https://github.com/runatlantis/atlantis/issues/2870
=> Add bump homebrew formula gha

Dockerfile
- Use atlantis-base:2022.12.29
- Latest base 
- Relates to #2890
=> chore(deps): atlantis-base: use 2022.12.29

.github/PULL_REQUEST_TEMPLATE.md
- Add tests section to PR template
- Ensure changes are tested by the author before they are proposed
N/A
=> docs/build: Add tests section to PR template

.github/workflows/atlantis-base.yml, .github/workflows/atlantis-image.yml
- Add docker labels to images
- Standardization
- Relates to https://github.com/runatlantis/atlantis/issues/2784
- https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/
- https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema
- https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/
=> Add docker labels to images

CHANGELOG.md, kustomize/bundle.yaml, main.go
- chore: release v0.22.1
- hotfix
- After the dependent PR is merged, let's have someone like @mcantinqc test the new `dev` image to verify it works accordingly before cutting a new release.
- waiting for someone to test before merging 
- Dependent on https://github.com/runatlantis/atlantis/pull/2913
- Dependent on #2906
=> chore: release v0.22.1

.circleci/config.yml, Dockerfile, runatlantis.io/docs/terraform-versions.md, testdrive/utils.go, testing/Dockerfile
=> deps: tf 1.3.7

CHANGELOG.md, kustomize/bundle.yaml, main.go
- chore: release v0.22.2
- Fix a few regressions
- Previous PR https://github.com/runatlantis/atlantis/pull/2914
=> chore: release v0.22.2

README.md
- add release svg to readme
- easier to see latest release on mobile devices
[![Latest Release](https://img.shields.io/github/release/runatlantis/atlantis.svg)](https://github.com/runatlantis/atlantis/releases/latest)
=> docs: add release svg to readme

docker-base/Dockerfile.debian
- use 11.6-slim for debian
- similar tagging to Alpine
- more compatible with renovatebot
- same image, different tag
- https://hub.docker.com/_/debian
=> chore(docker): use 11.6-slim

Dockerfile
- set ATLANTIS_BASE_TAG_DATE=latest
- latest base
- previous pr https://github.com/runatlantis/atlantis/pull/2968
- relates to https://github.com/runatlantis/atlantis/pull/2998
=> chore(docker): set ATLANTIS_BASE_TAG_DATE=latest

.github/workflows/atlantis-image.yml
- chore(docker): rm setup-golang from atlantis image workflow
- Not needed
N/A
=> chore(docker): rm setup-golang from atlantis image workflow

runatlantis.io/.vuepress/theme/components/Home.vue
- Add "in production since 2017"
- More accurate than "2 years"
- N/A
=> chore(website): Add "in production since 2017"

CHANGELOG.md, kustomize/bundle.yaml, main.go
- chore: release v0.22.3
- Bug fixes and features
- Previous PR https://github.com/runatlantis/atlantis/pull/2941
- Before merging, we need to ensure the atlantis-base is properly built from the last PR merge
- https://github.com/runatlantis/atlantis/actions/runs/3953685617/jobs/6770331395
- Github / ghcr is having issues so we will rerun it later today
=> chore: release v0.22.3

runatlantis.io/.vuepress/config.js
- Fix website search - it's still failing and this is a work in progress
- closes https://github.com/runatlantis/atlantis/issues/3011
- https://deploy-preview-3012--runatlantis.netlify.app/
- https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#get-search-index
- https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#appid
- https://github.com/vuepress/vuepress-next/issues/797
=> fix: runatlantis.io search

.github/workflows/codeql.yml
- ignore draft prs for codeql
- only run codeql scans when prs are ready to review to save on github action minutes
n/a
=> feat(codeql): ignore draft prs

.github/workflows/lint.yml, .github/workflows/test.yml, README.md
- Add go pkg badge
- show atlantis modules can be extended
- https://deps.dev/go/github.com%2Frunatlantis%2Fatlantis/v0.22.3
- https://pkg.go.dev/badge/?path=https%3A%2F%2Fgithub.com%2Frunatlantis%2Fatlantis
=> docs(readme): Add go pkg badge

README.md
updating slack invite link
previous link expired
yes
=> docs: adding working slack invite link

CODE_OF_CONDUCT.md
=> docs: update slack invite to a perm link

.goreleaser.yml
- sign releases
- best practices
- https://deps.dev/go/github.com%2Frunatlantis%2Fatlantis/v0.22.3
- related to https://github.com/runatlantis/atlantis/issues/3030
- https://goreleaser.com/customization/sign/
=> feat(build): sign releases

go.mod, go.sum, testing/assertions.go
- Swap `go-spew` with `kr/pretty`
- Remove old dependency
- https://github.com/kr/pretty
- https://github.com/davecgh/go-spew
- Slowly implements https://github.com/runatlantis/atlantis/issues/2795
=> chore(dependency): Swap `go-spew` with `kr/pretty`

docker-base/Dockerfile.alpine
- bump docker curl dependency
- docker base is failing to resolve current curl version
- https://github.com/runatlantis/atlantis/actions/runs/4306435530
=> chore(alpine): bump docker curl dependency

.github/workflows/atlantis-image.yml
- add prefix v to tags again
- backwards compatibility
See action https://github.com/nitrocode/atlantis/actions/runs/4310233206/jobs/7518466428 dhows v0.23.0 as the tag
- Previous pr https://github.com/runatlantis/atlantis/pull/3121
=> fix(docker): add prefix v to tags again

Dockerfile
- add terraform 1.4
- latest version
- https://github.com/hashicorp/terraform/releases/tag/v1.4.0
=> feat: add terraform 1.4

server/core/terraform/terraform_client_test.go
- fix terraform ~> 1.3 resolution
- Failing tests
- Previous PR https://github.com/runatlantis/atlantis/pull/3229
=> fix(test): fix terraform ~> 1.3 resolution

runatlantis.io/docs/server-configuration.md
- show `--tf-download` in server-configurations page
- Fix typo
- https://www.runatlantis.io/docs/server-configuration.html#tf-download
- netlify broken due to https://github.com/runatlantis/atlantis/pull/3225
=> docs(typo): show `--tf-download` in server-configurations page

yarn.lock
Reverts runatlantis/atlantis#3225
=> Revert "chore(deps): update dependency @vuepress/plugin-docsearch to v2.0.0-beta.50-pre.1 in package.json"

.gitattributes
- feat: Add .gitattributes
- Always add new lines to select files. This is now automatic within git since git will pick up the new file and make the changes accordingly.
- This will reduce the nitpick we share in PR reviews
- https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
=> chore(repo): Add .gitattributes

.github/workflows/release.yml
- update goreleaser to 1.16.2
- simple config change
=> deps: update goreleaser to 1.16.2

.github/workflows/lint-required.yml, .github/workflows/lint.yml, .github/workflows/test-required.yml, .github/workflows/test.yml
- use ** instead of **/* in paths
- run tests when required
- see incorrect passing run
https://github.com/runatlantis/atlantis/actions/runs/4525391680/jobs/7969849558?pr=2868 in pr #2868
=> fix(workflows): use ** instead of **/* in paths

Dockerfile
- Update `curl` and `libcap` dependencies.
- Outdated dependencies not longer in the repository.
blocks:
- https://github.com/runatlantis/atlantis/pull/3416
=> fix(deps): Update Dockerfile curl and libcap

runatlantis.io/docs/custom-workflows.md
Add the `TF_IN_AUTOMATION` environment variable to the Terragrunt custom workflow documentation.
Remove the unnecessary Terraform suggestion text from the output.
N/A
- https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_in_automation
- #3386
=> chore(docs): Add TF_IN_AUTOMATION to Terragrunt Custom Workflow Docs 

scripts/e2e-deps.sh
- fix jq download
- jq url changed
- see the last few broken merged prs
=> fix(e2e-deps): fix jq download

.github/workflows/pr-lint.yml
- feat(github-actions): Add pr lint workflow
- Ensure PRs follow semantic titles
- pr https://github.com/nitrocode/atlantis/pull/65
- fail https://github.com/nitrocode/atlantis/actions/runs/5161121240/jobs/9297849464?pr=65
- success https://github.com/nitrocode/atlantis/actions/runs/5161124640/jobs/9297856242?pr=65
- https://github.com/amannn/action-semantic-pull-request
=> feat(github-actions): Add pr lint workflow

.github/release.yml
- add release.yml
- Automated release notes
N/A
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
=> feat(release-notes): add release.yml

yarn.lock
Reverts runatlantis/atlantis#3532 This was causing errors when building the the website, not sure why the check's didn't error in the PR until merged to master.
Example: https://github.com/runatlantis/atlantis/actions/runs/5326432557/jobs/9648470244#step:4:48
=> revert(deps): update dependency @vuepress/plugin-docsearch to v2.0.0-beta.50-pre.1 in package.json

MAINTAINERS.md
Adding MAINTAINERS.md file required for CNCF submission
to fulfill requirements for CNCF
=> Adding maintainers file

Dockerfile
Alpine updated curl package
Fix Alpine builds
=> fix: Updating curl package

runatlantis.io/guide/testing-locally.md
Update documentation on how to get access tokens in Bitbucket Server
Documentation out of date
Not required
[Bitbucket Server access token](https://confluence.atlassian.com/bitbucketserver/http-access-tokens-939515499.html)
=> docs: Update testing-locally.md

Dockerfile
- feat(docker): add terraform 1.7
- latest terraform
We've done this before, not much to test
- closes #4201 
- https://github.com/hashicorp/terraform/releases/tag/v1.7.2
- Previous PR https://github.com/runatlantis/atlantis/pull/3914
=> feat(docker): add terraform 1.7

.circleci/config.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Dockerfile, e2e/go.mod, go.mod, testing/Dockerfile
=> feat: support go1.22

Dockerfile
relates to https://github.com/runatlantis/atlantis/pull/4221
=> chore(renovate): update renovate config for dockerfile

runatlantis.io/docs/access-credentials.md
Fixes a very small spelling mistake.
Just annoying.
Read it a few times.
=> fix(docs): Minor spelling of webhooks

runatlantis.io/docs/post-workflow-hooks.md
seen in https://github.com/runatlantis/atlantis/actions/runs/8038966216/job/21955468694
relates to https://github.com/infracost/docs/pull/604
=> docs: update atlantis ref link on infracost.io

.circleci/config.yml, Dockerfile, testdrive/utils.go, testing/Dockerfile
bump to terraform 1.8.0, https://github.com/hashicorp/terraform/releases/tag/v1.8.0
=> chore(tf): bump to terraform 1.8.0

README.md
Add a link to the survey
Adding visibility
N/A
N/A
=> chore: Add link to survey

.github/renovate.json5
- rm broken lock file maintenance
- not working
- reduces pr noise
- https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
=> chore(renovate): rm broken lock file maintenance

package.json, pnpm-lock.yaml
Reverts runatlantis/atlantis#4505
Brakes the website
=> fix: Revert "chore(deps): update dependency @vuepress/theme-default to v2.0.0-rc.26 in package.json (main)"

.github/workflows/website.yml, package.json, playwright.config.js, pnpm-lock.yaml, runatlantis.io/e2e/site-check.spec.js
- add playwright e2e test step to validate the site health
- sometimes, the vuepress PRs would crash the site due to plugin incompatibility 
- Will use this PR to test the functionality
=> feat: run playwright e2e tests

package.json, pnpm-lock.yaml
=> docs: fix navbar issue

.github/renovate.json5
renovate deps in github actions.
----
this would help manage the MUFFET_VERSION in website workflow:
https://github.com/runatlantis/atlantis/blob/cc6c1fc430617bb02bd4830155ad2ee38c659969/.github/workflows/website.yml#L57-L58
=> feat: renovate deps in gh workflows

runatlantis.io/.vitepress/config.ts
followup #4512 
https://vitepress.dev/reference/default-theme-edit-link
=> feat(docs): add editLink config

README.md, server/events/vcs/azuredevops_client.go
=> fix: update hero img loc

package.json, pnpm-lock.yaml, runatlantis.io/.vitepress/config.ts
sitemap.xml diff, https://www.diffchecker.com/0e4Ku2PR/
currently, 
```
$ curl -I https://www.runatlantis.io/robots.txt
HTTP/2 404
age: 0
cache-control: public,max-age=86400,must-revalidate
```
followup #4515
=> feat(docs): create robots.txt and update sitemap.xml

pnpm-lock.yaml
currently the search is broken
update lockfile fixed the issue
=> fix(docs): update lockfile and fix search

.github/workflows/test.yml
manually cherry-pick #4592 #4594 changes as bot not working
=> fix: cherry-pick e2e test fixes (#4592 #4594) (release-0.28)

runatlantis.io/guide/testing-locally.md
Hi,
Just a typo fix that I found when I was reading the documentation.
Thank you for your work!
=> docs: fix typo about Gitea

runatlantis.io/.vitepress/components/Banner.vue
=> chore: add toc vote info

package-lock.json, package.json
relates to https://github.com/jbaubree/sitemap-ts/issues/96
=> chore(deps): update sitemap-ts and vitepress

.github/workflows/release.yml, .goreleaser.yml
also update yaml config to v2 (nothing changes much)
=> feat: goreleaser-action v6

.github/workflows/atlantis-image.yml, .github/workflows/codeql.yml, .github/workflows/labeler.yml, .github/workflows/lint.yml, .github/workflows/pr-lint.yml, .github/workflows/release.yml, .github/workflows/renovate-config.yml, .github/workflows/stale.yml, .github/workflows/test.yml, .github/workflows/testing-env-image.yml, .github/workflows/website.yml
=> feat: bump action runner from ubuntu-22.04 to ubuntu-24.04

.github/workflows/test.yml, Dockerfile, testing/Dockerfile
=> chore(deps): bump to tf 1.9.2

.github/workflows/test.yml
=> chore(deps): ngrok 3.13.0

Dockerfile
- chore(deps): track alpine ca-certificates dep
relates to:
- #4734
- #4759
=> chore(deps): track alpine ca-certificates dep

runatlantis.io/docs/custom-workflows.md
- feat(docs): add aws provider contextual tags using env vars
- Let's tag everything with repo and repo dir
- https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.62.0
=> feat(docs): add aws provider contextual tags using env vars

server/core/config/raw/policies.go
yaml should also be `prevent_self_approve`
=> fix: set yaml to prevent_self_approve

.github/workflows/scorecard.yml, README.md
- add openssf scorecard and badge
- Improve security integrity in atlantis project
This action has been tested in other projects such as cloudposse and terraform-aws-domain-protect
- Brings visibility to #3030 
- https://securityscorecards.dev/#how-it-works
- example https://scorecard.dev/viewer/?uri=github.com/runatlantis/atlantis
- main repo https://github.com/ossf/scorecard
- action https://github.com/ossf/scorecard-action
- https://www.bestpractices.dev/en/projects/9428
=> docs: add openssf scorecard and badge

e2e/github.go, e2e/go.mod, e2e/go.sum, go.mod, go.sum, server/controllers/events/events_controller.go, server/controllers/events/events_controller_e2e_test.go, server/controllers/events/events_controller_test.go, server/controllers/events/github_request_validator.go, server/events/apply_command_runner_test.go, server/events/command_runner.go, server/events/command_runner_test.go, server/events/event_parser.go, server/events/event_parser_test.go, server/events/mocks/mock_event_parsing.go, server/events/mocks/mock_github_pull_getter.go, server/events/plan_command_runner_test.go, server/events/vcs/github_client.go, server/events/vcs/github_credentials.go, server/events/vcs/instrumented_client.go, server/events/vcs/mocks/mock_github_pull_request_getter.go, server/events/vcs/testdata/fixtures.go, testdrive/github.go, testdrive/testdrive.go
- upgrade go-github 63.x
- Manual upgrade using new HookConfig struct
See PR checks
- Closes https://github.com/runatlantis/atlantis/pull/4938
- https://github.com/google/go-github/pull/3073
- Struct changes in https://github.com/google/go-github/releases/tag/v60.0.0
- Upgraded to https://github.com/google/go-github/releases/tag/v63.0.0
=> chore(deps): upgrade go-github 63.x

SECURITY.md
- docs: add maintained releases to security text
- Explicitly call out why renovate PRs for security updates may be closed
N/A
- Slack discussion https://atlantis-community.slack.com/archives/C06AG0FDJ79/p1727113172976279
- Related https://github.com/runatlantis/atlantis/pull/4817
=> docs: add maintained releases to security text

CODE_OF_CONDUCT.md, README.md, runatlantis.io/index.md
Adding New CNCF slack join links
=> docs: Adding new slack link

runatlantis.io/docs/server-configuration.md
Fix the markdown formatting on `server-configuration.md`
=> chore(docs): Fix formatting on server-configuration.md

LICENSE
- set license to official apache 2.0
- Official text for official license
- This also improves the OpenSSF license to 10/10
N/A
- https://www.apache.org/licenses/LICENSE-2.0.txt
- https://scorecard.dev/viewer/?uri=github.com/runatlantis/atlantis
- https://github.com/ossf/scorecard/blob/ea7e27ed41b76ab879c862fa0ca4cc9c61764ee4/docs/checks.md#license
=> docs: set license to official apache 2.0

.github/workflows/lint.yml, Dockerfile, e2e/go.mod, go.mod, server/events/vcs/github_client.go, testing/Dockerfile
bump alpine image and ca-certificates
=> chore(deps): update alpine to 3.21.0, ca-certificates to 20241010, go/golangci-lint to latest

.github/workflows/website.yml, package-lock.json, package.json
fix https://github.com/advisories/GHSA-vg6x-rcgg-rjx6
=> chore(deps): bump vite to 5.4.12

e2e/README.md
Add doc to explain how to rotate gitlab token.
@jamengual and I have done this a few times and forgotten the specifics each time, hopefully this will be enough of a pointer.
N/A
N/A
=> chore: Add doc for how to rotate gitlab token

Makefile, runatlantis.io/.vitepress/config.ts
add trademark footer note per https://github.com/cncf/foundation/blob/main/website-guidelines.md
=> chore(website): add trademark footer note

runatlantis.io/.vitepress/config.ts
Work done as a part of:
- https://github.com/cncf/sandbox/issues/141
- https://cncfservicedesk.atlassian.net/browse/CNCFSD-2686
/cc @jamengual @krook
=> chore: configure new CNCF GA4 analytics ID

.github/workflows/website.yml, .lycheeignore
https://github.com/runatlantis/atlantis/pull/5337 for Release 0.32
=> chore(website): Update link checker to use Lychee (release-0.32)

runatlantis.io/contributing/events-controller.md, runatlantis.io/docs/access-credentials.md, runatlantis.io/docs/command-requirements.md, runatlantis.io/guide/testing-locally.md
https://github.com/runatlantis/atlantis/pull/5341 for release 0.32
=> docs: update gitlab links (release-0.32)

.github/workflows/website.yml
- ci(website): use .node-version file
- The node version file already exists so let's use it
- consistency with other actions/setup-node
- One less custom dependency that needs to be updated by renovate
N/A
N/A
=> ci(website): use .node-version file

package-lock.json
=> chore(deps): update vite

.github/renovate.json5
- ci(renovate): only update node deps on main branch
- Prevent needing to manually close renovate branches e.g. https://github.com/runatlantis/atlantis/pull/5498
- https://docs.renovatebot.com/configuration-options/#matchbasebranches
=> ci(renovate): only update node deps on main branch

.github/release.yml
- ci(release): add sections per provider
- Before users upgrade, it's important to know what changed with their provider. This helps make it easier to see those changes per release 
N/A
=> ci(release): add sections per provider

.github/release.yml
- ci(release): separate section for security
- This way it's clearer what security fixes are per release
N/A
=> ci(release): separate section for security

.github/renovate.json5
- ci(renovate): replace hardcoded branches with regex
- Prevent hard coding branches which makes it easier to release new versions and maintain older versions
- https://docs.renovatebot.com/configuration-options/#basebranches
=> ci(renovate): replace hardcoded branches with regex

CODEOWNERS
- chore(codeowners): add app/renovate-approve
- Allow renovate-approved changes to be mergeable
- Ignore the codeowners error because this is suggested by others including the lead maintainer. See references.
- https://github.com/renovatebot/renovate-approve-bot/issues/23
- https://github.com/search?q=app%2Frenovate-approve+path%3Acodeowners&type=code
- Prevents manual approval of PRs like https://github.com/runatlantis/atlantis/pull/5543
=> ci(codeowners): add app/renovate-approve

.github/renovate.json5, .github/workflows/renovate-config.yml
- ci: release branches for security updates only
- Fewer PRs that are duplicated across release branches
- https://docs.renovatebot.com/configuration-options/#matchbasebranches
=> ci: release branches for security updates only
